export default {
  "id": "license",
  "word": "license",
  "number": 1085,
  "version": 2,
  "mass": true,
  "senses": [
    {
      "id": "license-mcq-01",
      "title": "政府／機構正式授予某人做、持有、使用某事物的許可",
      "form": "licence — official",
      "en": "licence — official",
      "zh": "政府／機構正式授予某人做、持有、使用某事物的許可",
      "note": "來源詞義：政府／機構正式授予某人做、持有、使用某事物的許可",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-02",
      "title": "證明已獲上述許可的牌照／執照／許可證",
      "form": "licence — document",
      "en": "licence — document",
      "zh": "證明已獲上述許可的牌照／執照／許可證",
      "note": "來源詞義：證明已獲上述許可的牌照／執照／許可證",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-03",
      "title": "允許企業進行指定商業活動的牌照",
      "form": "business licence",
      "en": "business licence",
      "zh": "允許企業進行指定商業活動的牌照",
      "note": "來源詞義：允許企業進行指定商業活動的牌照",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-04",
      "title": "允許機構／企業正式營運的牌照",
      "form": "operating licence",
      "en": "operating licence",
      "zh": "允許機構／企業正式營運的牌照",
      "note": "來源詞義：允許機構／企業正式營運的牌照",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-05",
      "title": "關於申請、持有、遵守及續期牌照的發牌規定",
      "form": "licensing rules",
      "en": "licensing rules",
      "zh": "關於申請、持有、遵守及續期牌照的發牌規定",
      "note": "來源詞義：關於申請、持有、遵守及續期牌照的發牌規定",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-06",
      "title": "負責審批、發出和監管牌照的機構",
      "form": "licensing authority",
      "en": "licensing authority",
      "zh": "負責審批、發出和監管牌照的機構",
      "note": "來源詞義：負責審批、發出和監管牌照的機構",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-07",
      "title": "申請／維持牌照所需費用",
      "form": "licence fee",
      "en": "licence fee",
      "zh": "申請／維持牌照所需費用",
      "note": "來源詞義：申請／維持牌照所需費用",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-08",
      "title": "持有相關牌照的人／機構",
      "form": "licence holder",
      "en": "licence holder",
      "zh": "持有相關牌照的人／機構",
      "note": "來源詞義：持有相關牌照的人／機構",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-09",
      "title": "把即將到期牌照續期",
      "form": "renew a licence",
      "en": "renew a licence",
      "zh": "把即將到期牌照續期",
      "note": "來源詞義：把即將到期牌照續期",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-10",
      "title": "暫時停止牌照效力",
      "form": "suspend a licence",
      "en": "suspend a licence",
      "zh": "暫時停止牌照效力",
      "note": "來源詞義：暫時停止牌照效力",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-11",
      "title": "正式撤銷牌照",
      "form": "revoke a licence",
      "en": "revoke a licence",
      "zh": "正式撤銷牌照",
      "note": "來源詞義：正式撤銷牌照",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-12",
      "title": "持牌人主動交回／放棄牌照",
      "form": "surrender a licence",
      "en": "surrender a licence",
      "zh": "持牌人主動交回／放棄牌照",
      "note": "來源詞義：持牌人主動交回／放棄牌照",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-13",
      "title": "駕駛執照",
      "form": "driving licence / driver's license",
      "en": "driving licence / driver's license",
      "zh": "駕駛執照",
      "note": "來源詞義：駕駛執照",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-14",
      "title": "法律／監管制度要求的專業執業資格",
      "form": "professional licence",
      "en": "professional licence",
      "zh": "法律／監管制度要求的專業執業資格",
      "note": "來源詞義：法律／監管制度要求的專業執業資格",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-15",
      "title": "專業領域取得／維持法定執照的制度或狀態",
      "form": "licensure",
      "en": "licensure",
      "zh": "專業領域取得／維持法定執照的制度或狀態",
      "note": "來源詞義：專業領域取得／維持法定執照的制度或狀態",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-16",
      "title": "工作某些職業前必須取得政府／監管牌照的制度",
      "form": "occupational licensing",
      "en": "occupational licensing",
      "zh": "工作某些職業前必須取得政府／監管牌照的制度",
      "note": "來源詞義：工作某些職業前必須取得政府／監管牌照的制度",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-17",
      "title": "進口／出口指定貨物的官方許可",
      "form": "import/export licence",
      "en": "import/export licence",
      "zh": "進口／出口指定貨物的官方許可",
      "note": "來源詞義：進口／出口指定貨物的官方許可",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-18",
      "title": "進行廣播／使用指定頻譜的官方牌照",
      "form": "broadcast/spectrum licence",
      "en": "broadcast/spectrum licence",
      "zh": "進行廣播／使用指定頻譜的官方牌照",
      "note": "來源詞義：進行廣播／使用指定頻譜的官方牌照",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-19",
      "title": "依法售賣／供應酒類的酒牌",
      "form": "alcohol/liquor licence",
      "en": "alcohol/liquor licence",
      "zh": "依法售賣／供應酒類的酒牌",
      "note": "來源詞義：依法售賣／供應酒類的酒牌",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-20",
      "title": "已獲准進行指定受規管活動的持牌場所",
      "form": "licensed premises",
      "en": "licensed premises",
      "zh": "已獲准進行指定受規管活動的持牌場所",
      "note": "來源詞義：已獲准進行指定受規管活動的持牌場所",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-21",
      "title": "取得／持有授權的人或公司",
      "form": "licensee",
      "en": "licensee",
      "zh": "取得／持有授權的人或公司",
      "note": "來源詞義：取得／持有授權的人或公司",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-22",
      "title": "把使用權授予他人的權利持有人",
      "form": "licensor",
      "en": "licensor",
      "zh": "把使用權授予他人的權利持有人",
      "note": "來源詞義：把使用權授予他人的權利持有人",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-23",
      "title": "正式給予某人／企業進行指定活動的許可",
      "form": "license — verb",
      "en": "license — verb",
      "zh": "正式給予某人／企業進行指定活動的許可",
      "note": "來源詞義：正式給予某人／企業進行指定活動的許可",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-24",
      "title": "權利人保留知識產權所有權，但容許另一方按條款使用",
      "form": "IP licence",
      "en": "IP licence",
      "zh": "權利人保留知識產權所有權，但容許另一方按條款使用",
      "note": "來源詞義：權利人保留知識產權所有權，但容許另一方按條款使用",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-25",
      "title": "容許指定方式使用受版權保護作品的授權",
      "form": "copyright licence",
      "en": "copyright licence",
      "zh": "容許指定方式使用受版權保護作品的授權",
      "note": "來源詞義：容許指定方式使用受版權保護作品的授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-26",
      "title": "容許另一方在指定範圍內使用專利權的授權",
      "form": "patent licence",
      "en": "patent licence",
      "zh": "容許另一方在指定範圍內使用專利權的授權",
      "note": "來源詞義：容許另一方在指定範圍內使用專利權的授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-27",
      "title": "容許另一方按條件使用商標的授權",
      "form": "trademark licence",
      "en": "trademark licence",
      "zh": "容許另一方按條件使用商標的授權",
      "note": "來源詞義：容許另一方按條件使用商標的授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-28",
      "title": "經相關品牌／IP 權利人正式授權製造或出售的產品",
      "form": "licensed product",
      "en": "licensed product",
      "zh": "經相關品牌／IP 權利人正式授權製造或出售的產品",
      "note": "來源詞義：經相關品牌／IP 權利人正式授權製造或出售的產品",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-29",
      "title": "在權利人正式許可下生產／使用",
      "form": "under licence",
      "en": "under licence",
      "zh": "在權利人正式許可下生產／使用",
      "note": "來源詞義：在權利人正式許可下生產／使用",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-30",
      "title": "訂明授權範圍、期限、費用等條件的合約",
      "form": "licence agreement",
      "en": "licence agreement",
      "zh": "訂明授權範圍、期限、費用等條件的合約",
      "note": "來源詞義：訂明授權範圍、期限、費用等條件的合約",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-31",
      "title": "在界定範圍內給特定被授權方的獨家授權",
      "form": "exclusive licence",
      "en": "exclusive licence",
      "zh": "在界定範圍內給特定被授權方的獨家授權",
      "note": "來源詞義：在界定範圍內給特定被授權方的獨家授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-32",
      "title": "同類權利可同時授予多個被授權方的非獨家授權",
      "form": "non-exclusive licence",
      "en": "non-exclusive licence",
      "zh": "同類權利可同時授予多個被授權方的非獨家授權",
      "note": "來源詞義：同類權利可同時授予多個被授權方的非獨家授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-33",
      "title": "使用權需要支付特許權使用費的授權",
      "form": "royalty-bearing licence",
      "en": "royalty-bearing licence",
      "zh": "使用權需要支付特許權使用費的授權",
      "note": "來源詞義：使用權需要支付特許權使用費的授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-34",
      "title": "不需逐次另付 royalty；不一定完全免費",
      "form": "royalty-free licence",
      "en": "royalty-free licence",
      "zh": "不需逐次另付 royalty；不一定完全免費",
      "note": "來源詞義：不需逐次另付 royalty；不一定完全免費",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-35",
      "title": "沒有預設到期日、依合約條件持續有效的授權",
      "form": "perpetual licence",
      "en": "perpetual licence",
      "zh": "沒有預設到期日、依合約條件持續有效的授權",
      "note": "來源詞義：沒有預設到期日、依合約條件持續有效的授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-36",
      "title": "在原授權容許下，把部分權利再授權第三方",
      "form": "sublicence",
      "en": "sublicence",
      "zh": "在原授權容許下，把部分權利再授權第三方",
      "note": "來源詞義：在原授權容許下，把部分權利再授權第三方",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-37",
      "title": "雙方互相授予知識產權使用權",
      "form": "cross-licence",
      "en": "cross-licence",
      "zh": "雙方互相授予知識產權使用權",
      "note": "來源詞義：雙方互相授予知識產權使用權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-38",
      "title": "法律在指定條件下允許／要求的強制授權",
      "form": "compulsory licence",
      "en": "compulsory licence",
      "zh": "法律在指定條件下允許／要求的強制授權",
      "note": "來源詞義：法律在指定條件下允許／要求的強制授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-39",
      "title": "規定使用者可以如何合法安裝、使用、複製等軟件的授權",
      "form": "software licence",
      "en": "software licence",
      "zh": "規定使用者可以如何合法安裝、使用、複製等軟件的授權",
      "note": "來源詞義：規定使用者可以如何合法安裝、使用、複製等軟件的授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-40",
      "title": "終端使用者與軟件權利方之間的使用授權協議",
      "form": "EULA",
      "en": "EULA",
      "zh": "終端使用者與軟件權利方之間的使用授權協議",
      "note": "來源詞義：終端使用者與軟件權利方之間的使用授權協議",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-41",
      "title": "只授權指定單一使用者使用",
      "form": "single-user licence",
      "en": "single-user licence",
      "zh": "只授權指定單一使用者使用",
      "note": "來源詞義：只授權指定單一使用者使用",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-42",
      "title": "授權一個指定機構／場地內廣泛使用",
      "form": "site licence",
      "en": "site licence",
      "zh": "授權一個指定機構／場地內廣泛使用",
      "note": "來源詞義：授權一個指定機構／場地內廣泛使用",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-43",
      "title": "以同時使用人數／共享授權池限制使用",
      "form": "concurrent/floating licence",
      "en": "concurrent/floating licence",
      "zh": "以同時使用人數／共享授權池限制使用",
      "note": "來源詞義：以同時使用人數／共享授權池限制使用",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-44",
      "title": "為企業／機構大量使用者或設備安排的批量授權",
      "form": "volume licence",
      "en": "volume licence",
      "zh": "為企業／機構大量使用者或設備安排的批量授權",
      "note": "來源詞義：為企業／機構大量使用者或設備安排的批量授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-45",
      "title": "在訂閱有效期間提供的使用權",
      "form": "subscription licence",
      "en": "subscription licence",
      "zh": "在訂閱有效期間提供的使用權",
      "note": "來源詞義：在訂閱有效期間提供的使用權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-46",
      "title": "符合開源原則，容許使用、修改及再分發的軟件授權",
      "form": "open-source licence",
      "en": "open-source licence",
      "zh": "符合開源原則，容許使用、修改及再分發的軟件授權",
      "note": "來源詞義：符合開源原則，容許使用、修改及再分發的軟件授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-47",
      "title": "讓創作者預先規定作品重用、改編、商業使用等條件的標準版權授權",
      "form": "Creative Commons licence",
      "en": "Creative Commons licence",
      "zh": "讓創作者預先規定作品重用、改編、商業使用等條件的標準版權授權",
      "note": "來源詞義：讓創作者預先規定作品重用、改編、商業使用等條件的標準版權授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-48",
      "title": "規定資料／內容如何被重用、分發、修改的授權",
      "form": "data/content licence",
      "en": "data/content licence",
      "zh": "規定資料／內容如何被重用、分發、修改的授權",
      "note": "來源詞義：規定資料／內容如何被重用、分發、修改的授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-49",
      "title": "對音樂作品／錄音的指定使用方式取得版權許可",
      "form": "music licensing",
      "en": "music licensing",
      "zh": "對音樂作品／錄音的指定使用方式取得版權許可",
      "note": "來源詞義：對音樂作品／錄音的指定使用方式取得版權許可",
      "examples": [
        [
          "Licensing is handled by the local authority.",
          "發牌工作由地方當局負責。",
          "對音樂作品／錄音的指定使用方式取得版權許可"
        ]
      ],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-50",
      "title": "土地權利人容許另一人進入／使用土地，而不一定授予租賃權益",
      "form": "property licence",
      "en": "property licence",
      "zh": "土地權利人容許另一人進入／使用土地，而不一定授予租賃權益",
      "note": "來源詞義：土地權利人容許另一人進入／使用土地，而不一定授予租賃權益",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-51",
      "title": "車輛的車牌／登記牌",
      "form": "license plate — AmE",
      "en": "license plate — AmE",
      "zh": "車輛的車牌／登記牌",
      "note": "來源詞義：車輛的車牌／登記牌",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-52",
      "title": "正式：給人很大的行動／創作自由",
      "form": "licence — freedom",
      "en": "licence — freedom",
      "zh": "正式：給人很大的行動／創作自由",
      "note": "來源詞義：正式：給人很大的行動／創作自由",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-53",
      "title": "不受正常規則約束而任意行事的放縱",
      "form": "licence — excessive freedom",
      "en": "licence — excessive freedom",
      "zh": "不受正常規則約束而任意行事的放縱",
      "note": "來源詞義：不受正常規則約束而任意行事的放縱",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-54",
      "title": "創作者為藝術效果不必完全遵從現實／事實的自由",
      "form": "artistic licence",
      "en": "artistic licence",
      "zh": "創作者為藝術效果不必完全遵從現實／事實的自由",
      "note": "來源詞義：創作者為藝術效果不必完全遵從現實／事實的自由",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-55",
      "title": "詩人／作家為文學效果偏離一般事實或語言規則的自由",
      "form": "poetic licence",
      "en": "poetic licence",
      "zh": "詩人／作家為文學效果偏離一般事實或語言規則的自由",
      "note": "來源詞義：詩人／作家為文學效果偏離一般事實或語言規則的自由",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-56",
      "title": "被視為可以任意做某件事的權限",
      "form": "licence to do X — figurative",
      "en": "licence to do X — figurative",
      "zh": "被視為可以任意做某件事的權限",
      "note": "來源詞義：被視為可以任意做某件事的權限",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-57",
      "title": "比喻幾乎不費力就能大量賺錢的生意／特權",
      "form": "licence to print money",
      "en": "licence to print money",
      "zh": "比喻幾乎不費力就能大量賺錢的生意／特權",
      "note": "來源詞義：比喻幾乎不費力就能大量賺錢的生意／特權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-58",
      "title": "已取得法定／合約授權的",
      "form": "licensed",
      "en": "licensed",
      "zh": "已取得法定／合約授權的",
      "note": "來源詞義：已取得法定／合約授權的",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-59",
      "title": "未取得依法／合約要求的授權",
      "form": "unlicensed",
      "en": "unlicensed",
      "zh": "未取得依法／合約要求的授權",
      "note": "來源詞義：未取得依法／合約要求的授權",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    },
    {
      "id": "license-mcq-60",
      "title": "再次授權或改用另一套授權條款",
      "form": "relicense",
      "en": "relicense",
      "zh": "再次授權或改用另一套授權條款",
      "note": "來源詞義：再次授權或改用另一套授權條款",
      "examples": [],
      "options": [],
      "excludedOverlaps": []
    }
  ],
  "questions": [
    {
      "id": "license-06-0",
      "sense": "license-mcq-49",
      "en": "Licensing is handled by the local authority.",
      "zh": "發牌工作由地方當局負責。",
      "masked": "____ is handled by the local authority.",
      "options": [
        "license-mcq-49",
        "license-mcq-48",
        "license-mcq-50",
        "license-mcq-47",
        "license-mcq-51",
        "license-mcq-46"
      ],
      "explanation": "本句的「Licensing」指「對音樂作品／錄音的指定使用方式取得版權許可」。",
      "sentenceIndex": 0,
      "sourcePractice": 6,
      "targets": [
        "Licensing"
      ],
      "optionReasons": {
        "license-mcq-49": "本句指「對音樂作品／錄音的指定使用方式取得版權許可」。",
        "license-mcq-48": "「規定資料／內容如何被重用、分發、修改的授權」與本句語境不同。",
        "license-mcq-50": "「土地權利人容許另一人進入／使用土地，而不一定授予租賃權益」與本句語境不同。",
        "license-mcq-47": "「讓創作者預先規定作品重用、改編、商業使用等條件的標準版權授權」與本句語境不同。",
        "license-mcq-51": "「車輛的車牌／登記牌」與本句語境不同。",
        "license-mcq-46": "「符合開源原則，容許使用、修改及再分發的軟件授權」與本句語境不同。"
      },
      "correctOption": "license-mcq-49"
    }
  ],
  "comparisons": [],
  "source": {
    "path": "manuals/license.pdf",
    "file": "1085_license_Polysemy Exercise.pdf",
    "sha256": "25ae902f468b095122b972e17693b94f4dd39da4cc42aa4aa84379dd5ef71300",
    "pages": 50
  },
  "mcqSource": "pdf-authored-master-table"
};
