import {hubSession,hubRequest,escapeHtml as esc} from './learning-hub-client.mjs';
const listening=location.pathname.endsWith('listening-system.html'),reading=location.pathname.includes('reading-comprehension'),paper3=location.pathname.includes('dse-paper3')||location.pathname.startsWith('/paper3/');
const system=listening?'listening':'reading',main=document.querySelector('main')||document.body;
const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('./study-support.css',import.meta.url);document.head.append(css);
const account=()=>hubSession()?.id||hubSession()?.name||'guest';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));}catch{}};
function context(question,node){const source=window.EdmundListeningTools?.context?.()||{system:'reading',url:location.pathname+location.search,title:document.title};return {...source,question:String(question),excerpt:(node?.innerText||node?.textContent||'').slice(0,8000)};}
const keyFor=c=>`${c.url}#question=${c.question}`;
export async function editMistake(c){const key=keyFor(c),draftKey='mistake-draft:'+account()+':'+key,d=document.createElement('dialog');d.className='study-note-dialog';d.innerHTML=`<form><h2>My mistake · 我的錯誤筆記</h2><p>${esc([c.section,c.year,c.practice?'Practice '+c.practice:'',c.part?'Part / Task '+c.part:'',c.title,'Question '+c.question].filter(Boolean).join(' · '))}</p><details><summary>Question context · 題目內容</summary><p>${esc(c.excerpt)}</p></details><textarea rows="7" maxlength="12000" placeholder="What went wrong? What will you do next time?" aria-label="Mistake note"></textarea><p role="status">Loading…</p><button type="submit" disabled>Save · 儲存</button><button type="button" data-close>Close · 關閉</button></form>`;document.body.append(d);d.showModal();const field=d.querySelector('textarea'),status=d.querySelector('[role=status]'),save=d.querySelector('[type=submit]');let version=0;field.value=read(draftKey,'');field.oninput=()=>write(draftKey,field.value);d.querySelector('[data-close]').onclick=()=>d.remove();d.oncancel=()=>d.remove();try{const row=await hubRequest('mistakes','get',{key});version=row?.version||0;if(!field.value)field.value=row?.body||'';status.textContent='';save.disabled=false;}catch(error){status.textContent=error.message;}d.querySelector('form').onsubmit=async e=>{e.preventDefault();save.disabled=true;try{const row=await hubRequest('mistakes','save',{key,system:c.system,context:c,body:field.value,version});version=row.version;localStorage.removeItem(draftKey);status.textContent='Saved to your account · 已儲存至帳戶';document.dispatchEvent(new Event('mistake-saved'));}catch(error){status.textContent=error.message;}finally{save.disabled=false;}};}
if(!location.pathname.endsWith('mistake-logbook.html')){
const bar=document.createElement('div');bar.className='study-tools';bar.innerHTML=`${listening?'<label>Text size · 字體 <button type="button" data-font="-.25">−</button> <output data-font-size>1×</output> <button type="button" data-font=".25">＋</button></label>':''}${!reading?'<button type="button" data-brush aria-pressed="false">🖍 Temporary highlight · 暫時螢光筆</button>':''}${!paper3?`<a href="mistake-logbook.html?system=${system}">Mistake logbook · 錯誤筆記簿</a>`:''}`;main.prepend(bar);
let brush=false,ranges=[];function clear(){ranges=[];CSS.highlights?.delete('study-teaching');main.querySelectorAll('mark.study-highlight').forEach(n=>n.replaceWith(...n.childNodes));}
bar.querySelector('[data-brush]')?.addEventListener('click',e=>{brush=!brush;if(!brush)clear();e.currentTarget.setAttribute('aria-pressed',brush);e.currentTarget.textContent=brush?'Clear highlights · 清除螢光筆':'🖍 Temporary highlight · 暫時螢光筆';});
main.addEventListener('pointerup',()=>setTimeout(()=>{if(!brush)return;const selection=getSelection();if(!selection?.rangeCount||selection.isCollapsed)return;const r=selection.getRangeAt(0);if(!main.contains(r.commonAncestorContainer)||r.startContainer.parentElement.closest('input,textarea,button,.study-tools'))return;if(globalThis.CSS?.highlights&&globalThis.Highlight){ranges=ranges.filter(r=>r.startContainer.isConnected);ranges.push(r.cloneRange());CSS.highlights.set('study-teaching',new Highlight(...ranges));}else{const nodes=[],walker=document.createTreeWalker(main,NodeFilter.SHOW_TEXT);while(walker.nextNode())if(r.intersectsNode(walker.currentNode))nodes.push(walker.currentNode);for(const n of nodes.reverse()){if(!n.textContent.trim()||n.parentElement.closest('input,textarea,button,mark,.study-tools'))continue;const part=document.createRange(),a=n===r.startContainer?r.startOffset:0,b=n===r.endContainer?r.endOffset:n.length;if(b<=a)continue;part.setStart(n,a);part.setEnd(n,b);const mark=document.createElement('mark');mark.className='study-highlight';part.surroundContents(mark);}}selection.removeAllRanges();},0));
let scale=read('edmund-listening-text-scale',1);scale=Math.max(.25,Math.min(5,Number(scale)||1));const fonts=new WeakMap();function sizeText(){if(!listening)return;main.querySelectorAll('[data-text-scale]').forEach(select=>{select.value=String(scale);});const output=bar.querySelector('[data-font-size]');if(output.textContent!==scale+'×')output.textContent=scale+'×';const nodes=[...main.querySelectorAll('.dse-paper-sheet p,.dse-paper-sheet td,.dse-paper-sheet th,.dse-paper-sheet span,.dse-paper-sheet label,.dse-paper-sheet li,.listening-question-card,.listening-question-card p,.listening-question-card span,.dse-task-paper,.dse-task-paper p,.dse-task-paper td,.dse-task-paper span,.dse-question-block,.dse-question-block p,.dse-question-block td,.dse-question-block span,.dse-question-block label,.dse-multiple-choice,.dse-multiple-choice p,.dse-multiple-choice span,.dse-answer-gap,.transcript-line,.transcript-line span')];for(const el of nodes){if(fonts.has(el))el.style.fontSize=fonts.get(el)+'px';}for(const el of nodes){if(!fonts.has(el))fonts.set(el,parseFloat(getComputedStyle(el).fontSize));}for(const el of nodes){if(el.closest('.study-tools'))continue;el.style.fontSize=fonts.get(el)*scale+'px';el.style.lineHeight='1.5';}}
bar.querySelectorAll('[data-font]').forEach(b=>b.onclick=()=>{scale=Math.max(.25,Math.min(5,Math.round((scale+Number(b.dataset.font))*4)/4));write('edmund-listening-text-scale',scale);sizeText();});
document.addEventListener('change',e=>{if(e.target.matches('[data-text-scale]')){scale=Number(e.target.value);write('edmund-listening-text-scale',scale);sizeText();}});
function attachQuestions(){if(paper3)return;const candidates=listening?[...main.querySelectorAll('input[data-answer-q],input[data-dse-answer-q],select[data-dse-answer-q],input[data-dse-answer-group],.listening-question-card[data-question-card]')]:[...main.querySelectorAll('.question-card[data-question]')];const seen=new Set();for(const node of candidates){const number=node.dataset.answerQ||node.dataset.dseAnswerQ||node.dataset.dseAnswerGroup||node.dataset.questionCard||node.dataset.question;if(!number||seen.has(number))continue;seen.add(number);const host=node.matches('input,select')?(node.closest('.listening-gap-unit,.dse-answer-gap')||node.parentElement):node;if(host.querySelector('[data-mistake-note]'))continue;const b=document.createElement('button');b.type='button';b.className='mistake-note-button';b.dataset.mistakeNote=number;b.textContent='✎';b.title='My mistake · 我的錯誤筆記';b.setAttribute('aria-label',b.title+' '+number);b.onclick=e=>{e.preventDefault();e.stopPropagation();editMistake(context(number,node.closest('article,tr,.dse-question-block')||host));};host.append(b);}
if(listening)for(const input of main.querySelectorAll('input[data-answer-q],input[data-dse-answer-q]')){if(['radio','checkbox'].includes(input.type)||input.dataset.posAdded)continue;input.dataset.posAdded='true';const field=document.createElement('input');field.className='pos-guess';field.placeholder='Guess the POS';field.setAttribute('aria-label','Guess the POS · 預測詞性');field.maxLength=100;const key='pos-guess:'+account()+':'+keyFor(context(input.dataset.answerQ||input.dataset.dseAnswerQ,input));field.value=read(key,'');field.oninput=()=>write(key,field.value);const host=input.closest('label')||input;host.after(field);}}
function transcriptFloat(section){if(section.dataset.floatReady)return;section.dataset.floatReady='true';const header=section.querySelector('.listening-transcript__head'),lines=section.querySelector('.transcript-lines');if(!header||!lines)return;const button=document.createElement('button');button.type='button';button.textContent='Float transcript · 浮動錄音稿';header.append(button);let floating=false,manualUntil=0;const follow=document.createElement('button');follow.type='button';follow.textContent='Follow audio · 跟隨錄音';follow.hidden=true;header.append(follow);follow.onclick=()=>{manualUntil=0;scroll();};button.onclick=()=>{floating=!floating;section.classList.toggle('transcript-floating',floating);button.textContent=floating?'Restore transcript · 還原錄音稿':'Float transcript · 浮動錄音稿';follow.hidden=!floating;if(!floating){section.style.left='';section.style.top='';section.style.right='';section.style.bottom='';}scroll();};for(const event of ['wheel','touchstart','pointerdown'])lines.addEventListener(event,()=>manualUntil=Date.now()+8000,{passive:true});function scroll(){if(!floating||Date.now()<manualUntil)return;const current=lines.querySelector('.is-current');if(current)lines.scrollTop+=current.getBoundingClientRect().top-lines.getBoundingClientRect().top-8;}
new MutationObserver(scroll).observe(lines,{subtree:true,attributes:true,attributeFilter:['class']});let drag;header.addEventListener('pointerdown',e=>{if(!floating||e.target.closest('button'))return;const box=section.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:box.left,top:box.top};header.setPointerCapture(e.pointerId);});header.addEventListener('pointermove',e=>{if(!drag)return;section.style.left=Math.max(0,Math.min(innerWidth-100,drag.left+e.clientX-drag.x))+'px';section.style.top=Math.max(0,Math.min(innerHeight-80,drag.top+e.clientY-drag.y))+'px';section.style.right='auto';section.style.bottom='auto';});header.addEventListener('pointerup',()=>drag=null);}
function speed(){const bar=document.querySelector('[data-floating-audio]');if(!bar||bar.querySelector('[data-floating-speed]'))return;const label=document.createElement('label');label.innerHTML='Speed · 速度 <select data-floating-speed aria-label="Playback speed">'+[.25,.5,.75,1,1.25,1.5,1.75,2].map(n=>`<option value="${n}" ${n===1?'selected':''}>${n}×</option>`).join('')+'</select>';bar.append(label);const select=label.querySelector('select');select.onchange=()=>{const audio=window.EdmundListeningTools?.audio();if(audio)audio.playbackRate=Number(select.value);};document.addEventListener('ratechange',e=>{if(e.target===window.EdmundListeningTools?.audio())select.value=String(e.target.playbackRate);},true);}
let queued=false;function mount(){queued=false;attachQuestions();main.querySelectorAll('.listening-transcript').forEach(transcriptFloat);speed();sizeText();}new MutationObserver(()=>{if(!queued){queued=true;requestAnimationFrame(mount);}}).observe(main,{childList:true,subtree:true});mount();
}
