-- Edmund Music Journal: shared, cross-device article storage.
--
-- Run this file once in the Supabase SQL editor. Afterward, set the admin
-- password in a separate SQL-editor query (do not commit the real password):
--
--   select public.music_journal_set_admin_password('replace-with-a-strong-password');

begin;

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.music_journal_admin (
  singleton boolean primary key default true check (singleton),
  password_hash text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.music_journal_sessions (
  token_hash bytea primary key,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '12 hours')
);

create index if not exists music_journal_sessions_expires_idx
on public.music_journal_sessions(expires_at);

create table if not exists public.music_journal_posts (
  id text primary key,
  sort_index bigint generated by default as identity unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published boolean not null default true,
  payload jsonb not null,
  constraint music_journal_posts_payload_object
    check (jsonb_typeof(payload) = 'object'),
  constraint music_journal_posts_payload_size
    check (pg_column_size(payload) <= 6291456)
);

create index if not exists music_journal_posts_published_created_idx
on public.music_journal_posts(published, created_at desc);

create index if not exists music_journal_posts_public_order_idx
on public.music_journal_posts(sort_index desc)
where published;

alter table public.music_journal_admin enable row level security;
alter table public.music_journal_sessions enable row level security;
alter table public.music_journal_posts enable row level security;

drop policy if exists "Music journal posts are public" on public.music_journal_posts;

create or replace view public.music_journal_public_posts
with (security_barrier = true)
as
select
  post.id,
  post.sort_index,
  post.payload - array[
    'date',
    'createdAt',
    'created_at',
    'publishedAt',
    'publicationDate'
  ]::text[] as payload
from public.music_journal_posts post
where post.published = true;

create or replace view public.music_journal_public_post_summaries
with (security_barrier = true)
as
select
  post.id,
  post.sort_index,
  jsonb_strip_nulls(jsonb_build_object(
    'id', post.id,
    'title', post.payload -> 'title',
    'tag', post.payload -> 'tag',
    'image', post.payload -> 'image',
    'body', left(coalesce(post.payload ->> 'body', ''), 600),
    'author', post.payload -> 'author',
    'minutes', post.payload -> 'minutes'
  )) as payload
from public.music_journal_posts post
where post.published = true;

create or replace function public.music_journal_set_admin_password(p_password text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if length(coalesce(p_password, '')) < 10 then
    raise exception 'The admin password must contain at least 10 characters';
  end if;

  insert into public.music_journal_admin (singleton, password_hash, updated_at)
  values (true, extensions.crypt(p_password, extensions.gen_salt('bf', 12)), now())
  on conflict (singleton) do update
  set password_hash = excluded.password_hash,
      updated_at = now();

  delete from public.music_journal_sessions;
end;
$$;

create or replace function public.music_journal_login(p_password text)
returns table (
  token uuid,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_token uuid;
  v_expires_at timestamptz;
begin
  delete from public.music_journal_sessions
  where music_journal_sessions.expires_at <= now();

  if p_password is null
     or length(p_password) > 200
     or not exists (
    select 1
    from public.music_journal_admin admin_account
    where admin_account.singleton = true
      and admin_account.password_hash =
        extensions.crypt(coalesce(p_password, ''), admin_account.password_hash)
  ) then
    return;
  end if;

  v_token := gen_random_uuid();
  v_expires_at := now() + interval '12 hours';

  insert into public.music_journal_sessions (token_hash, expires_at)
  values (extensions.digest(v_token::text, 'sha256'), v_expires_at);

  return query select v_token, v_expires_at;
end;
$$;

create or replace function public.music_journal_session_valid(p_token uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.music_journal_sessions session_row
    where session_row.token_hash = extensions.digest(p_token::text, 'sha256')
      and session_row.expires_at > now()
  );
$$;

create or replace function public.music_journal_publish(
  p_token uuid,
  p_post jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id text;
  v_now timestamptz := clock_timestamp();
  v_published boolean := case
    when jsonb_typeof(p_post -> 'published') = 'boolean'
      then (p_post ->> 'published')::boolean
    else true
  end;
  v_clean_post jsonb;
  v_saved_post jsonb;
begin
  if not public.music_journal_session_valid(p_token) then
    raise exception 'Invalid or expired music-journal session';
  end if;

  if jsonb_typeof(p_post) <> 'object' then
    raise exception 'Post payload must be a JSON object';
  end if;

  v_id := nullif(trim(p_post ->> 'id'), '');
  if v_id is null
     or v_id !~ '^[A-Za-z0-9_-]{1,120}$'
     or nullif(trim(p_post ->> 'title'), '') is null
     or length(p_post ->> 'title') > 240
     or nullif(trim(p_post ->> 'tag'), '') is null
     or length(p_post ->> 'tag') > 80 then
    raise exception 'Post id, title, or tag is invalid';
  end if;

  if pg_column_size(p_post) > 6291456
     or octet_length(p_post::text) > 6291456 then
    raise exception 'Post is larger than the 6 MB limit';
  end if;

  v_clean_post :=
    (p_post - array[
      'date',
      'createdAt',
      'created_at',
      'publishedAt',
      'publicationDate'
    ]::text[])
    || jsonb_build_object(
      'id', v_id,
      'createdAt', (extract(epoch from v_now) * 1000)::bigint,
      'date', to_char(v_now, 'DD Mon YYYY')
    );

  insert into public.music_journal_posts as existing (
    id,
    created_at,
    updated_at,
    published,
    payload
  )
  values (
    v_id,
    v_now,
    v_now,
    v_published,
    v_clean_post
  )
  on conflict (id) do update
  set updated_at = v_now,
      -- Editing a private archive must not silently republish it. New rows are
      -- public by default, while existing rows keep their current visibility.
      published = existing.published,
      payload =
        (
          excluded.payload - array[
            'date',
            'createdAt',
            'created_at',
            'publishedAt',
            'publicationDate'
          ]::text[]
        )
        || jsonb_build_object(
          'id', existing.id,
          'createdAt',
            (extract(epoch from existing.created_at) * 1000)::bigint,
          'date', to_char(existing.created_at, 'DD Mon YYYY')
        )
  returning existing.payload
  into v_saved_post;

  return v_saved_post;
end;
$$;

-- The admin list used to return only (id, sort_index, payload). PostgreSQL
-- cannot change a RETURNS TABLE row shape with CREATE OR REPLACE, so drop the
-- exact signature first. This remains atomic because the migration is wrapped
-- in the transaction above, and it is safe to repeat on later runs.
drop function if exists public.music_journal_list_admin(uuid);

create function public.music_journal_list_admin(p_token uuid)
returns table (
  id text,
  sort_index bigint,
  published boolean,
  payload jsonb
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.music_journal_session_valid(p_token) then
    raise exception 'Invalid or expired music-journal session';
  end if;

  return query
  select post.id, post.sort_index, post.published, post.payload
  from public.music_journal_posts post
  order by post.sort_index desc;
end;
$$;

create or replace function public.music_journal_get_admin_post(
  p_token uuid,
  p_id text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_payload jsonb;
begin
  if not public.music_journal_session_valid(p_token) then
    raise exception 'Invalid or expired music-journal session';
  end if;

  select post.payload
  into v_payload
  from public.music_journal_posts post
  where post.id = p_id;

  return v_payload;
end;
$$;

create or replace function public.music_journal_set_visibility(
  p_token uuid,
  p_id text,
  p_published boolean
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id text := nullif(trim(p_id), '');
begin
  if not public.music_journal_session_valid(p_token) then
    raise exception 'Invalid or expired music-journal session';
  end if;

  if v_id is null
     or v_id !~ '^[A-Za-z0-9_-]{1,120}$'
     or p_published is null then
    raise exception 'Post id and visibility are required';
  end if;

  update public.music_journal_posts post
  set published = p_published,
      updated_at = clock_timestamp()
  where post.id = v_id
    and post.published is distinct from p_published;

  if found then
    return true;
  end if;

  -- Treat an idempotent repeat as success while still returning false for an
  -- unknown post id. This makes retries safe and avoids needless row writes.
  return exists (
    select 1
    from public.music_journal_posts post
    where post.id = v_id
      and post.published = p_published
  );
end;
$$;

create or replace function public.music_journal_delete(
  p_token uuid,
  p_id text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.music_journal_session_valid(p_token) then
    raise exception 'Invalid or expired music-journal session';
  end if;

  delete from public.music_journal_posts
  where music_journal_posts.id = p_id;

  return found;
end;
$$;

create or replace function public.music_journal_logout(p_token uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  delete from public.music_journal_sessions
  where music_journal_sessions.token_hash = extensions.digest(p_token::text, 'sha256');
$$;

revoke all on table public.music_journal_admin from public, anon, authenticated, service_role;
revoke all on table public.music_journal_sessions from public, anon, authenticated, service_role;
revoke all on table public.music_journal_posts from public, anon, authenticated, service_role;
revoke all on table public.music_journal_public_posts from public, anon, authenticated, service_role;
revoke all on table public.music_journal_public_post_summaries from public, anon, authenticated, service_role;
grant select on table public.music_journal_public_posts to anon, authenticated;
grant select on table public.music_journal_public_post_summaries to anon, authenticated;

revoke all on function public.music_journal_set_admin_password(text) from public, anon, authenticated, service_role;
revoke all on function public.music_journal_login(text) from public, anon, authenticated, service_role;
revoke all on function public.music_journal_session_valid(uuid) from public, anon, authenticated, service_role;
revoke all on function public.music_journal_publish(uuid, jsonb) from public, anon, authenticated, service_role;
revoke all on function public.music_journal_list_admin(uuid) from public, anon, authenticated, service_role;
revoke all on function public.music_journal_get_admin_post(uuid, text) from public, anon, authenticated, service_role;
revoke all on function public.music_journal_set_visibility(uuid, text, boolean) from public, anon, authenticated, service_role;
revoke all on function public.music_journal_delete(uuid, text) from public, anon, authenticated, service_role;
revoke all on function public.music_journal_logout(uuid) from public, anon, authenticated, service_role;

grant execute on function public.music_journal_login(text) to anon, authenticated;
grant execute on function public.music_journal_publish(uuid, jsonb) to anon, authenticated;
grant execute on function public.music_journal_list_admin(uuid) to anon, authenticated;
grant execute on function public.music_journal_get_admin_post(uuid, text) to anon, authenticated;
grant execute on function public.music_journal_set_visibility(uuid, text, boolean) to anon, authenticated;
grant execute on function public.music_journal_delete(uuid, text) to anon, authenticated;
grant execute on function public.music_journal_logout(uuid) to anon, authenticated;

notify pgrst, 'reload schema';

commit;
