-- Enable the 114 teacher-reviewed Common Expression lessons imported on 11 Aug 2026.
-- This migration changes catalogue rows only; existing progress keys remain unchanged.

begin;

insert into public.common_expression_catalogue_lessons (
  system_key,
  lesson_id,
  question_count,
  content_version,
  is_enabled
)
values
  ('speaking', 'common-expression-01', 20, 1, true),
  ('speaking', 'common-expression-02', 20, 1, true),
  ('speaking', 'common-expression-03', 30, 1, true),
  ('speaking', 'common-expression-04', 30, 1, true),
  ('speaking', 'common-expression-05', 30, 1, true),
  ('speaking', 'common-expression-06', 30, 1, true),
  ('speaking', 'common-expression-07', 30, 1, true),
  ('speaking', 'common-expression-08', 30, 1, true),
  ('speaking', 'common-expression-09', 30, 1, true),
  ('speaking', 'common-expression-10', 30, 1, true),
  ('speaking', 'common-expression-11', 30, 1, true),
  ('speaking', 'common-expression-12', 30, 1, true),
  ('speaking', 'common-expression-13', 30, 1, true),
  ('speaking', 'common-expression-14', 30, 1, true),
  ('speaking', 'common-expression-15', 30, 1, true),
  ('speaking', 'common-expression-16', 30, 1, true),
  ('speaking', 'common-expression-17', 30, 1, true),
  ('speaking', 'common-expression-18', 30, 1, true),
  ('speaking', 'common-expression-19', 30, 1, true),
  ('speaking', 'common-expression-20', 30, 1, true),
  ('speaking', 'common-expression-21', 30, 1, true),
  ('speaking', 'common-expression-22', 30, 1, true),
  ('speaking', 'common-expression-23', 30, 1, true),
  ('speaking', 'common-expression-24', 30, 1, true),
  ('speaking', 'common-expression-25', 30, 1, true),
  ('speaking', 'common-expression-26', 30, 1, true),
  ('speaking', 'common-expression-27', 30, 1, true),
  ('speaking', 'common-expression-28', 30, 1, true),
  ('speaking', 'common-expression-29', 30, 1, true),
  ('speaking', 'common-expression-30', 30, 1, true),
  ('speaking', 'common-expression-31', 30, 1, true),
  ('written', 'common-expression-01', 30, 1, true),
  ('written', 'common-expression-02', 30, 1, true),
  ('written', 'common-expression-03', 30, 1, true),
  ('written', 'common-expression-04', 30, 1, true),
  ('written', 'common-expression-05', 30, 1, true),
  ('written', 'common-expression-06', 30, 1, true),
  ('written', 'common-expression-07', 30, 1, true),
  ('written', 'common-expression-08', 30, 1, true),
  ('written', 'common-expression-09', 30, 1, true),
  ('written', 'common-expression-10', 30, 1, true),
  ('written', 'common-expression-11', 30, 1, true),
  ('written', 'common-expression-12', 30, 1, true),
  ('written', 'common-expression-13', 30, 1, true),
  ('written', 'common-expression-14', 30, 1, true),
  ('written', 'common-expression-15', 30, 1, true),
  ('written', 'common-expression-16', 30, 1, true),
  ('written', 'common-expression-17', 30, 1, true),
  ('written', 'common-expression-18', 30, 1, true),
  ('written', 'common-expression-19', 30, 1, true),
  ('written', 'common-expression-20', 30, 1, true),
  ('written', 'common-expression-21', 30, 1, true),
  ('written', 'common-expression-22', 30, 1, true),
  ('written', 'common-expression-23', 30, 1, true),
  ('written', 'common-expression-24', 30, 1, true),
  ('written', 'common-expression-25', 30, 1, true),
  ('written', 'common-expression-26', 30, 1, true),
  ('written', 'common-expression-27', 30, 1, true),
  ('written', 'common-expression-28', 30, 1, true),
  ('written', 'common-expression-29', 30, 1, true),
  ('written', 'common-expression-30', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-01', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-02', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-03', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-04', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-05', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-06', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-07', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-08', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-09', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-10', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-11', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-12', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-13', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-14', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-15', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-16', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-17', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-18', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-19', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-20', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-21', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-22', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-23', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-24', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-25', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-26', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-27', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-28', 30, 1, true),
  ('rhetorical-speaking', 'common-expression-29', 30, 1, true),
  ('rhetorical-writing', 'common-expression-01', 30, 1, true),
  ('rhetorical-writing', 'common-expression-02', 30, 1, true),
  ('rhetorical-writing', 'common-expression-03', 30, 1, true),
  ('rhetorical-writing', 'common-expression-04', 30, 1, true),
  ('rhetorical-writing', 'common-expression-05', 30, 1, true),
  ('rhetorical-writing', 'common-expression-06', 30, 1, true),
  ('rhetorical-writing', 'common-expression-07', 30, 1, true),
  ('rhetorical-writing', 'common-expression-08', 30, 1, true),
  ('rhetorical-writing', 'common-expression-09', 30, 1, true),
  ('rhetorical-writing', 'common-expression-10', 30, 1, true),
  ('rhetorical-writing', 'common-expression-11', 30, 1, true),
  ('rhetorical-writing', 'common-expression-12', 30, 1, true),
  ('rhetorical-writing', 'common-expression-13', 30, 1, true),
  ('rhetorical-writing', 'common-expression-14', 30, 1, true),
  ('rhetorical-writing', 'common-expression-15', 30, 1, true),
  ('rhetorical-writing', 'common-expression-16', 30, 1, true),
  ('rhetorical-writing', 'common-expression-17', 30, 1, true),
  ('rhetorical-writing', 'common-expression-18', 30, 1, true),
  ('rhetorical-writing', 'common-expression-19', 30, 1, true),
  ('rhetorical-writing', 'common-expression-20', 30, 1, true),
  ('rhetorical-writing', 'common-expression-21', 30, 1, true),
  ('rhetorical-writing', 'common-expression-22', 30, 1, true),
  ('rhetorical-writing', 'common-expression-23', 30, 1, true),
  ('rhetorical-writing', 'common-expression-24', 30, 1, true),
  ('rhetorical-writing', 'common-expression-25', 30, 1, true),
  ('rhetorical-writing', 'common-expression-26', 30, 1, true),
  ('rhetorical-writing', 'common-expression-27', 30, 1, true),
  ('rhetorical-writing', 'common-expression-28', 30, 1, true),
  ('rhetorical-writing', 'common-expression-29', 30, 1, true),
  ('professional-message', 'common-expression-01', 30, 1, true),
  ('professional-message', 'common-expression-02', 30, 1, true),
  ('professional-message', 'common-expression-03', 30, 1, true),
  ('professional-message', 'common-expression-04', 30, 1, true),
  ('professional-message', 'common-expression-05', 30, 1, true),
  ('professional-message', 'common-expression-06', 30, 1, true),
  ('professional-message', 'common-expression-07', 30, 1, true),
  ('professional-message', 'common-expression-08', 30, 1, true),
  ('professional-message', 'common-expression-09', 30, 1, true),
  ('professional-message', 'common-expression-10', 30, 1, true),
  ('professional-message', 'common-expression-11', 30, 1, true),
  ('professional-message', 'common-expression-12', 30, 1, true),
  ('professional-message', 'common-expression-13', 30, 1, true),
  ('professional-message', 'common-expression-14', 30, 1, true),
  ('professional-message', 'common-expression-15', 30, 1, true),
  ('professional-message', 'common-expression-16', 30, 1, true),
  ('professional-message', 'common-expression-17', 30, 1, true),
  ('professional-message', 'common-expression-18', 30, 1, true),
  ('professional-message', 'common-expression-19', 30, 1, true),
  ('professional-message', 'common-expression-20', 30, 1, true),
  ('professional-message', 'common-expression-21', 30, 1, true),
  ('professional-message', 'common-expression-22', 30, 1, true),
  ('professional-message', 'common-expression-23', 30, 1, true),
  ('professional-message', 'common-expression-24', 30, 1, true),
  ('professional-message', 'common-expression-25', 30, 1, true),
  ('professional-message', 'common-expression-26', 30, 1, true),
  ('professional-message', 'common-expression-27', 30, 1, true),
  ('business-speaking', 'common-expression-01', 30, 1, true),
  ('business-speaking', 'common-expression-02', 30, 1, true),
  ('business-speaking', 'common-expression-03', 30, 1, true),
  ('business-speaking', 'common-expression-04', 30, 1, true),
  ('business-speaking', 'common-expression-05', 30, 1, true),
  ('business-speaking', 'common-expression-06', 30, 1, true),
  ('business-speaking', 'common-expression-07', 30, 1, true),
  ('business-speaking', 'common-expression-08', 30, 1, true),
  ('business-speaking', 'common-expression-09', 30, 1, true),
  ('business-speaking', 'common-expression-10', 30, 1, true),
  ('business-speaking', 'common-expression-11', 30, 1, true),
  ('business-speaking', 'common-expression-12', 30, 1, true),
  ('business-speaking', 'common-expression-13', 30, 1, true),
  ('business-speaking', 'common-expression-14', 30, 1, true),
  ('business-speaking', 'common-expression-15', 30, 1, true),
  ('business-speaking', 'common-expression-16', 30, 1, true),
  ('business-speaking', 'common-expression-17', 30, 1, true),
  ('business-speaking', 'common-expression-18', 30, 1, true),
  ('business-speaking', 'common-expression-19', 30, 1, true),
  ('business-speaking', 'common-expression-20', 30, 1, true),
  ('business-speaking', 'common-expression-21', 30, 1, true),
  ('business-speaking', 'common-expression-22', 30, 1, true),
  ('business-speaking', 'common-expression-23', 30, 1, true),
  ('business-speaking', 'common-expression-24', 30, 1, true),
  ('business-speaking', 'common-expression-25', 30, 1, true),
  ('business-speaking', 'common-expression-26', 30, 1, true)
on conflict (system_key, lesson_id) do update
set question_count = excluded.question_count,
    content_version = excluded.content_version,
    is_enabled = true,
    updated_at = now();

commit;
