import {rankBadges} from './momentum-core.mjs?v=20260916-momentum1';
import {badgeHtml,totalHtml,updatedHtml,celebrateBadge} from './team-momentum.mjs?v=20260916-momentum1';
import './progress-previews.mjs?v=20260916-community1';
import {API,PUBLIC_KEY,session,rpc,subscribe,saveState,getCached} from './learning-state.mjs?v=20260916-community1';
import {escapeHtml as esc} from './library-core.mjs?v=20260916-community1';
import {ASSESSMENT_QUESTIONS,teamSeries,memberBreakdown,cardRows} from './community-core.mjs?v=20260916-community1';
import {exportCardsPDF} from './card-export.mjs?v=20260916-community1';
const ownerIs=owner=>session()?.token===owner?.token&&session()?.user?.id===owner?.user?.id;
const dateLabel=d=>new Date(d).toLocaleString('zh-HK',{timeZone:'Asia/Hong_Kong'});
const localRead=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
export function mountAssessment(host){
 const id=crypto.randomUUID();let sent=false;
 host.innerHTML=`<details class="anonymous-assessment"><summary><span>匿名自我評估與課程回饋<small>Anonymous self-assessment · 無需登入</small></span><span class="expand-cue">＋ 展開</span></summary><form><p>請按目前的感受選擇 1–7 分。系統不記錄帳戶或使用者名稱；請勿在留言填寫姓名。</p><p class="assessment-scale">1 非常不同意 · 4 中立 · 7 非常同意</p>${ASSESSMENT_QUESTIONS.map(([zh,en],i)=>`<fieldset><legend>${i+1}. ${zh}<small>${en}</small></legend><div class="rating-seven">${[1,2,3,4,5,6,7].map(n=>`<label><input type="radio" name="q${i}" value="${n}" required><span>${n}</span></label>`).join('')}</div></fieldset>`).join('')}<label>感想、意見或建議（選填）<textarea name="comment" rows="5" maxlength="4000" placeholder="寫下對課程的想法…"></textarea></label><label class="assessment-trap" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><button class="pro-primary" type="submit">提交匿名回饋</button><p role="status" data-assessment-status></p></form></details>`;
 const details=host.querySelector('details');details.addEventListener('toggle',()=>host.querySelector('.expand-cue').textContent=details.open?'− 收起':'＋ 展開');
 host.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();if(sent)return;const form=e.target,button=form.querySelector('button'),status=form.querySelector('[data-assessment-status]');button.disabled=true;const data=new FormData(form);try{const response=await fetch(API+'/rest/v1/rpc/special_flash_assessment_submit',{method:'POST',credentials:'omit',headers:{apikey:PUBLIC_KEY,'Content-Type':'application/json'},body:JSON.stringify({p_id:id,p_ratings:ASSESSMENT_QUESTIONS.map((_,i)=>Number(data.get('q'+i))),p_comment:data.get('comment')||'',p_trap:data.get('website')||''}),signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok)throw Error(result.message||'暫時未能提交，請重試。');sent=true;status.textContent='謝謝！你的匿名回饋已提交。';button.textContent='✓ 已提交';form.querySelectorAll('input,textarea').forEach(n=>n.disabled=true);}catch(error){status.textContent=error.message;button.disabled=false;}});
 return()=>host.replaceChildren();
}
const breakdownHtml=m=>{const b=memberBreakdown(m);return `<h3>${esc(m.username||'全組總計')}</h3><strong class="team-detail-total">${b.total} 題</strong><dl><div><dt>字卡</dt><dd>${b.card}</dd></div><div><dt>填充</dt><dd>${b.blank}</dd></div><div><dt>一詞多義</dt><dd>${b.poly}</dd></div></dl>`;};
export function mountTeam(host,{token,courseId}){
 if(document.body.dataset.professionalLibraryPage==='true')return()=>{};
 const owner=session();let active=true,busy=false,course=null,signature='',timer=null,reactionBusy=false,remote={heart:0,thumb:0,flex:0},retry=1000,lastUpdated=null;
 const queueKey=`professional-encouragement:${owner.user.id}:${courseId}`;let queue=localRead(queueKey,[]);
 host.innerHTML=`<div class="team-effort-heading"><div><span>TEAM EFFORT</span><h2>全組努力<small>Team Effort</small></h2><p>答對字卡、答對填空及完成整個詞語，各計一題。點擊同學或圖點查看詳情。</p></div><div class="team-refresh-area"><button type="button" data-team-refresh>↻ 更新</button><p class="team-updated" data-team-updated>正在取得最新資料…</p></div></div><div class="team-interaction-bar"><p data-team-status role="status"></p><div class="team-reactions" aria-label="給同學鼓勵">${[['heart','❤️','愛心'],['thumb','👍','讚好'],['flex','💪','加油']].map(([key,icon,label])=>`<button type="button" data-reaction="${key}" aria-label="${label}"><span>${icon}</span><strong data-reaction-count="${key}">0</strong></button>`).join('')}</div></div><div data-team-visual></div><div class="team-hover" role="tooltip" hidden></div>`;
 const status=text=>{if(active)host.querySelector('[data-team-status]').textContent=text;};
 const persist=()=>localStorage.setItem(queueKey,JSON.stringify(queue));
 function counts(){if(!active)return;for(const key of ['heart','thumb','flex'])host.querySelector(`[data-reaction-count="${key}"]`).textContent=Number(remote[key]||0)+queue.reduce((n,b)=>n+b[key],0);}
 async function refreshReactions(){if(!active||reactionBusy||queue.length||!ownerIs(owner))return;try{const value=await rpc('encouragement',{p_course:courseId},owner);if(active&&ownerIs(owner)&&!reactionBusy&&!queue.length){remote=value;counts();}}catch{}}
 async function flushReactions(){if(!active||reactionBusy||!queue.length||!ownerIs(owner))return;reactionBusy=true;const batch=queue[0];try{const value=await rpc('encouragement',{p_course:courseId,p_request:batch.id,p_heart:batch.heart,p_thumb:batch.thumb,p_flex:batch.flex},owner);if(!ownerIs(owner))return;queue=queue.filter(b=>b.id!==batch.id);persist();remote=value;retry=1000;counts();status('');}catch(error){status('鼓勵已保留，正在等候同步。');retry=Math.min(retry*2,30000);}finally{reactionBusy=false;if(active&&queue.length)timer=setTimeout(flushReactions,retry);}}
 function encourage(key){if(!ownerIs(owner))return;let batch=queue.at(-1);if(!batch||(reactionBusy&&batch===queue[0])||batch[key]>=1000){batch={id:crypto.randomUUID(),heart:0,thumb:0,flex:0};queue.push(batch);}batch[key]++;persist();counts();clearTimeout(timer);timer=setTimeout(flushReactions,750);}
 function detail(id,date){if(!course)return '';if(id==='total'){const members=course.members||[];const atDate=members.map(m=>({...m,...(date?sumUntil(m.account_id,date):{})}));const total=atDate.reduce((a,m)=>{for(const k of ['cards','card_questions','blank_questions','polysemy_words'])a[k]=(a[k]||0)+(Number(m[k])||0);return a;},{username:'全組總計'});return breakdownHtml(total)+`<table><thead><tr><th>同學</th><th>總題數</th><th>字卡</th><th>填充</th><th>詞語</th></tr></thead><tbody>${atDate.map(m=>`<tr><td>${esc(m.username)}</td><td>${m.cards||0}</td><td>${m.card_questions||0}</td><td>${m.blank_questions||0}</td><td>${m.polysemy_words||0}</td></tr>`).join('')}</tbody></table>`;}const m=course.members.find(m=>m.account_id===id);return m?breakdownHtml({...m,...(date?sumUntil(id,date):{})}):'';}
 function sumUntil(id,date){const last=course.daily?.map(d=>d.date).sort().at(-1);if(date>=last)return course.members.find(m=>m.account_id===id)||{};return (course.daily||[]).filter(d=>d.account_id===id&&d.date<=date).reduce((a,d)=>{for(const k of ['cards','card_questions','blank_questions','polysemy_words'])a[k]+=Number(d[k])||0;return a;},{cards:0,card_questions:0,blank_questions:0,polysemy_words:0});}
 function render(){const badges=rankBadges(course.members||[]),plot=teamSeries(course),w=920,h=390,left=62,top=40,bottom=330,right=875,x=i=>plot.dates.length===1?(left+right)/2:left+i*(right-left)/(plot.dates.length-1),y=value=>bottom-(Number(value)||0)/plot.max*(bottom-top),dateText=d=>new Date(d+'T12:00:00+08:00').toLocaleDateString('en-HK',{day:'numeric',month:'short'});
 const line=points=>points.map((p,i)=>(i?'L':'M')+x(i)+','+y(p.cards)).join(' '),dot=(m,p,i,total=false)=>`<g class="team-hit" data-team-member="${esc(total?'total':m.account_id)}" data-team-date="${p.date}" tabindex="0" role="button" aria-label="${esc(total?'全組':m.username)}：${p.cards} 題"><circle cx="${x(i)}" cy="${y(p.cards)}" r="14" fill="transparent"/><circle class="team-visible-point" cx="${x(i)}" cy="${y(p.cards)}" r="${total?8:5}" fill="${total?'#163f32':m.color}" stroke="${total?'#edbf4b':'#fff'}" stroke-width="${total?3:1.5}"/></g>`;
 host.querySelector('[data-team-visual]').innerHTML=`<div class="team-effort-summary"><button type="button" class="team-sum-button" data-team-member="total">${totalHtml(course)}</button><div class="team-effort-ranking">${plot.series.map(m=>`<div class="team-member-row">${badgeHtml(m,badges.get(m.account_id))}<button type="button" data-team-member="${esc(m.account_id)}"><i style="--member-color:${m.color}"></i><span>${esc(m.username)}</span><strong>${m.cards||0}</strong></button></div>`).join('')}</div></div><svg class="team-effort-chart" viewBox="0 0 ${w} ${h}" aria-label="全組累積完成題目互動圖"><rect class="team-chart-surface" width="${w}" height="${h}" rx="18"/>${[0,plot.max/2,plot.max].map(n=>`<line class="team-chart-grid" x1="${left}" x2="${right}" y1="${y(n)}" y2="${y(n)}"/><text class="team-chart-label" x="${left-12}" y="${y(n)+5}" text-anchor="end">${n}</text>`).join('')}<path class="team-chart-axis" d="M${left},${top}V${bottom}H${right}" fill="none"/>${plot.series.map(m=>`<path d="${line(m.points)}" fill="none" stroke="${m.color}" stroke-width="2.5"/>${m.points.map((p,i)=>p.cards>0?dot(m,p,i):'').join('')}`).join('')}<path d="${line(plot.team)}" fill="none" stroke="#163f32" stroke-width="4"/>${plot.team.map((p,i)=>dot({},p,i,true)).join('')}<text class="team-chart-count" x="${x(plot.team.length-1)}" y="${y(course.total_cards)+28}" text-anchor="middle">${course.total_cards} 題 · 全組</text>${plot.dates.map((d,i)=>(i===0||i===plot.dates.length-1||i===Math.floor(plot.dates.length/2))?`<text class="team-chart-label" x="${x(i)}" y="362" text-anchor="middle">${dateText(d)}</text>`:'').join('')}<text class="team-chart-title" x="${left}" y="23">累積完成題目 · Cumulative questions</text></svg>`;
 }
 async function refresh(){if(!active||busy||!ownerIs(owner))return;busy=true;try{const data=await rpc('team_effort',{},owner);if(!active||!ownerIs(owner))return;course=data.courses.find(c=>c.course_id===courseId);if(course&&JSON.stringify(course)!==signature){signature=JSON.stringify(course);render();}if(course){const serverTime=Date.parse(data.generated_at);lastUpdated=Number.isFinite(serverTime)?serverTime:Date.now();updateAge();}status('');void refreshReactions();}catch{status('暫時未能更新。可按「更新」重試。');}finally{busy=false;}}
 function updateAge(){if(active)host.querySelector('[data-team-updated]').innerHTML=updatedHtml(lastUpdated);}
 const ageTimer=setInterval(updateAge,15000);
 const tooltip=host.querySelector('.team-hover');
 host.addEventListener('mouseover',e=>{const target=e.target.closest('[data-team-member]');if(!target||!course)return;tooltip.innerHTML=detail(target.dataset.teamMember,target.dataset.teamDate);tooltip.hidden=false;const rect=target.getBoundingClientRect();tooltip.style.left=Math.max(8,Math.min(innerWidth-350,rect.left))+'px';tooltip.style.top=Math.max(8,Math.min(innerHeight-310,rect.bottom+8))+'px';});
 host.addEventListener('mouseout',e=>{if(e.target.closest('[data-team-member]'))tooltip.hidden=true;});
 host.addEventListener('click',e=>{const badge=e.target.closest('[data-team-badge]');if(badge){celebrateBadge(badge);return;}const reaction=e.target.closest('[data-reaction]');if(reaction){encourage(reaction.dataset.reaction);return;}if(e.target.closest('[data-team-refresh]')){void refresh();return;}const target=e.target.closest('[data-team-member]');if(target&&course){tooltip.hidden=true;const modal=document.createElement('dialog');modal.className='team-detail-modal';modal.innerHTML=`<button type="button" class="dialog-close" aria-label="關閉">×</button>${detail(target.dataset.teamMember,target.dataset.teamDate)}`;document.body.append(modal);modal.querySelector('button').onclick=()=>modal.close();modal.onclose=()=>modal.remove();modal.showModal();}});
 host.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.matches('g[data-team-member]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
 const unsubscribe=subscribe(refresh);document.addEventListener('professional-encouragement-changed',refreshReactions);void refresh();counts();if(queue.length)timer=setTimeout(flushReactions,750);
 return()=>{active=false;clearTimeout(timer);clearInterval(ageTimer);unsubscribe();tooltip.remove();document.removeEventListener('professional-encouragement-changed',refreshReactions);};
}
export function mountHighAttempts(host,{courseId}){if(document.body.dataset.professionalLibraryPage==='true')return()=>{};let active=true;const owner=session();host.innerHTML='<h3>高嘗試卡片</h3><p>正在載入…</p>';rpc('card_records',{p_course:courseId},owner).then(rows=>{if(!active||!ownerIs(owner))return;const high=cardRows(rows,'high'),groups=[...new Set(high.map(r=>Number(r.attempts)))].sort((a,b)=>a-b);host.innerHTML=`<div class="records-heading"><h3>高嘗試卡片 <small>共 ${high.length} 張</small></h3><a href="./library.html?view=records&status=all&course=${courseId}">查看所有卡片紀錄 →</a><button type="button" data-export-high ${high.length?'':'disabled'}>匯出高嘗試卡片 PDF</button></div><p class="records-history-note">歷史資料以已有的單卡紀錄為準；新練習會逐次累計。</p>${groups.map(n=>`<details><summary>${n} 次嘗試 · ${high.filter(r=>Number(r.attempts)===n).length} 張 <span>展開</span></summary>${high.filter(r=>Number(r.attempts)===n).map(r=>`<a class="attempt-record" href="./?deck=${r.deck_id}&card=${r.card_id}"><strong>${esc(r.front)}</strong><span>${esc(r.back)}</span><small>${esc(r.deck_title)} ↗</small></a>`).join('')}</details>`).join('')||'<p>累積練習後，嘗試兩次或以上的卡片會在這裡出現。</p>'}`;host.querySelector('[data-export-high]').onclick=()=>exportCardsPDF({title:'高嘗試卡片',cards:high});}).catch(()=>{if(active)host.innerHTML='<h3>高嘗試卡片</h3><p>紀錄暫時未能載入，請重新整理。</p>';});return()=>{active=false;};}
export async function feedbackPage(page){
 if(session()?.user?.role!=='admin'){page.insertAdjacentHTML('beforeend','<p>只有管理員可以查看匿名回饋。</p>');return;}const n=Math.max(1,Number(new URLSearchParams(location.search).get('page'))||1),data=await rpc('assessment_results',{p_page:n});
 page.insertAdjacentHTML('beforeend',`<section class="anonymous-results"><h2>匿名自我評估 · ${data.total} 份回覆</h2><p>1 非常不同意 · 4 中立 · 7 非常同意。以下沒有帳戶或使用者名稱。</p>${data.rows.map((r,i)=>`<article><h3>回覆 ${(n-1)*20+i+1}</h3><time>${dateLabel(r.submitted_at)}</time><dl>${ASSESSMENT_QUESTIONS.map(([zh],i)=>`<div><dt>${esc(zh)}</dt><dd>${r.ratings[i]} / 7</dd></div>`).join('')}</dl><p class="feedback-comment">${esc(r.comment||'（沒有留言）')}</p></article>`).join('')||'<p>暫時沒有回覆。</p>'}<nav class="pagination">${n>1?`<a href="./library.html?view=feedback&page=${n-1}">← 上一頁</a>`:''}<span>第 ${n} / ${Math.max(1,Math.ceil(data.total/20))} 頁</span>${n*20<data.total?`<a href="./library.html?view=feedback&page=${n+1}">下一頁 →</a>`:''}</nav></section>`);
}
export async function recordsPage(page){
 const p=new URLSearchParams(location.search),status=['green','red','high'].includes(p.get('status'))?p.get('status'):'all',course=p.get('course'),data=await rpc('card_records',course?{p_course:course}:{}),rows=cardRows(data,status),names={all:'目前字卡進度',green:'目前已掌握',red:'目前待重溫',high:'高嘗試卡片'},decks=[...new Set(rows.map(r=>r.deck_id))];
 page.insertAdjacentHTML('beforeend',`<section class="card-records"><h2>${names[status]} · ${rows.length} 張</h2><nav>${Object.entries(names).map(([id,name])=>`<a href="./library.html?view=records&status=${id}${course?'&course='+course:''}" ${id===status?'aria-current="page"':''}>${name}</a>`).join('')}</nav><button type="button" data-export-records ${rows.length?'':'disabled'}>匯出卡片列表 PDF</button>${decks.map(id=>`<section><h3>${esc(rows.find(r=>r.deck_id===id).deck_title)}</h3><a class="practice-records" href="./?deck=${id}&cards=${rows.filter(r=>r.deck_id===id).map(r=>r.card_id).join(',')}&mode=${status==='red'?'red':status==='green'?'green':'attempted'}">練習這組卡片 →</a>${rows.filter(r=>r.deck_id===id).map(r=>`<article><div><strong>${esc(r.front)}</strong><p>${esc(r.back)}</p><small>${Number(r.attempts)||1} 次有紀錄的嘗試${r.last_at?' · '+dateLabel(r.last_at):''}</small></div><a href="./?deck=${r.deck_id}&card=${r.card_id}">練習 →</a></article>`).join('')}</section>`).join('')||'<p>暫時沒有這類卡片。</p>'}</section>`);page.querySelector('[data-export-records]').onclick=()=>exportCardsPDF({title:names[status],cards:rows});
}
// Record both outcomes without changing the established progress-save or question-scoring APIs.
let markBusy=false,markTimer=null,blockedMarkToken=null;
const markQueueKey=id=>'professional-card-mark-outbox:'+id;
async function flushMarks(){const owner=session();if(markBusy||!owner?.token||blockedMarkToken===owner.token)return;const key=markQueueKey(owner.user.id),items=localRead(key,[]);if(!items.length)return;markBusy=true;const batch=items.slice(0,50);try{await rpc('record_marks',{p_events:batch},owner);const keys=new Set(batch.map(e=>e.deck+':'+e.card+':'+e.attempt));localStorage.setItem(key,JSON.stringify(localRead(key,[]).filter(e=>!keys.has(e.deck+':'+e.card+':'+e.attempt))));document.dispatchEvent(new Event('professional-card-records-changed'));}catch(error){if(error.code==='42501')blockedMarkToken=owner.token;}finally{markBusy=false;}}
if(typeof document!=='undefined'){
 document.addEventListener('professional-card-marked',e=>{const d=e.detail,owner=session();if(!d?.deck||!d.card||!d.attempt||!['red','green'].includes(d.mark)||d.account!==owner?.user?.id)return;const key=markQueueKey(owner.user.id),items=localRead(key,[]);if(!items.some(x=>x.deck===d.deck&&x.card===d.card&&x.attempt===d.attempt)){items.push({deck:d.deck,card:d.card,attempt:d.attempt,mark:d.mark,at:Date.now()});localStorage.setItem(key,JSON.stringify(items));}clearTimeout(markTimer);markTimer=setTimeout(flushMarks,500);});setInterval(flushMarks,10000);
 function headerLinks(){for(const header of document.querySelectorAll('.app-header,.login-shell>header')){if(header.querySelector('[data-community-nav]'))continue;const nav=document.createElement('nav');nav.dataset.communityNav='';nav.className='community-header-links';nav.setAttribute('aria-label','快速導航');nav.innerHTML=`${session()?.token?'<a class="bookmark-nav" href="./library.html?view=bookmarks">☆ 我的書籤</a>':''}<a class="main-site-nav" href="/index.html">⌂ EdmundEducation 主頁</a>${session()?.user?.role==='admin'?'<a href="./library.html?view=feedback">匿名回饋</a>':''}`;(header.querySelector('.header-actions')||header).append(nav);}}
 new MutationObserver(headerLinks).observe(document.getElementById('root'),{subtree:true,childList:true});headerLinks();void flushMarks();
}
