import {rpc,session} from './learning-state.mjs?v=20260916-ui-polish1';
import {escapeHtml as esc} from './library-core.mjs?v=20260916-ui-polish1';
import {learningPoints} from './momentum-core.mjs?v=20260916-ui-polish1';
const encode=encodeURIComponent;
export function mountLearningHistory(host,{courseId}){
 const owner=session();let active=true,points=[],selected=null,request=0,signature='',currentPage=1,rows=[];
 host.innerHTML='<div data-personal-chart></div><div class="learning-point-tooltip" role="tooltip" hidden></div><p class="learning-chart-help">● 所有練習 · All exercises <span>指向圖點查看數字；點擊查看當日紀錄 · 香港時間</span></p><section class="learning-date-records" hidden aria-label="所選日期的學習紀錄"></section>';
 const chart=host.querySelector('[data-personal-chart]'),tip=host.querySelector('[role=tooltip]'),details=host.querySelector('.learning-date-records');
 const owns=()=>active&&session()?.token===owner?.token;
 function draw(){const w=900,h=330,left=64,right=850,top=30,bottom=284,max=Math.max(4,...points.map(p=>p.cumulative)),x=i=>points.length===1?(left+right)/2:left+i*(right-left)/(points.length-1),y=n=>bottom-n/max*(bottom-top),step=Math.max(1,Math.ceil(points.length/7));
  chart.innerHTML=`<svg class="axis-chart personal-history-chart" viewBox="0 0 ${w} ${h}" role="group" aria-label="累積完成題目；點擊圖點查看紀錄">${[0,.25,.5,.75,1].map(f=>`<line class="chart-gridline" x1="${left}" x2="${right}" y1="${y(max*f)}" y2="${y(max*f)}"/><text class="chart-y-label" x="${left-12}" y="${y(max*f)+5}">${Math.round(max*f)}</text>`).join('')}<path class="chart-axis" d="M${left},${top}V${bottom}H${right}" fill="none"/><path class="personal-history-line" d="${points.map((p,i)=>(i?'L':'M')+x(i)+','+y(p.cumulative)).join(' ')}" fill="none" stroke="#358b4d" stroke-width="3.5" stroke-linejoin="round"/>${points.map((p,i)=>`<g class="learning-point${selected?.from===p.from?' selected':''}" data-learning-point="${i}" tabindex="0" role="button" aria-label="${esc(p.title)}：本期 ${p.questions} 題，累積 ${p.cumulative} 題；查看紀錄"><circle class="learning-point-hit" cx="${x(i)}" cy="${y(p.cumulative)}" r="15" fill="transparent"/><circle class="learning-point-dot" cx="${x(i)}" cy="${y(p.cumulative)}" r="5" fill="#358b4d"/></g>${i%step===0||i===points.length-1?`<text class="chart-x-label" x="${x(i)}" y="316">${p.label}</text>`:''}`).join('')}<text class="chart-axis-title" x="17" y="155" transform="rotate(-90 17 155)">QUESTIONS</text></svg>`;
 }
 function showTip(target){const p=points[Number(target.dataset.learningPoint)];if(!p)return;tip.innerHTML=`<strong>${esc(p.title)}</strong><p>${p.from===p.to?'當日':'本期'}完成 <b>${p.questions}</b> 題</p><p>字卡 ${p.cards} · 填充 ${p.blanks} · 詞語 ${p.words}</p><small>截至此日累積 ${p.cumulative} 題 · 點擊查看紀錄</small>`;tip.hidden=false;const rect=target.getBoundingClientRect(),size=tip.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(innerWidth-size.width-8,rect.left))+'px';tip.style.top=Math.max(8,Math.min(innerHeight-size.height-8,rect.bottom+8))+'px';}
 function rowHtml(row){let title=row.front||'歷史字卡彙總',text=row.back||'',url=row.exercise?`./?deck=${encode(row.exercise)}${row.item?'&card='+encode(row.item):''}`:null,type='字卡';
  if(row.kind==='blank'){const d=window.EDMUND_PROFESSIONAL_DIALOGUES?.find(d=>d.id===row.exercise),line=d?.lines[Number(row.item?.split(':')[0])];title=d?.titleZh||row.exercise||'填充練習';text=line?line.en+'\n'+line.zh:row.item?'題目 '+row.item:'';url=row.exercise?`./dialogue.html?id=${encode(row.exercise)}`:null;type='填充';}
  if(row.kind==='polysemy'){const match=/^lesson-(\d+):(.+)$/.exec(row.exercise||'');title=match?match[2]:'一詞多義';text=match?'第 '+match[1]+' 課 · 已完成此詞語的所有意思':'';url=match?`./polysemy.html?lesson=${encode(match[1])}&word=${encode(match[2])}`:null;type='一詞多義';}
  if(row.legacy)text=(text?text+'\n':'')+'歷史彙總：當時未儲存逐題內容。';
  return `<article class="learning-record"><div><small>${type} · ${esc(row.date)} · ${new Date(row.occurred_at).toLocaleTimeString('zh-HK',{timeZone:'Asia/Hong_Kong',hour:'2-digit',minute:'2-digit'})}</small><h4>${esc(title)}</h4><p>${esc(text)}</p>${row.deck_title?`<small>${esc(row.deck_title)}</small>`:''}</div><div class="learning-record-action"><strong>${Number(row.points)||0} 題</strong>${url?`<a href="${url}">前往練習 <svg class="pro-ui-arrow" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M6 18 18 6M6 6h12v12"/></svg></a>`:''}</div></article>`;
 }
 async function load(page=1){if(!selected||!owns())return;const serial=++request,period={...selected};if(page===1){rows=[];details.hidden=false;details.innerHTML=`<h4 tabindex="-1">${esc(period.title)} · 學習紀錄</h4><p role="status">正在載入…</p>`;}else details.querySelector('[data-history-more]').disabled=true;
  try{const data=await rpc('learning_details',{p_course:courseId,p_from:period.from,p_to:period.to,p_page:page},owner);if(!owns()||serial!==request)return;rows.push(...data.rows);currentPage=page;details.innerHTML=`<div class="learning-record-heading"><h4 tabindex="-1">${esc(period.title)} · 學習紀錄</h4><button type="button" data-history-close aria-label="收起學習紀錄">收起 ×</button></div><p>${Number(data.questions)||0} 題已完成 · 字卡答對、填空答對、整個詞語完成各計一題。</p><div class="learning-record-list">${rows.map(rowHtml).join('')||'<p>這段時間沒有已完成的題目。</p>'}</div><p class="history-pagination">已顯示 ${rows.length} / ${Number(data.total)||0} 項紀錄</p>${rows.length<data.total?'<button type="button" data-history-more>載入更多紀錄 <svg class="pro-ui-arrow" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M12 5v14m-6-6 6 6 6-6"/></svg></button>':''}`;
  }catch{if(owns()&&serial===request){if(page===1)details.innerHTML=`<h4>${esc(period.title)} · 學習紀錄</h4><p role="status">暫時未能載入紀錄。</p><button type="button" data-history-retry>重試</button>`;else{details.querySelector('[data-history-more]').disabled=false;details.querySelector('.history-pagination').textContent='未能載入更多，請重試。';}}}
 }
 function choose(target){selected=points[Number(target.dataset.learningPoint)];tip.hidden=true;draw();void load();}
 host.addEventListener('mouseover',e=>{const t=e.target.closest('[data-learning-point]');if(t)showTip(t);});host.addEventListener('focusin',e=>{const t=e.target.closest('[data-learning-point]');if(t)showTip(t);});
 host.addEventListener('mouseout',e=>{if(e.target.closest('[data-learning-point]'))tip.hidden=true;});host.addEventListener('focusout',()=>tip.hidden=true);
 host.addEventListener('click',e=>{const t=e.target.closest('[data-learning-point]');if(t)choose(t);else if(e.target.closest('[data-history-more]'))void load(currentPage+1);else if(e.target.closest('[data-history-retry]'))void load();else if(e.target.closest('[data-history-close]')){selected=null;request++;details.hidden=true;draw();}});
 host.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.matches('[data-learning-point]')){e.preventDefault();choose(e.target);}});
 return {update(daily,range){const next=learningPoints(daily||[],range),key=JSON.stringify(next);if(key===signature)return;signature=key;points=next;tip.hidden=true;if(selected){const nextSelected=points.find(p=>p.from===selected.from&&p.to===selected.to);if(!nextSelected){selected=null;request++;details.hidden=true;}else if(nextSelected.questions!==selected.questions){selected=nextSelected;void load();}}draw();},destroy(){active=false;request++;host.replaceChildren();}};
}
