import {escapeHtml as esc,sourceLabel} from './library-core.mjs?v=20260916-ui-polish1';
import {highlightQuery,searchData} from './search.mjs?v=20260916-ui-polish1';
export async function materialsPage(page){
 const params=new URLSearchParams(location.search),[{materials},support,audio]=await Promise.all([searchData(),fetch('./content/reader-support.json?v=20260916-ui-polish1').then(r=>r.json()),fetch('./dialogue-audio.json?v=20260916-ui-polish1').then(r=>r.json())]);
 const lesson=materials.find(l=>l.lesson===Number(params.get('lesson')))||materials[0],initial=Math.max(1,Math.min(lesson.pages.length,Number(params.get('page'))||1)),q=params.get('q')||'';let shown=initial,player=null;
 page.insertAdjacentHTML('beforeend',`<div class="material-downloads">${materials.map(l=>`<article><h2>第 ${l.lesson} 課</h2><p>${esc(l.title)}</p><a href="./library.html?view=materials&lesson=${l.lesson}">閱讀文字版</a><a href="./${l.pdf}" download="Professional-English-Lesson-${l.lesson}.pdf"><svg class="pro-ui-arrow" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M12 5v14m-6-6 6 6 6-6"/></svg> 下載 PDF · ${l.pages.length} 頁</a></article>`).join('')}</div><section class="material-reader"><header class="material-reader-controls"><h2>第 ${lesson.lesson} 課 · ${esc(lesson.title)}</h2><label>跳至頁數<select data-material-page>${lesson.pages.map(p=>`<option value="${p.page}" ${p.page===initial?'selected':''}>${sourceLabel(p)}</option>`).join('')}</select></label><button type="button" data-reader-translation aria-pressed="false">中文翻譯 OFF</button><a data-reader-pdf href="./${lesson.pdf}#page=${initial}" target="_blank" rel="noopener">查看原版 PDF <svg class="pro-ui-arrow" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M6 18 18 6M6 6h12v12"/></svg></a></header><p class="material-colour-note">保留教材的角色顏色與教學重點。開啟中文翻譯可查看對話譯文；有錄音的原句可按 ▶ 聆聽。</p><div data-reader-pages></div><nav class="material-pagination"><span data-page-count></span><button type="button" class="reader-next-page" data-append-page>＋ 顯示下一頁 <svg class="pro-ui-arrow" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M12 5v14m-6-6 6 6 6-6"/></svg></button></nav></section>`);
 const reader=page.querySelector('.material-reader'),container=page.querySelector('[data-reader-pages]');
 const toolbar=reader.querySelector('.material-reader-controls');
 const resize=new ResizeObserver(()=>reader.style.setProperty('--reader-toolbar-height',toolbar.getBoundingClientRect().height+'px'));resize.observe(toolbar);
 window.addEventListener('pagehide',()=>resize.disconnect(),{once:true});
 function selectPage(n){page.querySelector('[data-material-page]').value=String(n);page.querySelector('[data-reader-pdf]').href=`./${lesson.pdf}#page=${n}`;}
 function jumpToPage(n,behavior='smooth'){requestAnimationFrame(()=>{const target=container.querySelector(`[data-source-page="${n}"]`);if(!target)return;const height=toolbar.getBoundingClientRect().height;reader.style.setProperty('--reader-toolbar-height',height+'px');window.scrollTo({top:Math.max(0,window.scrollY+target.getBoundingClientRect().top-height-24),behavior});});}
 function append(n){if(container.querySelector(`[data-source-page="${n}"]`))return;const source=lesson.pages[n-1],article=document.createElement('article');article.className='material-text';article.dataset.sourcePage=n;article.setAttribute('aria-label',`課文第 ${n} 頁`);article.innerHTML=`<div class="reader-page-flag">第 ${n} 頁 / ${lesson.pages.length}</div><div class="material-original">${source.html}</div>`;container.append(article);const original=article.querySelector('.material-original');
 for(const turn of support.pages[lesson.lesson+':'+n]||[]){const cell=original.querySelectorAll('table')[turn.table]?.rows[turn.row]?.cells[turn.cell];if(!cell)continue;const tools=document.createElement('div');tools.className='reader-turn-tools';const path=turn.audio&&audio[`${turn.dialogue}:${turn.line}`]?.path;if(path){const b=document.createElement('button');b.type='button';b.className='reader-audio';b.dataset.readerAudio=path;b.setAttribute('aria-label','聆聽原句');b.innerHTML='▶ <span>聆聽</span>';tools.append(b);}const zh=document.createElement('p');zh.className='reader-translation';zh.textContent=turn.zh;cell.append(tools,zh);}
 for(const item of support.upgrades.filter(u=>u.lesson===lesson.lesson&&u.page===n)){const target=original.querySelectorAll(item.selector)[item.index];if(!target)continue;const details=document.createElement('details');details.className='quick-upgrade-answer';details.innerHTML=`<summary>顯示專業句式答案</summary><p class="upgrade-source">課文原句 · 第 ${item.source.page} 頁${item.note?' · '+esc(item.note):''}</p><blockquote>${esc(item.answer)}</blockquote><p class="upgrade-translation">${esc(item.translation)}</p>`;if(item.selector==='tr'){target.cells[1].replaceChildren(details);}else target.append(details);}
 highlightQuery(original,q);}
 function controls(){page.querySelector('[data-page-count]').textContent=`已顯示第 1–${shown} 頁 · 共 ${lesson.pages.length} 頁`;const b=page.querySelector('[data-append-page]');b.disabled=shown>=lesson.pages.length;b.innerHTML=b.disabled?'✓ 全部頁面已顯示':`＋ 顯示第 ${shown+1} 頁 <svg class="pro-ui-arrow" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M12 5v14m-6-6 6 6 6-6"/></svg>`;}
 // Deep links show the requested page and keep earlier pages available in one scroll.
 for(let i=1;i<=initial;i++)append(i);controls();
 page.querySelector('[data-append-page]').onclick=()=>{if(shown<lesson.pages.length){append(++shown);controls();selectPage(shown);jumpToPage(shown);}};
 page.querySelector('[data-material-page]').onchange=e=>{const n=Number(e.target.value);while(shown<n)append(++shown);controls();selectPage(n);jumpToPage(n);};
 page.querySelector('[data-reader-translation]').onclick=e=>{const on=reader.classList.toggle('show-translations');e.currentTarget.setAttribute('aria-pressed',String(on));e.currentTarget.textContent=on?'中文翻譯 ON':'中文翻譯 OFF';};
 reader.addEventListener('click',async e=>{const b=e.target.closest('[data-reader-audio]');if(!b)return;player?.pause();reader.querySelectorAll('[data-reader-audio]').forEach(x=>x.setAttribute('aria-pressed','false'));player=new Audio(new URL(b.dataset.readerAudio,location.href));b.setAttribute('aria-pressed','true');player.onended=()=>b.setAttribute('aria-pressed','false');try{await player.play();}catch{b.setAttribute('aria-pressed','false');const status=page.querySelector('[data-library-status]');if(status)status.textContent='錄音暫時未能播放，請再試。';}});
 window.addEventListener('pagehide',()=>player?.pause(),{once:true});if(params.has('page'))jumpToPage(initial,'instant');
}
