import {rpc,session} from './learning-state.mjs?v=20260916-ui-polish1';
import {escapeHtml as esc,searchContent} from './library-core.mjs?v=20260916-ui-polish1';
let content;
async function json(path){const r=await fetch(path);if(!r.ok)throw Error('資料暫時未能載入，請重試。');return r.json();}
export function searchData(){return content??=Promise.all([json('./content/lesson-materials.json?v=20260916-ui-polish1'),json('./dialogues.json?v=20260916-ui-polish1'),...[1,2,3].map(n=>json(`./content/lesson-${n}-polysemy.json?v=20260916-ui-polish1`))]).then(([materials,data,...polysemy])=>({materials,dialogues:data.dialogues,polysemy})).catch(e=>{content=null;throw e;});}
export function highlightQuery(container,query){if(!query)return;const walker=document.createTreeWalker(container,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())if(!walker.currentNode.parentElement.closest('button,script,style'))nodes.push(walker.currentNode);for(const node of nodes){const text=node.textContent,low=text.toLowerCase(),q=query.toLowerCase();let start=0,at=low.indexOf(q);if(at<0)continue;const f=document.createDocumentFragment();while(at>=0){f.append(text.slice(start,at));const m=document.createElement('mark');m.className='search-hit';m.textContent=text.slice(at,at+q.length);f.append(m);start=at+q.length;at=low.indexOf(q,start);}f.append(text.slice(start));node.replaceWith(f);}}
export function resultHtml(entries){return [['課文 · Textbook',entries.filter(r=>r.kind==='課文')],['練習 · Exercises',entries.filter(r=>r.kind!=='課文')]].map(([title,rows])=>`<section class="search-column"><h2>${title}<small>${rows.length} 個位置</small></h2>${rows.map(r=>`<article class="library-result"><div class="library-result-meta">${esc(r.kind)} · 第 ${r.lesson||'—'} 課 · ${esc(r.location)}</div><h3><a href="${esc(r.href)}">${esc(r.title)}</a></h3><p>${esc(r.text)}</p></article>`).join('')||'<p class="search-empty">這一類沒有相符結果。</p>'}</section>`).join('');}
export function bindLiveSearch(form,results,status,{url=false}={}){let sequence=0,timer,active=true;const owner=session(),flashCache=new Map();async function run(){const seq=++sequence,q=form.elements.q.value.trim().slice(0,200),lesson=form.elements.lesson?.value||'',type=form.elements.type?.value||'';if(url)history.replaceState(null,'','./library.html?'+new URLSearchParams({view:'search',q,...(lesson?{lesson}:{}),...(type?{type}:{})}));if(!q){results.replaceChildren();status.textContent='輸入詞語，即時查看課文與練習位置。';return;}status.textContent='正在搜尋…';try{const data=await searchData();if(!active||seq!==sequence)return;let rows=searchContent(data,q),warning='';const show=()=>{const filtered=rows.filter(r=>(!lesson||String(r.lesson)===lesson)&&(!type||r.kind===type));results.innerHTML=resultHtml(filtered);results.querySelectorAll('p,h3').forEach(p=>highlightQuery(p,q));status.textContent=`${filtered.length} 個位置${warning?' · '+warning:''}`;};show();try{let flash=flashCache.get(q);if(!flash){flash=await rpc('search',{p_query:q},owner);flashCache.set(q,flash);}if(!active||seq!==sequence||session()?.user?.id!==owner?.user?.id)return;for(const r of flash.results||[])rows.push({kind:'字卡',lesson:Number((r.deck_title.match(/(?:Class|Lesson)\s*(\d+)/i)||[])[1])||0,title:r.front,location:r.deck_title+(r.position?` · 第 ${r.position} 張`:''),text:r.back+' '+r.note,href:`./?deck=${encodeURIComponent(r.deck_id)}&card=${encodeURIComponent(r.card_id)}`});if(flash.has_more)warning='字卡結果超過 100 項，請輸入更完整的詞語。';}catch{warning='字卡暫時未能連線；課文與練習仍可搜尋。';}if(active&&seq===sequence)show();}catch(e){if(active&&seq===sequence)status.textContent=e.message;}}
const input=()=>{++sequence;clearTimeout(timer);timer=setTimeout(run,250);};form.addEventListener('input',input);form.addEventListener('change',input);form.addEventListener('submit',e=>{e.preventDefault();clearTimeout(timer);void run();});void run();return()=>{active=false;++sequence;clearTimeout(timer);};}
