// Protected Phrasal Verb answer catalogue.
//
// This static trust-boundary copy comes only from the visually verified
// canonical answers in `phrasal-verb-system-data.js`. Every key must be
// present exactly once, from `phrasal-verb-01-q01` through
// `phrasal-verb-01-q70`. Each value is an array whose first item is the
// canonical English answer; later items are deliberately approved variants
// from `acceptedAnswers`. Never invent answers or ship placeholder strings.
// If this catalogue becomes incomplete, claimed-correct scoring fails closed
// and the Worker health endpoint reports that the catalogue is not ready.
export const ACCEPTED_ANSWERS = Object.freeze({
  "phrasal-verb-01-q01": Object.freeze(["Traffic is building up outside the school."]),
  "phrasal-verb-01-q02": Object.freeze(["The teacher built the lesson around a short song.","The teacher built the lesson round a short song."]),
  "phrasal-verb-01-q03": Object.freeze(["The TV show built Mia up as its next big star."]),
  "phrasal-verb-01-q04": Object.freeze(["They built a small room onto the back of the house."]),
  "phrasal-verb-01-q05": Object.freeze(["Today’s lesson builds on what we learnt last week.","Today’s lesson builds upon what we learnt last week."]),
  "phrasal-verb-01-q06": Object.freeze(["Good food helped build Sam up after he was ill."]),
  "phrasal-verb-01-q07": Object.freeze(["The team built its plan on one simple idea.","The team built its plan upon one simple idea."]),
  "phrasal-verb-01-q08": Object.freeze(["Start with ten minutes of running and build up to thirty minutes."]),
  "phrasal-verb-01-q09": Object.freeze(["We built a short break into the plan from the start."]),
  "phrasal-verb-01-q10": Object.freeze(["Lina built up a collection of old coins."]),
  "phrasal-verb-01-q11": Object.freeze(["The adverts built the new game up far too much."]),
  "phrasal-verb-01-q12": Object.freeze(["The game was built around one simple rule.","The game was built round one simple rule."]),
  "phrasal-verb-01-q13": Object.freeze(["The team wants to build on last month’s success and do even better.","The team wants to build upon last month’s success and do even better."]),
  "phrasal-verb-01-q14": Object.freeze(["I was weak, and the doctor told me to build myself up by eating well."]),
  "phrasal-verb-01-q15": Object.freeze(["A small light is built into the new phone."]),
  "phrasal-verb-01-q16": Object.freeze(["The website is building this small event up as the biggest event of the year."]),
  "phrasal-verb-01-q17": Object.freeze(["We are building on our good start to make the project better.","We are building upon our good start to make the project better."]),
  "phrasal-verb-01-q18": Object.freeze(["Over the next year, I want to build up my savings."]),
  "phrasal-verb-01-q19": Object.freeze(["We will build a small shop onto the front of the building."]),
  "phrasal-verb-01-q20": Object.freeze(["She is building up to the full test by starting with easy questions."]),
  "phrasal-verb-01-q21": Object.freeze(["The writer built the story round the search for one lost dog.","The writer built the story around the search for one lost dog."]),
  "phrasal-verb-01-q22": Object.freeze(["These simple exercises are building her up again."]),
  "phrasal-verb-01-q23": Object.freeze(["The writer is building her story on something that really happened.","The writer is building her story upon something that really happened."]),
  "phrasal-verb-01-q24": Object.freeze(["Dust has built up under the bed."]),
  "phrasal-verb-01-q25": Object.freeze(["The plan needs extra time, so we will build it in from the start."]),
  "phrasal-verb-01-q26": Object.freeze(["We are building the party around space and stars.","We are building the party round space and stars."]),
  "phrasal-verb-01-q27": Object.freeze(["The school is building up a collection of books for its reading room."]),
  "phrasal-verb-01-q28": Object.freeze(["The family is building another bathroom onto the house."]),
  "phrasal-verb-01-q29": Object.freeze(["The house needed one more room, so they built it onto the side of the house."]),
  "phrasal-verb-01-q30": Object.freeze(["Water built up near the door during the rain."]),
  "phrasal-verb-01-q31": Object.freeze(["The second class built on what they learnt in the first class.","The second class built upon what they learnt in the first class."]),
  "phrasal-verb-01-q32": Object.freeze(["They built the school show around the children’s favourite book.","They built the school show round the children’s favourite book."]),
  "phrasal-verb-01-q33": Object.freeze(["Maya slowly built up a list of songs for the party."]),
  "phrasal-verb-01-q34": Object.freeze(["They built a safety check into every lesson."]),
  "phrasal-verb-01-q35": Object.freeze(["We began with short walks and built up to the long hill walk."]),
  "phrasal-verb-01-q36": Object.freeze(["They had one simple rule. They built the new game on it.","They had one simple rule. They built the new game upon it."]),
  "phrasal-verb-01-q37": Object.freeze(["I was going to see the film. My friends built it up before I saw it."]),
  "phrasal-verb-01-q38": Object.freeze(["A line was building up outside the shop."]),
  "phrasal-verb-01-q39": Object.freeze(["Ben was weak after being ill, so his family helped build him up again."]),
  "phrasal-verb-01-q40": Object.freeze(["He saved every useful word and slowly built up a long word list."]),
  "phrasal-verb-01-q41": Object.freeze(["The team should build on today’s good work in the next game.","The team should build upon today’s good work in the next game."]),
  "phrasal-verb-01-q42": Object.freeze(["The new class was built upon the skills from the first class.","The new class was built on the skills from the first class."]),
  "phrasal-verb-01-q43": Object.freeze(["Starting with five photos, the club built up a collection of hundreds of photos by adding more every week."]),
  "phrasal-verb-01-q44": Object.freeze(["I am building myself up to speaking in front of the whole class."]),
  "phrasal-verb-01-q45": Object.freeze(["The makers built a five-minute rest into the app."]),
  "phrasal-verb-01-q46": Object.freeze(["The school built the final match up as the most important match of the year."]),
  "phrasal-verb-01-q47": Object.freeze(["Heat built up in the room because the windows were closed."]),
  "phrasal-verb-01-q48": Object.freeze(["The whole day was built around helping new students feel welcome.","The whole day was built round helping new students feel welcome."]),
  "phrasal-verb-01-q49": Object.freeze(["The new plan builds upon the best parts of the old plan.","The new plan builds on the best parts of the old plan."]),
  "phrasal-verb-01-q50": Object.freeze(["The old school built on a new art room at the back."]),
  "phrasal-verb-01-q51": Object.freeze(["A month of good meals and rest built the children up."]),
  "phrasal-verb-01-q52": Object.freeze(["The story in the book is built on the writer’s own childhood.","The story in the book is built upon the writer’s own childhood."]),
  "phrasal-verb-01-q53": Object.freeze(["Leo did not ask the question at once; he took time to build himself up to asking it."]),
  "phrasal-verb-01-q54": Object.freeze(["The company built the new phone up to be the best phone ever before it was sold."]),
  "phrasal-verb-01-q55": Object.freeze(["The maker built a shelf into the table."]),
  "phrasal-verb-01-q56": Object.freeze(["Dark clouds were building up over the hills."]),
  "phrasal-verb-01-q57": Object.freeze(["Before Ben played his first game, people were already building him up as the player who could save the team."]),
  "phrasal-verb-01-q58": Object.freeze(["Because the trip may take longer than planned, we built an extra hour into the timetable before booking anything."]),
  "phrasal-verb-01-q59": Object.freeze(["Mia wanted to phone the school, but she needed a few minutes to build herself up to making the call."]),
  "phrasal-verb-01-q60": Object.freeze(["Over the year, the class built up a long list by saving every useful website it found."]),
  "phrasal-verb-01-q61": Object.freeze(["We should build on what already works instead of starting again.","We should build upon what already works instead of starting again."]),
  "phrasal-verb-01-q62": Object.freeze(["After a long time in bed, she needed to build herself up before returning to school."]),
  "phrasal-verb-01-q63": Object.freeze(["The club built its own plan on the ideas of its members instead of copying another group’s plan.","The club built its own plan upon the ideas of its members instead of copying another group’s plan."]),
  "phrasal-verb-01-q64": Object.freeze(["Instead of moving to a larger home, the family built on another floor."]),
  "phrasal-verb-01-q65": Object.freeze(["At first the hall was quiet, but noise from the crowd built up before the show began."]),
  "phrasal-verb-01-q66": Object.freeze(["The club built the whole day around music so every activity connected with it.","The club built the whole day round music so every activity connected with it."]),
  "phrasal-verb-01-q67": Object.freeze(["The runners started with short distances and built up to ten kilometres instead of running it on day one."]),
  "phrasal-verb-01-q68": Object.freeze(["I was very tired after being ill, so I used food, sleep and easy exercise to build myself up again."]),
  "phrasal-verb-01-q69": Object.freeze(["The café was too small, so the owners built a glass room onto the back of it for more tables."]),
  "phrasal-verb-01-q70": Object.freeze(["The game looks new, but it is built upon the rules of a much older game.","The game looks new, but it is built on the rules of a much older game."]),
});
