#!/usr/bin/env node
// Register complete, validated practices. Homework uses this same catalogue.
import fs from 'node:fs/promises';
import { validatePractice } from '../../listening-practice-loader.mjs';
const root = new URL('../../', import.meta.url);
const directory = new URL('assets/listening/practices/', root);
const practices = [1];
for (const file of await fs.readdir(directory)) {
  const match = file.match(/^practice-(\d+)\.json$/);
  if (!match) continue;
  const number = Number(match[1]);
  if (number === 1) throw new Error('Practice 1 uses the legacy adapter: do not replace its bookmark indexes.');
  validatePractice(JSON.parse(await fs.readFile(new URL(file,directory),'utf8')),number);
  practices.push(number);
}
practices.sort((a,b)=>a-b);
const code = `// Generated by tools/listening/generate_catalog.mjs; do not hand-edit.\n(function registerListeningCatalogue() {\n  "use strict";\n  const practiceNumbers = ${JSON.stringify(practices)};\n  const practices = practiceNumbers.map(practice => Object.freeze({\n    id: \`ielts-listening-practice-\${practice}\`, practice,\n    title: \`IELTS Listening Practice \${practice}\`,\n    href: \`listening-system.html?section=ielts&practice=\${practice}\`,\n    parts: Object.freeze(Array.from({ length: 4 }, (_, index) => {\n      const part = index + 1;\n      return Object.freeze({ id: \`ielts-listening-practice-\${practice}-part-\${part}\`, practice, part,\n        title: \`IELTS Listening Practice \${practice} - Part \${part}\`,\n        href: \`listening-system.html?section=ielts&practice=\${practice}&part=\${part}\` });\n    }))\n  }));\n  window.EDMUND_LISTENING_CATALOG = Object.freeze({ version: 2, systems: Object.freeze([\n    Object.freeze({id:"dse",title:"DSE Paper 3 Part A 聆聽"}),\n    Object.freeze({id:"ielts",title:"IELTS 聆聽"})\n  ]), practices: Object.freeze(practices) });\n})();\n`;
await fs.writeFile(new URL('listening-system-catalog.js',root),code);
console.log(`Registered ${practices.length} complete Listening practices.`);
