// Public lesson answers mirrored from sentence-structure-data.js. The answers
// are already visible in the browser; this server copy prevents clients from
// manufacturing progress records whose claimed correct answers do not match
// the shipped content. Keep the catalog-sync test green whenever content moves.
export const ACCEPTED_ANSWERS = Object.freeze({
  "ss1-q01": ["I went to the library to borrow a book."],
  "ss1-q02": ["Lily got up early to catch the first bus."],
  "ss1-q03": ["Tom called his teacher to ask a question."],
  "ss1-q04": ["We went to the supermarket to buy some fresh fruit."],
  "ss1-q05": ["Mia opened the window to get some fresh air."],
  "ss1-q06": ["Jack is saving money to buy a new bicycle."],
  "ss1-q07": ["Ben visited the doctor to get some advice."],
  "ss1-q08": ["I use a notebook to write down new words."],
  "ss1-q09": ["Emma wore a thick coat to stay warm."],
  "ss1-q10": ["The students practised English every day to improve their speaking skills."],
  "ss1-q11": ["Sarah joined a cooking class to learn how to make Italian food."],
  "ss1-q12": ["David spoke quietly to avoid waking the baby."],
  "ss1-q13": ["This button is used to turn on the computer."],
  "ss1-q14": ["Amy brought a camera to take pictures of the beautiful view."],
  "ss1-q15": ["This meeting is being held to discuss our new project."],
  "ss1-q16": ["Kevin went online to find information about the museum."],
  "ss1-q17": ["Take an umbrella to stay dry in the rain."],
  "ss1-q18": ["My mother gave me some money to buy lunch."],
  "ss1-q19": ["The team held an extra practice to have a better chance of winning the next match."],
  "ss1-q20": ["Jason moved closer to the screen to see the words more clearly."],
  "ss1-q21": ["Olivia went to the bank to open a new account."],
  "ss1-q22": ["The teacher repeated the instructions to help everyone understand them."],
  "ss1-q23": ["Henry left the house early to avoid being late for work."],
  "ss1-q24": ["This machine was designed to clean the floor."],
  "ss1-q25": ["Chloe started exercising three times a week to improve her health."],
  "ss1-q26": ["They are decorating the hall to hold a school party there."],
  "ss1-q27": ["The police officer stopped the traffic to help the children cross the road safely."],
  "ss1-q28": ["You should read the question carefully before answering to avoid making careless mistakes."],
  "ss1-q29": ["A special room was prepared to give the guests a place to rest."],
  "ss1-q30": ["Lucy wrote a list of everything she needed to avoid forgetting anything at the supermarket."],
  "ss1-q31": ["Noah turned on the desk lamp to read more clearly."],
  "ss1-q32": ["The museum provides maps to help visitors find the different rooms easily."],
  "ss1-q33": ["Maya carries a reusable bottle to reduce plastic waste."],
  "ss1-q34": ["The ladder is used to reach the top shelf."],
  "ss1-q35": ["Leo set an alarm to wake up on time."],
  "ss1-q36": ["The nurse closed the door to give the patient more privacy."],
  "ss1-q37": ["Grace checked her work twice to reduce her spelling mistakes."],
  "ss1-q38": ["The lights were switched off to avoid wasting electricity."],
  "ss1-q39": ["Use this key to open the back door."],
  "ss1-q40": ["Ava lowered her voice to avoid disturbing the people who were reading."],
  "ss1-q41": ["Ethan went to the customer service desk to ask for help with his lost bag."],
  "ss1-q42": ["The school installed more water fountains to make it easier for students to refill their bottles."],
  "ss1-q43": ["This shelf is used to display the library’s new books."],
  "ss1-q44": ["Zoe opened the curtains to make the room brighter."],
  "ss1-q45": ["Daniel checked the train timetable to avoid missing the last train."],
  "ss1-q46": ["The chef tasted the soup to check whether it needed more salt."],
  "ss1-q47": ["Emma wrote the instructions step by step to make them easier for her younger brother to follow."],
  "ss1-q48": ["A small bridge was built to help the villagers cross the river safely."],
  "ss1-q49": ["You should wear these gloves to protect your hands from the paint."],
  "ss1-q50": ["The coach showed the players a video of their previous game to help them understand their mistakes."],
  "ss2-q01": ["I am an optimistic person."],
  "ss2-q02": ["Amy is a patient person."],
  "ss2-q03": ["Ben is an honest person."],
  "ss2-q04": ["Chloe is a friendly person."],
  "ss2-q05": ["Leo is an active person."],
  "ss2-q06": ["Nina is a diligent student."],
  "ss2-q07": ["Omar is a helpful neighbour."],
  "ss2-q08": ["They are energetic players."],
  "ss2-q09": ["We are responsible employees."],
  "ss2-q10": ["My aunt is a caring nurse."],
  "ss2-q11": ["Lily is a creative designer."],
  "ss2-q12": ["Mr Chan is a patient teacher.", "Mr Chan is our patient teacher."],
  "ss2-q13": ["Maya is a talented singer."],
  "ss2-q14": ["Daniel is a careful driver."],
  "ss2-q15": ["Grace is an organised secretary."],
  "ss2-q16": ["Ethan is an experienced chef."],
  "ss2-q17": ["Olivia is a curious learner."],
  "ss2-q18": ["Noah is a cheerful child."],
  "ss2-q19": ["The twins are polite guests.", "The twins are our polite guests."],
  "ss2-q20": ["My parents are understanding people."],
  "ss2-q21": ["This is a useful tool."],
  "ss2-q22": ["That is an expensive watch."],
  "ss2-q23": ["It is a comfortable chair."],
  "ss2-q24": ["This is an interesting book."],
  "ss2-q25": ["The teacher says it is a difficult question."],
  "ss2-q26": ["Hong Kong is a busy city."],
  "ss2-q27": ["The new library is a modern building."],
  "ss2-q28": ["That is a peaceful village."],
  "ss2-q29": ["It is a dangerous road."],
  "ss2-q30": ["The panda is a gentle animal."],
  "ss2-q31": ["Emma is a very reliable teammate."],
  "ss2-q32": ["Jason is an unusually quiet student."],
  "ss2-q33": ["This is not a complicated solution."],
  "ss2-q34": ["It was an exciting match."],
  "ss2-q35": ["It was not a surprising result."],
  "ss2-q36": ["That was a sensible decision."],
  "ss2-q37": ["It is not a difficult rule."],
  "ss2-q38": ["The museum is a popular attraction."],
  "ss2-q39": ["Our dog is a very loyal animal."],
  "ss2-q40": ["The laptop is not a powerful machine."],
  "ss2-q41": ["Aisha is a calm person."],
  "ss2-q42": ["Marcus is a dependable worker."],
  "ss2-q43": ["Everyone in the class knows that Sofia is a thoughtful person."],
  "ss2-q44": ["I think it is a practical plan."],
  "ss2-q45": ["The guide said it was a safe path."],
  "ss2-q46": ["The manager explained that it was an urgent task."],
  "ss2-q47": ["The doctor told us that it was a serious illness."],
  "ss2-q48": ["Although it is a small room, it is comfortable."],
  "ss2-q49": ["It was a long but engaging film."],
  "ss2-q50": ["It was a challenging but valuable project for the team."]
});
