-- GENERATED FILE. Apply after ../supabase-writing-grammar-corpus.sql.
-- Source: corpus-v1.json

begin;

do $$
declare
  v_existing_hash text;
  v_existing_status text;
begin
  select content_sha256, status into v_existing_hash, v_existing_status from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1';
  if v_existing_hash is not null and v_existing_hash <> 'b097b05fa1c46cd8851f48a859d03bbe9b4cb6d4214cb8a7f26ab479cf1dabf9' then
    raise exception 'Corpus version already exists with different content';
  end if;
  if v_existing_hash is not null and v_existing_status <> 'approved' then
    raise exception 'Corpus version exists but is not an approved release';
  end if;
end;
$$;

update public.writing_grammar_corpus_releases set is_current = false where is_current and corpus_version <> '2026-08-01.1';

insert into public.writing_grammar_corpus_releases (corpus_version, schema_version, status, is_current, title, notes, content_sha256, approved_at)
values ('2026-08-01.1', 1, 'reviewed', false, 'Edmund Sir Teacher-Approved Grammar Corpus — Release 1', 'Initial normalized corpus containing PARA-0001 and PARA-0002.', 'b097b05fa1c46cd8851f48a859d03bbe9b4cb6d4214cb8a7f26ab479cf1dabf9', null)
on conflict (corpus_version) do nothing;

insert into public.writing_grammar_corpus_groups (corpus_version, group_key, partition, description)
select '2026-08-01.1', 'WORKPLACE_UNIFORMS_001', 'retrieval', 'Workplace-uniform paragraph family for approved retrieval examples.'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_corpus_groups (corpus_version, group_key, partition, description)
select '2026-08-01.1', 'JAPAN_TRAVEL_001', 'retrieval', 'Japan-travel paragraph family for approved retrieval examples.'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;

insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'MANY_PLURAL_NOUN', 'many 後使用可數名詞複數', 'singular_plural', 'many + plural countable noun', '["many","singular_countable_noun"]'::jsonb, 'many + singular countable noun', 'many + plural countable noun', 'many 後面接可數名詞複數。', '["many companies","many memories"]'::jsonb, '["many company","many memory"]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'PLURAL_SUBJECT_VERB', '複數主語與現在式動詞一致', 'subject_verb_agreement', 'plural subject + base-form present verb', '["plural_subject","present_verb_s"]'::jsonb, 'plural subject + present verb ending in s', 'plural subject + base-form present verb', '複數主語在一般現在式中通常配合不加 s 的動詞。', '["Companies require uniforms.","They need help."]'::jsonb, '["Companies requires uniforms.","They needs help."]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'STAFF_COLLECTIVE_NOUN', 'staff 的集合名詞用法', 'countability', 'staff / staff members', '["staff","nonstandard_plural"]'::jsonb, 'staffs when referring generally to employees', 'staff or staff members', 'staff 通常是集合名詞。可寫 staff 或 staff members，一般不寫 staffs。', '["The company supports its staff.","The staff members wear uniforms."]'::jsonb, '["The company supports its staffs."]'::jsonb, '["staff members"]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'TO_BASE_VERB', 'to 後使用動詞原形', 'infinitive_or_gerund', 'to + base verb', '["infinitive_to","inflected_verb"]'::jsonb, 'infinitive to + inflected verb', 'infinitive to + base verb', '不定詞 to 後面使用動詞原形。', '["to wear uniforms"]'::jsonb, '["to wears uniforms"]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'SINGULAR_SUBJECT_VERB', '單數主語與現在式動詞一致', 'subject_verb_agreement', 'third-person singular subject + present verb ending in s', '["singular_subject","base_present_verb"]'::jsonb, 'third-person singular subject + base present verb', 'third-person singular subject + present verb ending in s', '第三身單數主語在一般現在式中，動詞通常要加 s 或使用相應的單數形式。', '["The policy has benefits.","The design does not suit everyone."]'::jsonb, '["The policy have benefits.","The design do not suit everyone."]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'SEVERAL_PLURAL_NOUN', 'several 後使用可數名詞複數', 'singular_plural', 'several + plural countable noun', '["several","singular_countable_noun"]'::jsonb, 'several + singular countable noun', 'several + plural countable noun', 'several 後面要接可數名詞複數。', '["several advantages"]'::jsonb, '["several advantage"]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'GENERAL_GROUP_PLURAL', '泛指群體時使用複數名詞', 'singular_plural', 'general group reference -> plural noun', '["general_reference","singular_countable_noun"]'::jsonb, 'bare singular countable noun used for a general group', 'plural countable noun used for a general group', '泛指某一類人或事物時，通常使用可數名詞複數。', '["Customers can find staff."]'::jsonb, '["Customer can find staff."]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'MODAL_BASE_VERB', '情態動詞後使用動詞原形', 'modal_or_auxiliary', 'can / could / may / might / should / must + base verb', '["modal","inflected_verb"]'::jsonb, 'modal + inflected verb', 'modal + base verb', 'can、may、should 等情態動詞後面，要直接使用最基本的動詞形式，不加 s、ed 或 ing。', '["Customers can identify staff.","Uniforms may save money.","Companies should provide suitable clothing."]'::jsonb, '["Customers can identifies staff.","Uniforms may saves money.","Companies should provides suitable clothing."]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'SPEND_MONEY_ON', 'spend money on 的介詞搭配', 'preposition', 'spend money on something', '["spend","money","for"]'::jsonb, 'spend money for something', 'spend money on something', '表示「花錢在某事上」使用 spend money on something。', '["Staff spend money on work clothes."]'::jsonb, '["Staff spend money for work clothes."]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'GENERAL_SOME_PLURAL', 'some 泛指可數群體時使用複數', 'singular_plural', 'some + plural countable noun', '["some","singular_countable_noun"]'::jsonb, 'some + singular countable noun in a group reference', 'some + plural countable noun', 'some 泛指一群可數的人或事物時，後面的名詞使用複數。', '["some employees"]'::jsonb, '["some employee"]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'SHARED_MODAL_PARALLEL', '共用情態動詞的平行結構', 'parallelism', 'modal + base verb + and + base verb', '["modal","coordinated_verbs","inflected_second_verb"]'::jsonb, 'modal + base verb + and + inflected verb', 'modal + base verb + and + base verb', '情態動詞同時控制兩個並列動詞時，兩個動詞都使用原形。', '["Companies should provide uniforms and allow choices."]'::jsonb, '["Companies should provide uniforms and allows choices."]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'PREPOSITION_GERUND', '介詞後使用動名詞', 'infinitive_or_gerund', 'preposition + verb-ing', '["preposition","past_or_base_verb"]'::jsonb, 'preposition + finite or past verb', 'preposition + verb-ing', '介詞後面的動作通常使用動名詞形式。', '["without causing discomfort"]'::jsonb, '["without caused discomfort"]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'PURPOSE_TO_INFINITIVE', '使用不定詞表達行動目的', 'infinitive_or_gerund', 'action + to + base verb', '["movement_or_action","for","base_verb"]'::jsonb, 'action + for + base verb', 'action + to + base verb', '表示某個行動的目的時，通常使用 to + 動詞原形。', '["We travelled to Japan to visit several cities."]'::jsonb, '["We travelled to Japan for visit several cities."]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'NEAR_PREPOSITION', 'near 直接接地方', 'preposition', 'near + place / close to + place', '["near","from","place"]'::jsonb, 'near from + place', 'near + place', 'near 可以直接接地方；也可以使用 close to。', '["near the railway station","close to the railway station"]'::jsonb, '["near from the railway station"]'::jsonb, '["close to"]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'ADJECTIVE_AFTER_BE', 'be 後使用形容詞描述狀態', 'word_form', 'be + degree adverb + adjective', '["be","very","noun_form"]'::jsonb, 'be + very + noun form', 'be + very + adjective form', 'be 動詞後描述主語狀態時，需要使用形容詞，而不是相關名詞。', '["Travelling was very convenient."]'::jsonb, '["Travelling was very convenience."]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'INFORMATION_UNCOUNTABLE', 'information 是不可數名詞', 'countability', 'much information / pieces of information', '["many","information_plural"]'::jsonb, 'many informations', 'much information or pieces of information', 'information 在一般英文中是不可數名詞，不能直接加 s。', '["much information","three pieces of information"]'::jsonb, '["many informations"]'::jsonb, '["a lot of information","several pieces of information"]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'INDIRECT_QUESTION_ORDER', '間接問句使用陳述句語序', 'sentence_structure', 'reporting verb + question word + subject + auxiliary/verb', '["reporting_verb","question_word","auxiliary_before_subject"]'::jsonb, 'ask + question word + auxiliary + subject + verb', 'ask + question word + subject + auxiliary/verb', '間接問句不是獨立問題，因此使用陳述句語序。疑問詞後面先寫主語，再寫動詞。', '["She asked where we should go.","I do not know what he wants.","Can you tell me when the lesson will start?"]'::jsonb, '["She asked where should we go.","I do not know what does he want.","Can you tell me when will the lesson start?"]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'SUGGEST_CONSTRUCTION', 'suggest 的句型', 'sentence_structure', 'suggest that + subject + base verb / suggest + verb-ing', '["suggest","object_pronoun","to_infinitive"]'::jsonb, 'suggest someone to do', 'suggest that someone do or suggest doing', 'suggest 通常使用 suggest that + 主語 + 動詞，或者 suggest + verb-ing。不要直接寫 suggest someone to do。', '["They suggested that we visit the temple.","They suggested visiting the temple."]'::jsonb, '["They suggested us to visit the temple."]'::jsonb, '["They suggested visiting the temple."]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'PASSIVE_RELATIVE_CLAUSE', '關係子句中的被動語態', 'verb_form_or_tense', 'relative pronoun + be + past participle', '["inanimate_subject","relative_pronoun","bare_past_participle"]'::jsonb, 'thing + that + past participle without be', 'thing + that + be + past participle', '主語是動作的承受者時，關係子句需要使用 be + 過去分詞的被動語態。', '["a temple that was built five hundred years ago"]'::jsonb, '["a temple that built five hundred years ago"]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'RAIN_IT_CONSTRUCTION', '描述下雨時使用形式主語 it', 'sentence_structure', 'it + be + raining', '["weather_subject","be","raining"]'::jsonb, 'the weather + be + raining', 'it + be + raining', '描述正在下雨時，最自然的主語通常是形式主語 it。', '["It was raining heavily."]'::jsonb, '["The weather was raining heavily."]'::jsonb, '["The weather was rainy."]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'ADVERB_POSITION', '副詞放在適當位置修飾動詞', 'word_form', 'verb + manner adverb', '["manner_adverb","verb_ing"]'::jsonb, 'manner adverb before the target verb in this construction', 'target verb + manner adverb', '副詞修飾動作的程度或方式時，要放在合適的位置。', '["It was raining heavily."]'::jsonb, '["It was heavily raining."]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'THIRD_CONDITIONAL_RESULT', '第三條件句的結果部分', 'verb_form_or_tense', 'If + had + past participle, would have + past participle', '["if_had_participle","would","past_form_without_have"]'::jsonb, 'If + had + past participle, would + past form', 'If + had + past participle, would have + past participle', '第三條件句談論未發生的過去情況；結果部分通常使用 would have + 過去分詞。', '["If we had brought an umbrella, we would not have got wet."]'::jsonb, '["If we had brought an umbrella, we would not got wet."]'::jsonb, '["would not have gotten wet"]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rules (corpus_version, rule_id, title_zh_hant, grammar_category, formula, structural_signature, incorrect_pattern, correct_pattern, explanation_zh_hant, correct_examples, incorrect_examples, alternative_corrections, english_variant, status, author, version)
select '2026-08-01.1', 'PAST_TENSE_PARALLEL', '敘述過去事件時保持並列動詞時態一致', 'parallelism', 'past verb + and + past verb', '["past_narrative","past_verb","and","base_verb"]'::jsonb, 'past verb + and + base present verb in a past narrative', 'past verb + and + past verb', '同一過去敘述中的並列動作，通常使用一致的過去式。', '["The journey gave us memories and broadened our knowledge."]'::jsonb, '["The journey gave us memories and broaden our knowledge."]'::jsonb, '[]'::jsonb, 'both', 'approved', 'Edmund Sir', 1
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;

insert into public.writing_grammar_paragraphs (corpus_version, paragraph_id, group_key, title, topic_category, student_level, incorrect_paragraph, corrected_paragraph, original_word_count, corrected_word_count, sentence_count, issue_count, english_variant, author, status, version, retrieval_eligible, evaluation_holdout, notes)
select '2026-08-01.1', 'PARA-0001', 'WORKPLACE_UNIFORMS_001', 'Workplace Uniforms', 'Work / Business', 'B1–B2', 'In recent years, many company requires their staffs to wears uniforms at work. This policy have several advantage for both workers and customer. First, customers can identifies employees quickly, especially when they needs help. Second, a uniform can reduces how much money staff spend for work clothes. However, some employee feels uncomfortable because the same design do not suit everyone. Uniforms may also makes workers feel that they has less personal freedom. In my opinion, companies should provides suitable uniforms and allows employees to choose between several styles, so the policy can remain professional without caused unnecessary discomfort at work.', 'In recent years, many companies require their staff to wear uniforms at work. This policy has several advantages for both workers and customers. First, customers can identify employees quickly, especially when they need help. Second, a uniform can reduce how much money staff spend on work clothes. However, some employees feel uncomfortable because the same design does not suit everyone. Uniforms may also make workers feel that they have less personal freedom. In my opinion, companies should provide suitable uniforms and allow employees to choose between several styles, so the policy can remain professional without causing unnecessary discomfort at work.', 100, 100, 7, 19, 'both', 'Edmund Sir', 'approved', 1, true, false, 'Multiple common ESL grammar problems.'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_paragraphs (corpus_version, paragraph_id, group_key, title, topic_category, student_level, incorrect_paragraph, corrected_paragraph, original_word_count, corrected_word_count, sentence_count, issue_count, english_variant, author, status, version, retrieval_eligible, evaluation_holdout, notes)
select '2026-08-01.1', 'PARA-0002', 'JAPAN_TRAVEL_001', 'A Family Trip to Japan', 'Travel / Culture', 'B1–B2', 'Last summer, my family travelled to Japan for visit several cities. We stayed in a hotel which was located near from the railway station, so travelling was very convenience. On the first day, we collected many informations from a tourist centre and asked the staff where should we go. They suggested us to visit an ancient temple that built over five hundred years ago. Although the weather was heavily raining, the temple was more beautiful than I expected. If we had brought an umbrella, we would not got wet. Overall, the journey gave us many memory and broaden our knowledge.', 'Last summer, my family travelled to Japan to visit several cities. We stayed in a hotel which was located near the railway station, so travelling was very convenient. On the first day, we collected much information from a tourist centre and asked the staff where we should go. They suggested that we visit an ancient temple that was built over five hundred years ago. Although it was raining heavily, the temple was more beautiful than I expected. If we had brought an umbrella, we would not have got wet. Overall, the journey gave us many memories and broadened our knowledge.', 100, 100, 7, 12, 'British English', 'Edmund Sir', 'approved', 1, true, false, 'Travel vocabulary with infinitive, preposition, countability, indirect-question, passive and conditional errors.'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;

insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0001-S01', 'PARA-0001', 1, 'In recent years, many company requires their staffs to wears uniforms at work.', 'In recent years, many companies require their staff to wear uniforms at work.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0001-S02', 'PARA-0001', 2, 'This policy have several advantage for both workers and customer.', 'This policy has several advantages for both workers and customers.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0001-S03', 'PARA-0001', 3, 'First, customers can identifies employees quickly, especially when they needs help.', 'First, customers can identify employees quickly, especially when they need help.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0001-S04', 'PARA-0001', 4, 'Second, a uniform can reduces how much money staff spend for work clothes.', 'Second, a uniform can reduce how much money staff spend on work clothes.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0001-S05', 'PARA-0001', 5, 'However, some employee feels uncomfortable because the same design do not suit everyone.', 'However, some employees feel uncomfortable because the same design does not suit everyone.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0001-S06', 'PARA-0001', 6, 'Uniforms may also makes workers feel that they has less personal freedom.', 'Uniforms may also make workers feel that they have less personal freedom.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0001-S07', 'PARA-0001', 7, 'In my opinion, companies should provides suitable uniforms and allows employees to choose between several styles, so the policy can remain professional without caused unnecessary discomfort at work.', 'In my opinion, companies should provide suitable uniforms and allow employees to choose between several styles, so the policy can remain professional without causing unnecessary discomfort at work.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0002-S01', 'PARA-0002', 1, 'Last summer, my family travelled to Japan for visit several cities.', 'Last summer, my family travelled to Japan to visit several cities.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0002-S02', 'PARA-0002', 2, 'We stayed in a hotel which was located near from the railway station, so travelling was very convenience.', 'We stayed in a hotel which was located near the railway station, so travelling was very convenient.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0002-S03', 'PARA-0002', 3, 'On the first day, we collected many informations from a tourist centre and asked the staff where should we go.', 'On the first day, we collected much information from a tourist centre and asked the staff where we should go.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0002-S04', 'PARA-0002', 4, 'They suggested us to visit an ancient temple that built over five hundred years ago.', 'They suggested that we visit an ancient temple that was built over five hundred years ago.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0002-S05', 'PARA-0002', 5, 'Although the weather was heavily raining, the temple was more beautiful than I expected.', 'Although it was raining heavily, the temple was more beautiful than I expected.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0002-S06', 'PARA-0002', 6, 'If we had brought an umbrella, we would not got wet.', 'If we had brought an umbrella, we would not have got wet.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_sentences (corpus_version, sentence_id, paragraph_id, sentence_order, incorrect_sentence, corrected_sentence, review_policy, status)
select '2026-08-01.1', 'PARA-0002-S07', 'PARA-0002', 7, 'Overall, the journey gave us many memory and broaden our knowledge.', 'Overall, the journey gave us many memories and broadened our knowledge.', 'exact', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;

insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I001', 'I001', 'PARA-0001-S01', 1, 'company', 'companies', 1, 'MANY_PLURAL_NOUN', 'many 後面的可數名詞通常要用複數，所以寫 companies。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I002', 'I002', 'PARA-0001-S01', 2, 'requires', 'require', 1, 'PLURAL_SUBJECT_VERB', 'companies 是複數主語，現在式動詞用 require，不加 s。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I003', 'I003', 'PARA-0001-S01', 3, 'staffs', 'staff', 1, 'STAFF_COLLECTIVE_NOUN', 'staff 通常是集合名詞。可寫 staff 或 staff members，一般不寫 staffs。', '["staff members"]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I004', 'I004', 'PARA-0001-S01', 4, 'wears', 'wear', 1, 'TO_BASE_VERB', 'to 後面使用動詞原形，所以是 to wear。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I005', 'I005', 'PARA-0001-S02', 1, 'have', 'has', 1, 'SINGULAR_SUBJECT_VERB', 'policy 是第三身單數，所以使用 has。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I006', 'I006', 'PARA-0001-S02', 2, 'advantage', 'advantages', 1, 'SEVERAL_PLURAL_NOUN', 'several 後面要接可數名詞複數，所以是 advantages。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I007', 'I007', 'PARA-0001-S02', 3, 'customer', 'customers', 1, 'GENERAL_GROUP_PLURAL', '這裡泛指顧客這個群體，所以使用 customers。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I008', 'I008', 'PARA-0001-S03', 1, 'identifies', 'identify', 1, 'MODAL_BASE_VERB', 'can 後面使用動詞原形，所以是 can identify。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I009', 'I009', 'PARA-0001-S03', 2, 'needs', 'need', 1, 'PLURAL_SUBJECT_VERB', 'they 是複數主語，所以使用 need，不加 s。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I010', 'I010', 'PARA-0001-S04', 1, 'reduces', 'reduce', 1, 'MODAL_BASE_VERB', 'can 後面使用動詞原形，所以是 can reduce。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I011', 'I011', 'PARA-0001-S04', 2, 'spend for', 'spend on', 1, 'SPEND_MONEY_ON', '表示「花錢在某事上」使用 spend money on something。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I012', 'I012', 'PARA-0001-S05', 1, 'employee', 'employees', 1, 'GENERAL_SOME_PLURAL', '這裡泛指部分員工，所以使用 some employees。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I013', 'I013', 'PARA-0001-S05', 2, 'feels', 'feel', 1, 'PLURAL_SUBJECT_VERB', 'employees 是複數，因此使用 feel。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I014', 'I014', 'PARA-0001-S05', 3, 'do', 'does', 1, 'SINGULAR_SUBJECT_VERB', 'design 是第三身單數，因此使用 does not。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I015', 'I015', 'PARA-0001-S06', 1, 'makes', 'make', 1, 'MODAL_BASE_VERB', 'may 後面使用動詞原形，所以是 may make。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I016', 'I016', 'PARA-0001-S06', 2, 'has', 'have', 1, 'PLURAL_SUBJECT_VERB', 'they 是複數主語，因此使用 have。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I017', 'I017', 'PARA-0001-S07', 1, 'provides', 'provide', 1, 'MODAL_BASE_VERB', 'should 後面使用動詞原形，所以是 should provide。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I018', 'I018', 'PARA-0001-S07', 2, 'allows', 'allow', 1, 'SHARED_MODAL_PARALLEL', 'should 同時控制 provide 和 allow，兩個動詞都要使用原形。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0001-I019', 'I019', 'PARA-0001-S07', 3, 'caused', 'causing', 1, 'PREPOSITION_GERUND', 'without 是介詞，後面的動作通常使用動名詞，所以是 without causing。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0002-I001', 'I001', 'PARA-0002-S01', 1, 'for visit', 'to visit', 1, 'PURPOSE_TO_INFINITIVE', '表示「前往日本是為了參觀城市」，通常使用 to + 動詞原形 表達目的，所以寫 to visit。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0002-I002', 'I002', 'PARA-0002-S02', 1, 'near from', 'near', 1, 'NEAR_PREPOSITION', 'near 可以直接接地方，所以寫 near the railway station。也可以寫 close to the railway station。', '["close to"]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0002-I003', 'I003', 'PARA-0002-S02', 2, 'convenience', 'convenient', 1, 'ADJECTIVE_AFTER_BE', 'convenience 是名詞；這裡放在 was very 後面，需要形容詞 convenient。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0002-I004', 'I004', 'PARA-0002-S03', 1, 'many informations', 'much information', 1, 'INFORMATION_UNCOUNTABLE', 'information 在一般英文中是不可數名詞，不能寫 informations。可以寫 much information、a lot of information 或 several pieces of information。', '["a lot of information","several pieces of information"]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0002-I005', 'I005', 'PARA-0002-S03', 2, 'where should we go', 'where we should go', 1, 'INDIRECT_QUESTION_ORDER', '這是放在 asked 後面的間接問句，使用陳述句語序：where + 主語 + 動詞。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0002-I006', 'I006', 'PARA-0002-S04', 1, 'suggested us to visit', 'suggested that we visit', 1, 'SUGGEST_CONSTRUCTION', 'suggest 通常使用 suggest that + 主語 + 動詞，或者 suggest + verb-ing。不要直接寫 suggest someone to do。', '["suggested visiting"]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0002-I007', 'I007', 'PARA-0002-S04', 2, 'that built', 'that was built', 1, 'PASSIVE_RELATIVE_CLAUSE', '寺廟是「被建造」，所以需要被動語態 was built。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0002-I008', 'I008', 'PARA-0002-S05', 1, 'the weather', 'it', 1, 'RAIN_IT_CONSTRUCTION', '描述正在下雨時，最自然的主語通常是形式主語 it：It was raining.', '["the weather was rainy"]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0002-I009', 'I009', 'PARA-0002-S05', 2, 'heavily raining', 'raining heavily', 1, 'ADVERB_POSITION', 'heavily 修飾下雨的程度，通常放在 raining 後面：raining heavily。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0002-I010', 'I010', 'PARA-0002-S06', 1, 'would not got', 'would not have got', 1, 'THIRD_CONDITIONAL_RESULT', '前面使用 If + had + 過去分詞，結果部分通常使用 would have + 過去分詞。', '["would not have gotten"]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0002-I011', 'I011', 'PARA-0002-S07', 1, 'many memory', 'many memories', 1, 'MANY_PLURAL_NOUN', 'many 後面接可數名詞複數，所以寫 many memories。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_issues (corpus_version, issue_id, source_issue_id, sentence_id, issue_order, wrong_text, replacement_text, occurrence_index, rule_id, explanation_zh_hant, acceptable_alternatives, confidence, status)
select '2026-08-01.1', 'PARA-0002-I012', 'I012', 'PARA-0002-S07', 2, 'broaden', 'broadened', 1, 'PAST_TENSE_PARALLEL', '整段描述去年的旅程；gave 和 broadened 是兩個並列的過去式動作。', '[]'::jsonb, 1, 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;

insert into public.writing_grammar_rule_exceptions (corpus_version, exception_id, rule_id, exception_order, condition_en, example_text, explanation_zh_hant, english_variant, status)
select '2026-08-01.1', 'EX-PURPOSE_TO_INFINITIVE-01', 'PURPOSE_TO_INFINITIVE', 1, 'for + verb-ing can describe the intended use of an object.', 'This bag is for carrying books.', 'for + verb-ing 可以表示物件的用途。這不等於「某人做某事的目的」。', 'both', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rule_exceptions (corpus_version, exception_id, rule_id, exception_order, condition_en, example_text, explanation_zh_hant, english_variant, status)
select '2026-08-01.1', 'EX-NEAR_PREPOSITION-01', 'NEAR_PREPOSITION', 1, 'near to is valid in some abstract or formal contexts.', 'The negotiations were near to completion.', 'near to 在部分語境可以成立，因此系統不應一律刪除 to。near from 才是本例的問題。', 'both', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rule_exceptions (corpus_version, exception_id, rule_id, exception_order, condition_en, example_text, explanation_zh_hant, english_variant, status)
select '2026-08-01.1', 'EX-ADJECTIVE_AFTER_BE-01', 'ADJECTIVE_AFTER_BE', 1, 'The noun convenience is grammatical when the syntax requires a noun.', 'We travelled for convenience.', 'convenience 作名詞時完全正確；本例錯在 was very convenience 需要形容詞。', 'both', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rule_exceptions (corpus_version, exception_id, rule_id, exception_order, condition_en, example_text, explanation_zh_hant, english_variant, status)
select '2026-08-01.1', 'EX-INFORMATION_UNCOUNTABLE-01', 'INFORMATION_UNCOUNTABLE', 1, 'Information can be counted with a unit expression.', 'We received three pieces of information.', '需要計算資料數量時，可以使用 pieces/items of information。', 'both', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rule_exceptions (corpus_version, exception_id, rule_id, exception_order, condition_en, example_text, explanation_zh_hant, english_variant, status)
select '2026-08-01.1', 'EX-INDIRECT_QUESTION_ORDER-01', 'INDIRECT_QUESTION_ORDER', 1, 'A directly quoted question retains question word order.', 'She asked, “Where should we go?”', '直接引述問題時使用疑問句語序；只有間接問句使用 where we should go。', 'both', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rule_exceptions (corpus_version, exception_id, rule_id, exception_order, condition_en, example_text, explanation_zh_hant, english_variant, status)
select '2026-08-01.1', 'EX-SUGGEST_CONSTRUCTION-01', 'SUGGEST_CONSTRUCTION', 1, 'suggest + verb-ing is a valid construction.', 'They suggested visiting the temple.', 'suggest + verb-ing 是正確結構。', 'both', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rule_exceptions (corpus_version, exception_id, rule_id, exception_order, condition_en, example_text, explanation_zh_hant, english_variant, status)
select '2026-08-01.1', 'EX-SUGGEST_CONSTRUCTION-02', 'SUGGEST_CONSTRUCTION', 2, 'suggest to someone that... is valid when to introduces the recipient.', 'They suggested to us that we visit the temple.', 'suggest to someone that... 可以成立，但不能寫 suggest someone to do。', 'both', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rule_exceptions (corpus_version, exception_id, rule_id, exception_order, condition_en, example_text, explanation_zh_hant, english_variant, status)
select '2026-08-01.1', 'EX-PASSIVE_RELATIVE_CLAUSE-01', 'PASSIVE_RELATIVE_CLAUSE', 1, 'Use the active voice when the relative-clause subject performs the action.', 'We met the workers who built the temple.', 'workers 主動建造寺廟，所以使用主動式 built，不需要 were built。', 'both', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rule_exceptions (corpus_version, exception_id, rule_id, exception_order, condition_en, example_text, explanation_zh_hant, english_variant, status)
select '2026-08-01.1', 'EX-RAIN_IT_CONSTRUCTION-01', 'RAIN_IT_CONSTRUCTION', 1, 'The weather can be the subject when rainy is an adjective.', 'The weather was rainy.', '使用形容詞 rainy 時，可以用 the weather 作主語。', 'both', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rule_exceptions (corpus_version, exception_id, rule_id, exception_order, condition_en, example_text, explanation_zh_hant, english_variant, status)
select '2026-08-01.1', 'EX-THIRD_CONDITIONAL_RESULT-01', 'THIRD_CONDITIONAL_RESULT', 1, 'A mixed conditional can combine a past condition with a present result.', 'If I had studied medicine, I would be a doctor now.', '這是混合條件句：過去條件造成現在結果，因此可以使用 would be。', 'both', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rule_exceptions (corpus_version, exception_id, rule_id, exception_order, condition_en, example_text, explanation_zh_hant, english_variant, status)
select '2026-08-01.1', 'EX-THIRD_CONDITIONAL_RESULT-02', 'THIRD_CONDITIONAL_RESULT', 2, 'American English commonly uses gotten as the past participle of get.', 'If we had brought an umbrella, we would not have gotten wet.', 'gotten 是常見美式英文；got 是本例採用的英式英文。', 'American English', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rule_exceptions (corpus_version, exception_id, rule_id, exception_order, condition_en, example_text, explanation_zh_hant, english_variant, status)
select '2026-08-01.1', 'EX-MANY_PLURAL_NOUN-01', 'MANY_PLURAL_NOUN', 1, 'The formal many a construction takes a singular noun and singular verb.', 'Many a traveller has made this mistake.', '正式結構 many a + 單數名詞 + 單數動詞 是例外。', 'both', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;
insert into public.writing_grammar_rule_exceptions (corpus_version, exception_id, rule_id, exception_order, condition_en, example_text, explanation_zh_hant, english_variant, status)
select '2026-08-01.1', 'EX-PAST_TENSE_PARALLEL-01', 'PAST_TENSE_PARALLEL', 1, 'A modal changes the required form of the following verb.', 'The journey may broaden our knowledge.', '情態動詞 may 後面使用動詞原形，所以這裡的 broaden 正確。', 'both', 'approved'
where exists (select 1 from public.writing_grammar_corpus_releases where corpus_version = '2026-08-01.1' and status = 'reviewed') on conflict do nothing;

do $$
begin
  if (select count(*) from public.writing_grammar_corpus_groups where corpus_version = '2026-08-01.1') <> 2
    or (select count(*) from public.writing_grammar_paragraphs where corpus_version = '2026-08-01.1') <> 2
    or (select count(*) from public.writing_grammar_sentences where corpus_version = '2026-08-01.1') <> 14
    or (select count(*) from public.writing_grammar_issues where corpus_version = '2026-08-01.1') <> 31
    or (select count(*) from public.writing_grammar_rules where corpus_version = '2026-08-01.1') <> 23
    or (select count(*) from public.writing_grammar_rule_exceptions where corpus_version = '2026-08-01.1') <> 13
  then
    raise exception 'Corpus seed counts do not match the approved release';
  end if;
end;
$$;

update public.writing_grammar_corpus_releases set status = 'approved', is_current = true, approved_at = '2026-08-01T00:00:00.000Z'::timestamptz where corpus_version = '2026-08-01.1' and status = 'reviewed';
update public.writing_grammar_corpus_releases set is_current = true where corpus_version = '2026-08-01.1' and status = 'approved' and not is_current;

commit;
