import {steps,questions,questionMap,correct,completed,latestRun,daily,hkDate,esc} from './scoop.mjs?v=20260917-1';
import {mountRecorder} from './recording.mjs?v=20260917-1';
const $=s=>document.querySelector(s);let client,user=null,events=[],outbox=[],timeDays=[],inputs={},run=null,index=0,generation=0,syncing=null,ready=false,cleanup=()=>{},feedback={},seconds=0,lastTick=Date.now(),lastAction=Date.now(),storageFailed=false;
const cacheKey=()=>`edmund-natural-english-v1:${user.id}`;
const unique=xs=>[...new Map(xs.map(e=>[e.id,e])).values()];
const status=(text,error=false)=>{$('[data-sync]').textContent=text;$('[data-retry]').hidden=!error;};
function persist(){if(!user)return;try{localStorage.setItem(cacheKey(),JSON.stringify({events,outbox,timeDays,inputs}));}catch{storageFailed=true;status('本機儲存不可用，請保持連線並等候帳戶儲存。',true);}}
async function rpc(name,args){if(!client){const c=window.EDMUND_SUPABASE;if(!window.supabase||!c)throw Error('登入服務未能載入，請重新整理。');client=window.supabase.createClient(c.url,c.anonKey,{auth:{persistSession:true,storage:sessionStorage,autoRefreshToken:true,detectSessionInUrl:false}});}const s=await client.auth.getSession();if(s.error)throw s.error;if(!s.data?.session){const a=await client.auth.signInAnonymously();if(a.error)throw a.error;}const {data,error}=await client.rpc(name,args).abortSignal(AbortSignal.timeout(15000));if(error)throw error;return data;}
function add(data){if(!user)return;const e={id:crypto.randomUUID(),at:new Date().toISOString(),...data};outbox.push(e);if(e.kind!=='time')events.push(e);persist();void sync();return e;}
async function sync(){if(!user||syncing)return syncing;const owner=user.id,token=user.token,gen=generation;const task=(async()=>{try{do{const batch=outbox.slice(0,100),ids=new Set(batch.map(e=>e.id));status('正在儲存…');const data=await rpc('natural_english_sync',{p_token:token,p_events:batch});if(gen!==generation||user?.id!==owner)return false;outbox=outbox.filter(e=>!ids.has(e.id));events=unique([...(data.events||[]),...outbox.filter(e=>e.kind!=='time')]);timeDays=data.timeDays||[];persist();progress();charts();}while(outbox.length);status(storageFailed?'已儲存至學生帳戶；本機儲存不可用。':'已儲存至學生帳戶');return true;}catch(e){if(gen===generation)status(/expired|session|Sign in/i.test(e.message||'')?'登入已過期，請重新登入。未同步進度保留於此裝置。':storageFailed?'未能連線，且本機儲存不可用。請保持此頁開啟並重試。':'暫時未能連線，進度保留於此裝置，恢復連線後會再同步。',true);return false;}})();syncing=task;const ok=await task;if(gen===generation)syncing=null;return ok;}
const seen=sense=>events.some(e=>e.kind==='view'&&e.sense===sense);
function view(sense){if(!seen(sense))add({kind:'view',sense});}
function recorded(slot){return seen('recorded:'+run+':'+slot);}
function skipped(slot){return seen('skipped:'+run+':'+slot);}
function stepDone(s){const done=completed(events,run);return s.questions.every(q=>done.has(q))&&(!s.recording||recorded(s.recording)||skipped(s.recording));}
function progress(){if(!user||!run)return;const done=completed(events,run);$('[data-count]').textContent=`本次已答對 ${done.size} / ${questions.length} 題`;$('[data-progress]').value=done.size;$('[data-speaking-count]').textContent=`口說 ${['phrase','dialogue'].filter(recorded).length} / 2 項已練習（選做）`;$('[data-steps]').innerHTML=steps.map((s,i)=>`<button data-step="${i}" ${i===index?'aria-current="step"':''}><span>${stepDone(s)?'✓':String(i+1).padStart(2,'0')}</span>${s.label}</button>`).join('');const next=$('[data-next]');if(next)next.disabled=!stepDone(steps[index]);}
function questionHtml(q){const done=completed(events,run).has(q.id),f=feedback[q.id],value=inputs[run+':'+q.id]||'';return `<article class="question" data-question="${q.id}"><h3>${esc(q.prompt)}</h3>${q.type==='mc'?`<div class="choices">${q.options.map((option,i)=>`<button data-choice="${i}" data-q="${q.id}" ${done?'disabled':''} class="${done&&correct(q,option)?'correct':f?.choice===option&&!f.correct?'wrong':''}"><span>${String.fromCharCode(65+i)}</span>${esc(option)}</button>`).join('')}</div>`:`<form data-blank="${q.id}"><label><span lang="en">${esc(q.before)}</span><input name="answer" value="${esc(value)}" aria-label="${esc(q.prompt)}" autocomplete="off" autocapitalize="none" spellcheck="false" maxlength="160" ${done?'disabled':''} required><span lang="en">${esc(q.after)}</span></label><div class="blank-actions"><button class="primary" ${done?'disabled':''}>${done?'✓ 已答對':'檢查答案'}</button><button type="button" data-hint="${q.id}">給我提示</button></div><p data-hint-text hidden>${esc(q.hint)}</p></form>`}${done||f?`<div class="feedback ${done?'good':''}" role="status"><strong>${done?'✓ 答對了！':'再想一下，你可以再試。'}</strong><p>${esc(q.explanation)}</p>${done?'':`<small>正確表達：${esc(q.answers[0])}</small>`}</div>`:''}</article>`;}
function audioHtml(s){return s.model?`<section class="model"><p class="eyebrow">聽一聽 · 再自己說</p><p class="model-sentence" lang="en">${esc(s.model)}</p><div class="audio-actions"><button data-say="${esc(s.model)}">🔊 聽示範</button><button data-say="${esc(s.model)}" data-slow>慢速播放</button><button data-translation>顯示／隱藏中文</button></div><p data-zh hidden>${esc(s.zh)}</p><small>使用裝置的英文朗讀聲音。</small><p data-audio-status role="status"></p></section>`:'';}
function render(){cleanup();cleanup=()=>{};window.speechSynthesis?.cancel();const s=steps[index],done=completed(events,run);$('[data-stage]').innerHTML=`<div class="stage-heading"><p class="eyebrow">SCOOP / 第 ${index+1} 步，共 ${steps.length} 步</p><h2 tabindex="-1">${s.title}</h2><p>${s.intro}</p></div>${s.sentence?`<div class="surprise"><span>你可能會這樣說…</span><p lang="en">Can I get two <mark>balls</mark> of ice cream, please?</p></div>`:''}${s.id==='surprise'?'':audioHtml(s)}${s.questions.map(id=>questionHtml(questionMap.get(id))).join('')}${s.id==='surprise'&&(done.has('spot')||feedback.spot)?`<aside class="reveal"><h3>💡 原來不是 balls！</h3><p>${s.reveal}</p><div class="scoop-pairs"><span>一球 <b>one scoop</b></span><span>兩球 <b>two scoops</b></span><span>三球 <b>three scoops</b></span></div>${audioHtml(s)}</aside>`:''}${s.recording?`<section class="recorder" data-recorder></section><p class="record-badge" data-record-badge>${recorded(s.recording)?'✓ 口說已練習':skipped(s.recording)?'已跳過，可隨時回來練習':'口說選做，不計入答對題數'}</p>`:''}<nav class="stage-nav"><button data-prev ${index===0?'disabled':''}>上一步</button><span>${stepDone(s)?'✓ 這一步已完成':s.recording?'完成題目後，錄音或選擇跳過即可繼續':'答對本頁題目後繼續；答錯可以再試。'}</span><button class="primary" data-next ${stepDone(s)?'':'disabled'}>${index===steps.length-1?'查看學習成果':'下一步'}</button></nav>`;
 if(s.recording){const owner=user.id,currentRun=run;cleanup=mountRecorder($('[data-recorder]'),{key:owner+':'+run+':'+s.recording,onRecorded:()=>{if(user?.id!==owner||run!==currentRun)return;view('recorded:'+run+':'+s.recording);$('[data-record-badge]').textContent='✓ 口說已練習';progress();},onSkip:()=>{if(user?.id!==owner||run!==currentRun)return;view('skipped:'+run+':'+s.recording);$('[data-record-badge]').textContent=recorded(s.recording)?'✓ 口說已練習':'已跳過，可隨時回來練習';progress();}});}
 progress();}
function answer(id,choice){const q=questionMap.get(id);if(!ready||!q||completed(events,run).has(id))return;const round=1+Math.max(0,...events.filter(e=>e.kind==='answer'&&e.run===run&&e.question===id).map(e=>e.round));feedback[id]={choice,correct:correct(q,choice)};add({kind:'answer',run,round,question:id,choice});render();$(`[data-question="${id}"] .feedback`)?.scrollIntoView({block:'nearest',behavior:'smooth'});}
function finish(){if(!steps.every(stepDone)){index=steps.findIndex(s=>!stepDone(s));render();return;}cleanup();$('[data-stage]').innerHTML=`<section class="finish"><span class="finish-icon">✓</span><p class="eyebrow">SCOOP / 本課完成</p><h2>你可以自己點一份冰淇淋了！</h2><p>${questions.length} / ${questions.length} 題已答對。口說 ${['phrase','dialogue'].filter(recorded).length} / 2 項已練習（選做）。</p><p>今天帶走三個實用表達：</p>${['Two scoops, please.','Can I get two scoops of vanilla ice cream, please?','In a cup, please.'].map(t=>`<button class="takeaway" data-say="${t}">🔊 ${t}</button>`).join('')}<p data-audio-status role="status"></p><div class="finish-actions"><button data-step="0">回顧本課</button><button class="primary" data-redo>再練一次</button><a href="index.html">返回首頁</a></div></section>`;}
function timeMap(){const map=new Map(timeDays.map(d=>[d.date,Number(d.seconds)]));for(const e of outbox.filter(e=>e.kind==='time'))map.set(hkDate(e.at),(map.get(hkDate(e.at))||0)+e.seconds);return map;}
const duration=n=>`${Math.floor(n/60)} 分 ${Math.floor(n%60)} 秒`;
function charts(){if(!user)return;const qs=daily(events),ts=timeMap(),range=$('[data-range]').value,today=hkDate(new Date());let dates=[...new Set([...qs.keys(),...ts.keys(),today])].sort();if(range!=='all'){dates=[];for(let i=Number(range)-1;i>=0;i--){const d=new Date(today+'T12:00:00+08:00');d.setUTCDate(d.getUTCDate()-i);dates.push(hkDate(d));}}$('[data-charts]').innerHTML=[['questions','答對題數',qs],['time','學習時間',ts]].map(([kind,title,map])=>{const vals=dates.map(d=>map.get(d)||0),max=Math.max(1,...vals),sum=vals.reduce((a,b)=>a+b,0);return `<article class="dashboard-card"><h3>${title}</h3><strong class="stat">${kind==='time'?duration(sum):sum+' 題'}</strong><p>${kind==='time'?'可見頁面的活躍學習時間':'每道題目在同一次練習只計一次'}</p><div class="bars">${dates.map((date,i)=>`<button data-day="${date}" data-kind="${kind}" title="${date}：${kind==='time'?duration(vals[i]):vals[i]+' 題'}" aria-label="${date}：${kind==='time'?duration(vals[i]):vals[i]+' 題'}"><svg viewBox="0 0 18 90" aria-hidden="true"><rect x="0" y="${90-Math.max(3,vals[i]/max*85)}" width="18" height="${Math.max(3,vals[i]/max*85)}" rx="4"/></svg><small>${date.slice(5)}</small></button>`).join('')}</div></article>`;}).join('');}
function detail(date,kind){const el=$('[data-day-detail]');el.hidden=false;el.innerHTML=`<h3>${esc(date)} · ${kind==='time'?'學習時間':'作答紀錄'}</h3>`+(kind==='time'?`<p>${duration(timeMap().get(date)||0)} · 包括看解釋、答題和口說練習。</p>`:`<ul>${events.filter(e=>e.kind==='answer'&&hkDate(e.at)===date&&questionMap.has(e.question)).map(e=>`<li>${correct(questionMap.get(e.question),e.choice)?'✓ 答對':'待重溫'} · ${esc(questionMap.get(e.question).prompt)}<small>你的回答：${esc(e.choice)}</small></li>`).join('')||'<li>當天沒有作答紀錄。</li>'}</ul>`);}
function capture(){if(!user||!seconds)return;const n=Math.min(60,Math.floor(seconds));seconds-=n;if(n)add({kind:'time',seconds:n});}
function startReady(){if(!user)return;run=latestRun(events);if(!run){run=crypto.randomUUID();add({kind:'start',run});}ready=true;$('[data-app]').inert=false;index=Math.max(0,steps.findIndex(s=>!stepDone(s)));render();charts();}
async function enter(token){const gen=++generation,rows=await rpc('flashcard_student_session_profile',{p_token:token});if(gen!==generation)return false;const r=rows?.[0];if(!r?.id||!r.session_token)return false;user={id:r.id,name:r.name,role:'student',token:r.session_token};events=[];outbox=[];inputs={};timeDays=[];run=null;ready=false;feedback={};seconds=0;storageFailed=false;try{const c=JSON.parse(localStorage.getItem(cacheKey())||'null');if(c&&Array.isArray(c.events)&&Array.isArray(c.outbox)){events=c.events;outbox=c.outbox;timeDays=c.timeDays||[];inputs=c.inputs||{};}}catch{}window.EdmundSystemNav?.rememberStudentSession(user);$('[data-login-form]').reset();$('[data-login]').hidden=true;$('[data-app]').hidden=false;$('[data-app]').inert=true;$('[data-logout]').hidden=false;$('[data-student]').textContent=user.name;$('[data-dashboards]').open=false;const ok=await sync();if(gen===generation&&ok)startReady();return true;}
function clear(){cleanup();window.speechSynthesis?.cancel();generation++;user=null;run=null;ready=false;syncing=null;events=[];outbox=[];seconds=0;$('[data-app]').hidden=true;$('[data-login]').hidden=false;$('[data-logout]').hidden=true;$('[data-student]').textContent='';}
$('[data-login-form]').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('[type=submit]'),f=new FormData(e.currentTarget);b.disabled=true;$('[data-login-status]').textContent='正在登入…';try{const rows=await rpc('flashcard_student_login',{p_name:String(f.get('username')).trim(),p_password:String(f.get('password'))});if(!rows?.[0]?.session_token||!await enter(rows[0].session_token))throw Error('用戶名稱或密碼不正確。請使用功課及溫習安排的學生帳戶。');$('[data-login-status]').textContent='';}catch(err){$('[data-login-status]').textContent=err.message||'登入失敗，請重試。';}finally{b.disabled=false;}};
$('[data-logout]').onclick=async()=>{capture();cleanup();await sync();clear();window.EdmundSystemNav?.forgetStudentSession();};
$('[data-retry]').onclick=async()=>{if(await sync()&&!ready)startReady();};
$('[data-range]').onchange=()=>{charts();$('[data-day-detail]').hidden=true;};
document.addEventListener('submit',e=>{if(e.target.matches('[data-blank]')){e.preventDefault();answer(e.target.dataset.blank,new FormData(e.target).get('answer'));}});
document.addEventListener('input',e=>{const f=e.target.closest('[data-blank]');if(user&&f){inputs[run+':'+f.dataset.blank]=e.target.value;persist();}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!user||!ready)return;if(b.dataset.step!==undefined){capture();index=Number(b.dataset.step);render();$('[data-stage] h2').focus();}else if(b.hasAttribute('data-prev')){capture();index--;render();}else if(b.hasAttribute('data-next')){capture();if(index===steps.length-1)finish();else{index++;render();}$('[data-stage] h2')?.focus();}else if(b.dataset.q)answer(b.dataset.q,questionMap.get(b.dataset.q).options[Number(b.dataset.choice)]);else if(b.dataset.hint)$(`[data-question="${b.dataset.hint}"] [data-hint-text]`).hidden=false;else if(b.hasAttribute('data-translation')){const p=b.closest('.model').querySelector('[data-zh]');p.hidden=!p.hidden;}else if(b.dataset.say){const label=b.closest('.model,.finish')?.querySelector('[data-audio-status]');if(!window.speechSynthesis){if(label)label.textContent='此裝置暫不支援朗讀，請參考上方文字。';return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(b.dataset.say);u.lang='en-US';u.rate=b.hasAttribute('data-slow')?.75:1;u.voice=speechSynthesis.getVoices().find(v=>v.lang==='en-US')||null;u.onerror=()=>{if(label)label.textContent='未能播放，請再按一次或檢查裝置音量。';};speechSynthesis.speak(u);}else if(b.dataset.day)detail(b.dataset.day,b.dataset.kind);else if(b.hasAttribute('data-redo')&&confirm('開始新一次練習？之前的紀錄會保留。')){run=crypto.randomUUID();feedback={};index=0;add({kind:'start',run});render();}});
['pointerdown','keydown'].forEach(n=>document.addEventListener(n,()=>lastAction=Date.now(),{passive:true}));
setInterval(()=>{const now=Date.now(),elapsed=Math.min(2,Math.max(0,(now-lastTick)/1000));lastTick=now;if(user&&ready&&!document.hidden&&now-lastAction<600000){seconds+=elapsed;if(seconds>=30)capture();}},1000);
setInterval(()=>{if(user&&!document.hidden)void sync();},60000);
document.addEventListener('visibilitychange',()=>{capture();if(document.hidden){cleanup();window.speechSynthesis?.cancel();}else{lastAction=Date.now();lastTick=Date.now();if(user&&ready)render();void sync();}});
window.addEventListener('online',async()=>{if(await sync()&&user&&!ready)startReady();});window.addEventListener('pagehide',()=>{capture();persist();cleanup();window.speechSynthesis?.cancel();});
window.addEventListener('edmund-student-session-change',()=>{if(user&&window.EdmundSystemNav?.getStudentSession?.()?.id!==user.id){capture();persist();clear();}});
(async()=>{const s=window.EdmundSystemNav?.getStudentSession?.();if(s?.role==='student'&&s.token){try{if(await enter(s.token))return;}catch{}clear();$('[data-login-status]').textContent='請重新登入以繼續。';}})();

window.addEventListener('pageshow',e=>{if(e.persisted&&user&&ready){lastAction=Date.now();lastTick=Date.now();render();void sync();}});
