#!/usr/bin/env python3
"""Build and validate the IELTS Speaking Part 1 browser payload."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any


SOURCE_NAME = "ielts-speaking-part1-book1-structured.json"
OUTPUT_NAME = "speaking-system-part1-data.js"
EXPECTED_QUESTION_COUNT = 9
WORD_PATTERN = re.compile(r"\b[A-Za-z]+(?:[’'][A-Za-z]+)*(?:-[A-Za-z]+)*\b")


def clean_text(value: object, where: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{where} must be a non-empty string")
    if value != value.strip() or re.search(r"\s{2,}", value):
        raise ValueError(f"{where} contains unexpected whitespace")
    return value


def source_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_payload(source_path: Path) -> dict[str, Any]:
    payload = json.loads(source_path.read_text(encoding="utf-8"))
    expected_header = {
        "schema_version": 1,
        "exam": "IELTS",
        "part": 1,
        "book": 1,
        "module_count": 1,
    }
    if not isinstance(payload, dict):
        raise ValueError("Part 1 source must be an object")
    for key, expected in expected_header.items():
        if payload.get(key) != expected:
            raise ValueError(f"Part 1 source {key} must be {expected!r}")

    modules = payload.get("modules")
    if not isinstance(modules, list) or len(modules) != 1:
        raise ValueError("Part 1 Book 1 must contain exactly one pilot module")

    source_module = modules[0]
    if not isinstance(source_module, dict):
        raise ValueError("Part 1 module must be an object")
    if source_module.get("id") != "ielts-part-1-book-1-accommodation":
        raise ValueError("Part 1 pilot module id is not stable")
    if source_module.get("index") != 1:
        raise ValueError("Part 1 pilot module index must be 1")
    title = clean_text(source_module.get("title"), "module title")
    title_zh = clean_text(source_module.get("title_zh"), "module Chinese title")
    questions = source_module.get("questions")
    if not isinstance(questions, list) or len(questions) != EXPECTED_QUESTION_COUNT:
        raise ValueError(f"Accommodation must contain {EXPECTED_QUESTION_COUNT} questions")
    if source_module.get("question_count") != len(questions):
        raise ValueError("module question_count does not match the questions array")

    normalized_questions: list[dict[str, object]] = []
    english_word_count = 0
    for expected_number, question in enumerate(questions, start=1):
        where = f"question {expected_number}"
        if not isinstance(question, dict) or question.get("number") != expected_number:
            raise ValueError(f"{where} is invalid or out of order")
        question_en = clean_text(question.get("question_en"), f"{where} English")
        question_zh = clean_text(question.get("question_zh"), f"{where} Chinese")
        answer_en = clean_text(question.get("answer_en"), f"{where} answer English")
        answer_zh = clean_text(question.get("answer_zh"), f"{where} answer Chinese")
        english_word_count += len(WORD_PATTERN.findall(question_en))
        english_word_count += len(WORD_PATTERN.findall(answer_en))
        normalized_questions.append({
            "number": expected_number,
            "questionEn": question_en,
            "questionZh": question_zh,
            "answerEn": answer_en,
            "answerZh": answer_zh,
        })

    return {
        "metadata": {
            "schemaVersion": 1,
            "exam": "IELTS",
            "part": 1,
            "bookCount": 1,
            "moduleCount": 1,
            "questionCount": len(normalized_questions),
            "turnCount": len(normalized_questions) * 2,
            "englishWordCount": english_word_count,
            "audioBuildVersion": "v1",
            "sourceSha256": source_sha256(source_path),
        },
        "books": [{
            "part": 1,
            "book": 1,
            "displayTitle": "Book 1 of Part 1",
            "exerciseCount": 1,
            "exercises": [{
                "id": source_module["id"],
                "index": 1,
                "title": title,
                "titleZh": title_zh,
                "questionCount": len(normalized_questions),
                "questions": normalized_questions,
            }],
        }],
    }


def browser_source(payload: dict[str, Any]) -> str:
    return (
        "/* Generated by tools/build-speaking-part1-data.py; do not edit by hand. */\n"
        "window.EDMUND_SPEAKING_PART1_DATA = Object.freeze("
        f"{json.dumps(payload, ensure_ascii=False, indent=2)}"
        ");\n"
    )


def parse_args() -> argparse.Namespace:
    repository_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=repository_root / "tools" / SOURCE_NAME)
    parser.add_argument("--output", type=Path, default=repository_root / OUTPUT_NAME)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    source_path = args.source.resolve()
    output_path = args.output.resolve()
    payload = load_payload(source_path)
    expected = browser_source(payload)
    if args.check:
        if not output_path.is_file() or output_path.read_text(encoding="utf-8") != expected:
            raise SystemExit("Part 1 browser data is missing or stale")
        print(
            f"Part 1 browser data valid: {payload['metadata']['moduleCount']} module, "
            f"{payload['metadata']['questionCount']} questions, "
            f"{payload['metadata']['englishWordCount']} English words."
        )
        return 0
    output_path.write_text(expected, encoding="utf-8")
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
