#!/usr/bin/env python3
"""Build the 238-row Edmund's Progression browser data from the supplied PDF."""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path

from pypdf import PdfReader


TYPE_TO_CATEGORY = {
    "Opinion": "opinion",
    "Discuss Both Views and Give Your Opinion": "discuss-both-views",
    "Cause and Solution": "cause-solution",
    "Advantages and Disadvantages": "advantage-disadvantage",
    "Direct Questions": "direct-question",
}

EXPECTED_COUNTS = {
    "advantage-disadvantage": 29,
    "opinion": 104,
    "discuss-both-views": 40,
    "cause-solution": 19,
    "direct-question": 46,
}

ROW_PATTERN = re.compile(
    r"^\s*(?P<number>\d{1,3})\s{2,}(?P<type>.+? - Q(?P<question>\d+))\s{2,}(?P<topic>\S.*?)\s*$"
)
QUESTION_DATA_PATTERN = re.compile(
    r"window\.EDMUND_MODEL_ESSAY_QUESTION_DATA=Object\.freeze\((\{.*\})\);\s*$",
    re.DOTALL,
)


def extract_rows(pdf_path: Path) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for page in PdfReader(str(pdf_path)).pages:
        text = page.extract_text(extraction_mode="layout") or ""
        for line in text.splitlines():
            match = ROW_PATTERN.match(line)
            if not match:
                continue
            number = int(match.group("number"))
            printed_type = match.group("type")
            type_label = printed_type.rsplit(" - Q", 1)[0]
            category = TYPE_TO_CATEGORY.get(type_label)
            if not category:
                raise ValueError(f"Unsupported progression type: {printed_type}")
            question_number = int(match.group("question"))
            topic = match.group("topic").strip()

            # The PDF prints Q7 twice for Cause/Solution. Its row 3 topic is the
            # released-prisoners essay, which is canonically Q5; row 48 is Q7.
            if number == 3:
                if category != "cause-solution" or question_number != 7 or "released prisoners" not in topic.lower():
                    raise ValueError("The expected row 3 PDF numbering defect changed")
                question_number = 5

            essay_key = f"{category}:{question_number}"
            rows.append(
                {
                    "number": number,
                    "type": f"{type_label} - Q{question_number}",
                    "topic": topic,
                    "essayKey": essay_key,
                }
            )
    return rows


def load_canonical_keys(question_data_path: Path) -> set[str]:
    source = question_data_path.read_text(encoding="utf-8")
    match = QUESTION_DATA_PATTERN.search(source)
    if not match:
        raise ValueError("Could not parse IELTS Task 2 question data")
    return set(json.loads(match.group(1)))


def validate(rows: list[dict[str, object]], canonical_keys: set[str]) -> None:
    if len(rows) != 238:
        raise ValueError(f"Expected 238 progression rows, found {len(rows)}")
    numbers = [int(row["number"]) for row in rows]
    if numbers != list(range(1, 239)):
        raise ValueError("Progression numbering is not exactly 1 through 238")
    keys = [str(row["essayKey"]) for row in rows]
    if len(set(keys)) != 238:
        duplicates = [key for key, count in Counter(keys).items() if count > 1]
        raise ValueError(f"Progression keys are not unique: {duplicates}")
    counts = Counter(key.rsplit(":", 1)[0] for key in keys)
    if dict(counts) != EXPECTED_COUNTS:
        raise ValueError(f"Unexpected category counts: {dict(counts)}")
    if set(keys) != canonical_keys:
        missing = sorted(canonical_keys - set(keys))
        extra = sorted(set(keys) - canonical_keys)
        raise ValueError(f"Progression does not match canonical inventory; missing={missing}, extra={extra}")
    if rows[2]["essayKey"] != "cause-solution:5" or rows[47]["essayKey"] != "cause-solution:7":
        raise ValueError("Cause/Solution Q5/Q7 reconciliation failed")
    if rows[170]["essayKey"] != "discuss-both-views:20" or rows[237]["essayKey"] != "discuss-both-views:41":
        raise ValueError("The two canonical car-free-day entries were not preserved")


def write_browser_data(rows: list[dict[str, object]], output_path: Path) -> None:
    payload = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
    output_path.write_text(
        "// Generated by tools/build-writing-progression-data.py from Edmund's Progression List.pdf\n"
        f"window.EDMUND_WRITING_PROGRESSION=Object.freeze({payload}.map((row)=>Object.freeze(row)));\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("pdf", type=Path)
    parser.add_argument("--output", type=Path, default=Path("writing-progression-data.js"))
    parser.add_argument("--questions", type=Path, default=Path("ielts-task2-question-data.js"))
    args = parser.parse_args()
    rows = extract_rows(args.pdf)
    validate(rows, load_canonical_keys(args.questions))
    write_browser_data(rows, args.output)
    print(f"Wrote {len(rows)} progression rows to {args.output}")


if __name__ == "__main__":
    main()
