#!/usr/bin/env python3
"""Import the ordered bilingual Quote of the Day catalogue from Edmund's PDF.

The PDF is the editorial source of truth. This importer deliberately fails on
incomplete records so a broken or partially copied catalogue cannot silently be
published. The generated JavaScript is static, cacheable and does not expose a
database or storage credential to the browser.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

import pdfplumber


DEFAULT_SOURCE = Path("/Users/sammak/Downloads/Quote and Translation Database for Website.pdf")
DEFAULT_OUTPUT = Path(__file__).resolve().parents[1] / "schedule-quotes.mjs"
ROTATION_START = "2026-08-11"


@dataclass
class QuoteRecord:
    english_quote: str = ""
    english_attribution: str = ""
    chinese_quote: str = ""
    chinese_attribution: str = ""

    def complete(self) -> bool:
        return all((
            self.english_quote,
            self.english_attribution,
            self.chinese_quote,
            self.chinese_attribution,
        ))


def clean(value: str) -> str:
    """Collapse PDF line wrapping and enforce the site's ASCII apostrophe rule."""
    return " ".join(value.split()).replace("’", "'")


def parse_catalogue(source: Path) -> list[QuoteRecord]:
    records: list[QuoteRecord] = []
    current = QuoteRecord()
    field: str | None = None

    with pdfplumber.open(source) as document:
        lines: list[str] = []
        for page in document.pages:
            lines.extend((page.extract_text() or "").splitlines())

    for raw_line in lines:
        line = raw_line.strip()
        if not line:
            continue

        if line.startswith("“"):
            if current.complete():
                records.append(current)
                current = QuoteRecord()
            elif any(vars(current).values()):
                raise ValueError(f"Incomplete quote before: {line}")
            field = "english_quote"
            current.english_quote = line
        elif line.startswith("——"):
            field = "chinese_attribution"
            current.chinese_attribution = line.removeprefix("——").strip()
        elif line.startswith("—"):
            field = "english_attribution"
            current.english_attribution = line.removeprefix("—").strip()
        elif line.startswith("「"):
            field = "chinese_quote"
            current.chinese_quote = line
        elif field:
            previous = getattr(current, field)
            setattr(current, field, f"{previous} {line}")
        else:
            raise ValueError(f"Unexpected catalogue text: {line}")

    if current.complete():
        records.append(current)
    elif any(vars(current).values()):
        raise ValueError("The final quote record is incomplete")

    for record in records:
        for key, value in vars(record).items():
            setattr(record, key, clean(value))
        if not (record.english_quote.startswith("“") and record.english_quote.endswith("”")):
            raise ValueError(f"English quotation marks are incomplete: {record.english_quote}")
        if not (record.chinese_quote.startswith("「") and record.chinese_quote.endswith("」")):
            raise ValueError(f"Chinese quotation marks are incomplete: {record.chinese_quote}")

    if len(records) != 513:
        raise ValueError(f"Expected 513 complete records, found {len(records)}")
    return records


def render_module(records: list[QuoteRecord]) -> str:
    rows = [
        {
            "id": f"QUOTE-{index:04d}",
            "englishQuote": record.english_quote,
            "englishAttribution": record.english_attribution,
            "chineseQuote": record.chinese_quote,
            "chineseAttribution": record.chinese_attribution,
        }
        for index, record in enumerate(records, start=1)
    ]
    catalogue = json.dumps(rows, ensure_ascii=False, indent=2)
    return f'''// Generated by tools/import-schedule-quotes.py. Do not hand-edit.
// Editorial source: Quote and Translation Database for Website.pdf

export const SCHEDULE_QUOTE_ROTATION_START = "{ROTATION_START}";

export const SCHEDULE_QUOTES = Object.freeze({catalogue}.map((quote) => Object.freeze(quote)));

function dayNumber(dayKey) {{
  const match = /^(\\d{{4}})-(\\d{{2}})-(\\d{{2}})$/.exec(String(dayKey || ""));
  if (!match) throw new TypeError("Hong Kong day key must use YYYY-MM-DD.");
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const timestamp = Date.UTC(year, month - 1, day);
  const date = new Date(timestamp);
  if (date.getUTCFullYear() !== year || date.getUTCMonth() !== month - 1 || date.getUTCDate() !== day) {{
    throw new RangeError("Hong Kong day key is not a real calendar date.");
  }}
  return Math.floor(timestamp / 86_400_000);
}}

export function quoteIndexForHongKongDay(dayKey, rotationStart = SCHEDULE_QUOTE_ROTATION_START) {{
  if (!SCHEDULE_QUOTES.length) return -1;
  const offset = dayNumber(dayKey) - dayNumber(rotationStart);
  return ((offset % SCHEDULE_QUOTES.length) + SCHEDULE_QUOTES.length) % SCHEDULE_QUOTES.length;
}}

export function quoteForHongKongDay(dayKey, rotationStart = SCHEDULE_QUOTE_ROTATION_START) {{
  const index = quoteIndexForHongKongDay(dayKey, rotationStart);
  return index < 0 ? null : SCHEDULE_QUOTES[index];
}}
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", nargs="?", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    records = parse_catalogue(args.source)
    args.output.write_text(render_module(records), encoding="utf-8")
    print(f"Imported {len(records)} quotes into {args.output}")


if __name__ == "__main__":
    main()
