"""Source-authored 2016 Paper 3 B1 reconstruction (museum documents)."""
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent / 'layouts'
def b(en, zh): return f'<div class="bilingual"><p lang="en">{escape(en)}</p><p class="translation" lang="zh-Hant">{escape(zh)}</p></div>'
def put(n, body): (ROOT / f'2016-b1-page-{n:02}.html').write_text(body.rstrip()+'\n', encoding='utf-8')
def inp(key,label): return f'<input data-note="10-{key}" aria-label="{escape(label,quote=True)}">'

put(1,(ROOT/'2014-b1-page-01.html').read_text().replace('2014','2016'))
toc=[(3,'Listening note-taking sheet for podcast Nosing Around'),(4,'Email from Lara Gau to Indy Wong'),(5,'Article from The Hong Kong Review'),(6,'Minutes from museum staff meeting'),(7,'Email exchange between Limahl Howard and Lara Gau'),(8,'Question Wizard online survey results of museum visitors'),(8,'Lok and Partners’ interim report'),(9,'Museum Staff Manual'),(9,'Part-time student assistants’ feedback from summer 2015')]
situation=[('You are Indy Wong. You are a museum assistant for Lara Gau at the Hong Kong Social History Museum. Lara has a few things she wants you to do to help out.','你是 Indy Wong，在香港社會歷史博物館擔任 Lara Gau 的助理。Lara 有幾項工作需要你協助。'),('You will listen to an interview between Patty Leung and Dr Jack Jones for the podcast Nosing Around.','你將聆聽 Patty Leung 訪問 Jack Jones 博士的 Nosing Around 播客。'),('Before the recording is played, you will have five minutes to study the Question-Answer Book and the Data File to familiarize yourself with the situation and the tasks.','錄音播放前，你有五分鐘閱讀問答冊和資料檔，熟悉情境和任務。'),('Complete the tasks by following the instructions in the Question-Answer Book and on the recording. You will find all the information you need in the Question-Answer Book, the Data File and on the recording. As you listen you can make notes on page 3 of the Data File.','依照問答冊和錄音的指示完成任務。所需資料在問答冊、資料檔及錄音中。聆聽時可在資料檔第 3 頁記筆記。'),('You now have five minutes to familiarize yourself with the Question-Answer Book and the Data File.','現在有五分鐘熟悉問答冊和資料檔。')]
put(2,'<section class="recreated-page situation-page" aria-label="2016 Part B situation and contents"><div class="situation-box"><h2>Part B</h2><h3>Situation</h3>'+''.join(b(*x) for x in situation)+'</div><div class="contents-box"><h3>Contents</h3><ol>'+''.join(f'<li><a href="#page-{page}">{escape(title)} <span>{page}</span></a></li>' for page,title in toc)+'</ol></div></section>')
notes=[('Social History Museum (and directions)','社會歷史博物館及前往路線'),('Wang Chung Traditional Farmhouse and Village','王涌傳統農舍及村莊'),('Dr Jones’ Talk','Jones 博士的講座'),('Chang Yee Tak Plough','張義德犁')]
put(3,'<section class="recreated-page conference-notes" aria-label="Nosing Around podcast notes"><h2>Listening note-taking sheet for podcast <em>Nosing Around</em></h2><div class="notes-form-body">'+''.join(f'<h3>{escape(en)}</h3><p class="translation" lang="zh-Hant">{escape(zh)}</p><textarea data-note="3-{i}" rows="6" aria-label="Notes: {escape(en,quote=True)}"></textarea>' for i,(en,zh) in enumerate(notes,1))+'</div></section>')
lara=[('Hi Indy','Indy：'),('How are things in Hong Kong? Mexico is great! I’ll tell you all about it when I get back. While I am away, I’ve got three things I need you to do.','香港那邊如何？墨西哥很好！回來再告訴你。我不在期間，有三件事請你處理。'),('The first thing I want you to do is complete the 1980s Exhibition flyer. You might want to look at the Hong Kong Review and the minutes of the staff meeting as well as your notes from the podcast. Note that we got positive feedback in The Hong Kong Review so you should be able to find another quote from there to put at the top of the flyer (4 words).','首先完成 1980 年代展覽傳單。參考《香港評論》、員工會議紀錄和播客筆記。評論中有正面評語，請找出另一句四字引言放在傳單上方。'),('Secondly, you need to write the progress report for Dr Jones on the new museum café. Include the following information: the new name for the café, full details about the new location of the café, what work has been completed so far, including the children’s play area outside the café. I’ll forward you my emails with Mr Howard about this. You might want to look at the minutes of the last meeting as well as the Question Wizard results and Mr Lok’s interim report.','其次，為 Jones 博士撰寫新博物館咖啡室的進度報告，交代新名稱、新位置的完整資料，以及咖啡室和戶外兒童遊樂區的工程進度。可參考我和 Howard 先生的電郵、會議紀錄、問卷結果及 Lok 先生的中期報告。'),('Finally, can you write a letter to Ms Pollitti, the Careers Mistress at St Scritti’s School, and tell her about the part-time student assistant positions. We want to attract pupils from this excellent school. You will need to explain what a social history museum is as well as outline the details of the position. See also the minutes of the last meeting and the relevant page in the staff manual to help you. You should include positive feedback from previous student assistants to show why it will be a good experience.','最後請寫信給 St Scritti’s School 的就業輔導老師 Pollitti 女士，介紹兼職學生助理職位。解釋社會歷史博物館的性質及職位詳情，並引用過往助理的正面回饋。')]
put(4,'<section class="recreated-page email-document" aria-label="Email from Lara Gau to Indy Wong"><h2>Email from Lara Gau to Indy Wong</h2><div class="email-window"><div class="email-headers"><div><strong>To:</strong> Indy Wong</div><div><strong>From:</strong> Lara Gau</div><div><strong>Sent:</strong> Fri 8 April 2016 3:14 AM</div><div><strong>Subject:</strong> Things to do</div></div><div class="email-content">'+''.join(b(*x) for x in lara)+'<p>Lara</p></div></div></section>')
article=[('Well, my immediate reaction when my editor told me to review a museum rather than my usual restaurant reviews was ‘Oh no! Not a boring old museum!’ But I had never been to the new Hong Kong Social History Museum, so I tried to keep an open mind....','編輯叫我評論博物館而非平常的餐廳時，我第一反應是「不要！無聊的舊博物館！」但我從未到訪新開的香港社會歷史博物館，於是嘗試保持開放心態。'),('The best part for me at the museum was the “Household of the 80s”. There are lots of rooms you can walk around and you get to try out different things. My favourite room was the “TV lounge”. I got to watch TV. Some old TV programmes I remembered watching when I was a kid. I also really enjoyed playing around on an old “Spectrum” computer and seeing if I could top my high scores on some old games.','最精彩的是「八十年代家居」展區。可以走進不同房間親身體驗。我最喜歡電視廳，看到童年看過的節目，也很享受玩舊式 Spectrum 電腦遊戲。'),('Another great thing about the Social History Museum is that it is really close to South Point MTR.','另一好處是博物館很靠近 South Point 港鐵站。'),('Overall, I have to say this was an excellent day out.','總括而言，這是很棒的一日遊。')]
put(5,'<section class="recreated-page museum-review" aria-label="Hong Kong Review museum article"><h2>Article from <em>The Hong Kong Review</em></h2><article class="review-sheet"><h3>How we used to live in the 80s: The Hong Kong Social History Museum</h3>'+''.join(b(*x) for x in article)+'<p>Rating: ☀ ☀ ☀ ☀ ½</p></article></section>')
minutes=[('Response to “How we used to live in the 1980s” Exhibition',[('Dr Jones was pleased to announce that the exhibition has been very successful so far. The reviews in the newspapers have been very positive, especially about the household of the 1980s. Visitor feedback showed that the bathroom was the most popular room. People reported enjoying smelling the soaps and tasting the toothpaste as top highlights.','Jones 博士表示展覽成績很好，報章尤其讚賞八十年代家居。訪客最喜歡浴室，特別是聞香皂和品嘗牙膏。')]),('Update on the museum café',[('Dr Jones was very concerned that Lara had not yet completed a progress report about the new café before leaving for Mexico. Lara said the final report would be completed by Indy.','Jones 博士擔心 Lara 赴墨西哥前尚未完成新咖啡室進度報告；Lara 說由 Indy 完成。'),('She informed the meeting that Minton’s had finished making the tables and chairs and that the expected delivery date was April 27. She added that Mr Lok, the builders, had promised to send an interim report later that day.','Minton’s 已完成桌椅，預計 4 月 27 日送達；承建商 Lok 先生當天稍後會提交中期報告。')]),('Part-time student assistants',[('Dr Jones has agreed to the request to hire three part-time assistants this year. They will work four days a week from July to August.','Jones 博士同意聘請三名兼職助理，於七至八月每週工作四天。'),('Limahl enquired whether they would help on a daily basis in the café. The meeting rejected this idea but agreed for them to assist when it is very busy.','會議否決讓他們每日在咖啡室工作的建議，但同意在繁忙時協助。'),('It was agreed to increase the hourly rate to $38.','時薪將增至 38 元。')]),('Update on talk',[('Dr Jones confirmed that he would give a talk at the museum. Exact date and time to be confirmed. He added that the talk would be about the changes in the traditional way of life on farms in the New Territories since the 1980s.','Jones 博士會在館內演講，日期時間待定，主題是八十年代以來新界農場傳統生活方式的變化。')])]
meeting='<section class="recreated-page meeting-minutes museum-minutes" aria-label="Museum staff meeting minutes"><h2>Minutes from museum staff meeting</h2><div class="meeting-sheet"><h3>Staff meeting of the Hong Kong Social History Museum</h3><dl class="meeting-meta"><dt>Date:</dt><dd>Tues. April 5, 2016</dd><dt>Venue:</dt><dd>Museum Seminar Room 2</dd><dt>Chairperson:</dt><dd>Dr Jack Jones, Director</dd><dt>In Attendance:</dt><dd>Limahl Howard, Building Management Director<br>Lara Gau, Public Relations and Retail<br>Xu Xinpeng, Facilities</dd><dt>Secretary:</dt><dd>Cindy Lau</dd></dl><h3>Minutes of Meeting</h3><ul>'+''.join('<li><h4>'+escape(title)+'</h4>'+''.join(b(*x) for x in pars)+'</li>' for title,pars in minutes)+'</ul></div></section>'
put(6,meeting)

thread=[('To: Lara Gau','From: Limahl Howard','Sent: Fri 1 April 2016 11:33 AM','Subject: Re: Progress Report',[('Lara','Lara：'),('You can view the online results about the vote on the new café name and children’s play area facilities at Question Wizard: http://questionnwizard.com/hkmuscafe/Quodsusg','新咖啡室名稱及兒童遊樂區設施的投票結果，可在 Question Wizard 網站查閱。'),('The downside of the change of venue is the space. So we can only have the two most popular play area facilities.','更換地點的缺點是空間有限，因此只能設置得票最高的兩項遊樂設施。')],'Limahl'),('To: Limahl Howard','From: Lara Gau','Sent: Thurs 31 March 2016 10:47 AM','Subject: Re: Progress Report',[('Dear Limahl','Limahl：'),('Thanks. Another thing I mentioned on the phone was I need to know what the voters decided about the facilities for the kids’ play area and what they chose for the new name for the café.','謝謝。我在電話中提過，還需要知道投票者為兒童遊樂區選了甚麼設施，以及咖啡室的新名稱。')],'Lara'),('To: Lara Gau','From: Limahl Howard','Sent: Thurs 31 March 2016 10:26 AM','Subject: Progress Report',[('Hi Lara','Lara：'),('Here’s the information about the building work you requested on the phone just now. The main thing I suppose is that the café won’t be on the ground floor. As you will remember, the safety report said the ground floor’s too close to the road – and dangerous for children. Plus, there’s just too much air pollution from the traffic. Oh and the noise (from the traffic). So that’s why it was decided that it’s going to go on the museum rooftop instead.','以下是你剛才來電索取的工程資料。咖啡室不會設在地下，因地下太接近馬路，對兒童有危險，也有交通造成的空氣和噪音污染。因此改設在博物館天台。')],'Limahl')]
def mail(headers,paras,sign):
    return '<div class="email-window"><div class="email-headers">'+''.join(f'<div><strong>{escape(h.split(":",1)[0])}:</strong>{escape(h.split(":",1)[1])}</div>' for h in headers)+'</div><div class="email-content">'+''.join(b(*p) for p in paras)+f'<p>{escape(sign)}</p></div></div>'
put(7,'<section class="recreated-page museum-thread" aria-label="Limahl Howard and Lara Gau email exchange"><h2>Email exchange between Limahl Howard and Lara Gau</h2>'+''.join(mail(row[:4],row[4],row[5]) for row in thread)+'</section>')

names=[('The Rubik Cubical',234),('Spandau Café',567),('Café at the End of the Universe',123),('Snack Man',234),('Foodloose',45)]
facilities=[('Slides',234),('Kids’ climbing wall',576),('Witch’s hat',144),('Swings',786),('Roundabout',55)]
def survey_table(title,first,rows): return '<table><thead><tr><th>'+title+'</th><th>No. of votes</th></tr></thead><tbody>'+''.join(f'<tr><td>{escape(item)}</td><td>{count}</td></tr>' for item,count in rows)+'</tbody></table>'
report=[('The café dining area','Completed','n/a','n/a'),('The café kitchen','70%','16/04','n/a'),('Gift shop windows','15%','28/04','Glass on order. Delivery date tbc'),('Children’s play area','0%','30/04','Start date: after completion of kitchen')]
report_table='<div class="table-scroll"><table><thead><tr><th>Description</th><th>Level of completion</th><th>Estimated date of completion</th><th>Notes</th></tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{escape(v)}</td>' for v in row)+'</tr>' for row in report)+'</tbody></table></div>'
put(8,'<section class="recreated-page museum-survey" aria-label="Question Wizard survey and Lok interim report"><h2>Question Wizard online survey results of museum visitors</h2><div class="survey-browser"><div class="browser-strip">Question Wizard · File　Edit　View　Go　Bookmarks　Tools　Help</div><div class="browser-strip">http://questionnwizard.com/hkmuscafe/Quodsusg</div><div class="survey-tables">'+survey_table('Suggested names','Suggested name',names)+survey_table('Suggested play area facilities','Facility',facilities)+'</div></div><p class="translation" lang="zh-Hant">咖啡室名稱以 Spandau Café 得票最多（567 票）；遊樂設施以鞦韆（786 票）及兒童攀石牆（576 票）得票最多。</p><h2>Lok and Partners’ interim report</h2><div class="email-window"><div class="email-headers"><div><strong>To:</strong> Lara Gau</div><div><strong>From:</strong> Lok and Partners</div><div><strong>Sent:</strong> Tues 5 April 2016 4:33 PM</div><div><strong>Subject:</strong> Interim Report on HK Social History Museum work</div></div><div class="email-content">'+b('Dear Ms Gau,','Gau 女士：')+b('See the interim report below on the building work at the museum as requested:','按要求，以下是博物館工程的中期報告：')+report_table+b('Please contact me on WhatsApp on 9654376 if you have any enquiries.','如有疑問，請透過 WhatsApp 9654376 聯絡我。')+'<p>Regards,<br>Jimmie Lok<br>Lok and Partners Ltd</p></div></div></section>')

feedback=[('Thinking back on what happened while I worked there I feel teamwork was what I really developed in.','回想在這裏工作的經歷，我覺得最有進步的是團隊合作。'),('It was okay at times. A bit boring though.','有時還可以，不過有點無聊。'),('The pay was terrible but having said that as a communicator I’m so much better than I was before.','薪酬很差，但我的溝通能力確實比以前好得多。')]
put(9,'<section class="recreated-page museum-manual" aria-label="Museum staff manual and student feedback"><h2>Museum Staff Manual</h2><div class="manual-sheet"><h3>Section 4.5: Part-time Student Assistant Staff</h3><h4>4.5.1 Main Duties</h4>'+b('Part-time assistants are permitted to do the following:','兼職助理可執行以下工作：')+'<ul><li>assist visitors</li><li>clean display items (after training)</li></ul><p class="translation" lang="zh-Hant">協助訪客；接受培訓後清潔展品。</p><h4>4.5.2 Working Hours</h4>'+b('Assistants must not work more than 4 hours per day on any day.','助理每日工作不可超過四小時。')+'</div><h2>Part-time student assistants’ feedback from summer 2015</h2><div class="feedback-sheet">'+''.join(f'<div class="feedback-item"><strong>({i})</strong>{b(en,zh)}</div>' for i,(en,zh) in enumerate(feedback,1))+'</div><p class="end-note">THIS IS THE LAST PAGE OF THE PART B1 DATA FILE</p></section>')

flyer='<div class="museum-flyer"><h4>The Hong Kong Social History Museum Presents:<br>How we used to live in the 1980s</h4><p class="flyer-tagline">Come and experience how people lived in the 1980s in our exciting new exhibition!</p><div class="flyer-quotes"><strong>“A wonderful experience” – Hong Kong Times</strong><label>“'+inp('quote','Four-word quote from The Hong Kong Review')+'” – '+inp('quote-source','Quote source')+'</label></div><div class="flyer-columns"><section><h5>TALKS</h5><label>Title: '+inp('talk-title','Talk title')+'</label><label>Speaker: '+inp('speaker','Talk speaker')+'</label><label>Contents of Talk: '+inp('talk-content','Talk content')+'</label><label>Date &amp; Time: '+inp('talk-time','Talk date and time')+'</label></section><section><h5>HOUSEHOLD OF THE 1980s</h5><ul><li><strong>Room #1: The bedroom.</strong><p>Activities: Admire posters, listen to some 80s pop music like “Hot Topic” and “Lena Nutshell” and read classic story books and comics.</p></li><li>Room #2: '+inp('room2','Second room name')+'<p>Activities: '+inp('room2-activity','Second room activities')+'</p></li><li>Room #3: '+inp('room3','Third room name')+'<p>Activities: '+inp('room3-activity','Third room activities')+'</p></li></ul></section></div><label>Directions for getting to the museum from the new MTR station<textarea rows="3" data-note="10-directions" aria-label="Directions from the new MTR station"></textarea></label></div>'
put(10,'<section class="recreated-page answer-book museum-flyer-answer" aria-label="2016 B1 QAB page 1"><div class="answer-book-header"><span>HKDSE 2016 · ENGLISH LANGUAGE · PAPER 3 PART B1 · Question-Answer Book</span><strong>B1</strong></div><h3>Task 5: Exhibition flyer <small>(18 marks)</small></h3>'+b('Complete the 1980s Exhibition flyer below using information from the B1 Data File and your notes.','利用乙部一資料檔及筆記完成八十年代展覽傳單。')+flyer+'<p class="answer-end">END OF TASK 5</p></section>')

def essay(page,key,title,zh,lead='',height=680):
    cid=f'2016-b1-{page}-{key}'
    return f'<section class="recreated-page answer-book" aria-label="2016 B1 QAB page {page-9}"><h3>{escape(title)}</h3>{lead}<p class="translation" lang="zh-Hant">{escape(zh)}</p><label class="answer-field" for="{cid}">{escape(title)}</label><textarea class="answer-box" id="{cid}" data-note="{page}-{key}" data-count-id="{cid}" style="min-height:{height}px" aria-label="{escape(title,quote=True)}"></textarea><p class="answer-count" data-count-for="{cid}">0 words</p>'
put(11,essay(11,'report','Task 6: Progress report (18 marks)','任務 6：新博物館咖啡室進度報告，約 120 字。',b('Write a progress report on the new museum café using information from the B1 Data File. Write around 120 words.','利用乙部一資料檔撰寫新博物館咖啡室進度報告，約 120 字。'))+'</section>')
put(12,essay(12,'report-cont','Task 6: Progress report, continued','任務 6：進度報告續頁。',height=300)+'<p class="answer-end">END OF TASK 6</p><h3>Task 7: Letter <small>(18 marks)</small></h3>'+b('Write a letter to the Careers Mistress at St. Scritti’s School using information from the Data File and your notes. There is no need to write the address or date. Write around 150 words.','利用資料檔及筆記寫信給 St. Scritti’s School 的就業輔導老師。毋須寫地址或日期，約 150 字。')+'<label class="answer-field" for="2016-b1-12-letter">Task 7 letter</label><textarea class="answer-box" id="2016-b1-12-letter" data-note="12-letter" data-count-id="2016-b1-12-letter" style="min-height:420px" aria-label="Task 7 letter"></textarea><p class="answer-count" data-count-for="2016-b1-12-letter">0 words</p></section>')
put(13,essay(13,'letter-cont','Task 7: Letter, continued','任務 7：書信續頁。',height=720)+'<p class="answer-end">END OF TASK 7<br>END OF PART B1</p></section>')
