"""Source-authored reconstruction of 2015 Paper 3 B1 Data File and QAB."""
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent / "layouts"


def b(en, zh):
    return f'<div class="bilingual"><p lang="en">{escape(en)}</p><p class="translation" lang="zh-Hant">{escape(zh)}</p></div>'


def put(n, content):
    (ROOT / f"2015-b1-page-{n:02}.html").write_text(content.rstrip() + "\n", encoding="utf-8")


put(1, (ROOT / "2014-b1-page-01.html").read_text().replace("2014", "2015"))

toc = [(3,"Listening note-taking sheet for the Skype conference on April 2"),(4,"Email from Malcolm Parker to Starsky Chung"),(5,"WhatsApp chat between Malcolm Parker and Ms. Ajala Chaterjee"),(5,"Email from Dong Jianzhen to Malcolm Parker"),(6,"WhatsApp chat between Malcolm Parker and Charlie Chiba"),(7,"Email from Angelina Dai to Malcolm Parker"),(7,"Letter from pupils at St. Godfrey’s Catholic School to Malcolm Parker"),(8,"Transcript extract from Listen Up! podcast"),(9,"iTunes screenshot"),(9,"Most Downloaded Songs in UK (2014) from Dredger Magazine"),(9,"Buzz Online Worst Albums of 2012 by listener votes")]
situation = [
    ("You are Starsky Chung. You work for North Star Artists, an international agency that manages a range of pop music bands and singers.", "你是 Starsky Chung，在管理多個流行樂隊和歌手的國際經紀公司 North Star Artists 工作。"),
    ("Your boss is Malcolm Parker, who works in the London office of North Star Artists. He is sending a British pop band called Bubblegum to Hong Kong to do some promotions for their next CD. You need to look after them while they are here.", "你的上司 Malcolm Parker 在倫敦辦公室工作。他安排英國流行樂隊 Bubblegum 到香港宣傳新唱片，你要在他們來港期間照顧他們。"),
    ("You will listen to a Skype conference call between Malcolm Parker, a music video director – Eduardo de Luca – and yourself.", "你將聆聽你、Malcolm Parker 和音樂錄影帶導演 Eduardo de Luca 的 Skype 會議。"),
    ("Before the recording is played, you will have five minutes to study the Question-Answer Book and the Data File to familiarize yourself with the situation and the tasks.", "錄音播放前，你有五分鐘閱讀問答冊及資料檔，熟悉情境和任務。"),
    ("Complete the tasks by following the instructions in the Question-Answer Book and on the recording. You will find all the information you need in the Question-Answer Book, the Data File and on the recording. As you listen you can make notes on page 3 of the Data File.", "按照問答冊和錄音的指示完成任務。所需資料在問答冊、資料檔和錄音中；聆聽時可在資料檔第 3 頁做筆記。"),
    ("You now have five minutes to familiarize yourself with the Question-Answer Book and the Data File.", "現在你有五分鐘熟悉問答冊和資料檔。"),
]
put(2, '<section class="recreated-page situation-page" aria-label="2015 B1 situation and contents"><div class="situation-box"><h2>Part B</h2><h3>Situation</h3>' + ''.join(b(*p) for p in situation) + '</div><div class="contents-box"><h3>Contents</h3><ol>' + ''.join(f'<li><a href="#page-{n}">{escape(title)} <span>{n}</span></a></li>' for n,title in toc) + '</ol></div></section>')

headings = [("Performance at Atlantic Plaza","在 Atlantic Plaza 的表演"),("Music Video (May 19)","5 月 19 日的音樂錄影帶"),("Rules about interviews with band","訪問樂隊的規則"),("Merchandise / Souvenirs for Asian Tour","亞洲巡演商品及紀念品")]
put(3, '<section class="recreated-page conference-notes" aria-label="Skype conference note-taking sheet"><h2>Listening note-taking sheet for the Skype conference on April 2</h2><div class="notes-form-body">' + ''.join(f'<h3>{escape(en)}</h3><p class="translation" lang="zh-Hant">{escape(zh)}</p><textarea rows="5" data-note="3-{i}" aria-label="Notes: {escape(en, quote=True)}"></textarea>' for i,(en,zh) in enumerate(headings,1)) + '</div></section>')

email = [
    ("Dear Starsky", "Starsky："),
    ("I need you to do a few things in preparation for Bubblegum’s visit to Hong Kong in May.", "為準備 Bubblegum 五月訪港，請幫我完成幾件事。"),
    ("First, I need you to complete the whole-day schedule for the band’s performance at the Atlantic Plaza shopping mall. Look at your notes from the Skype conference, my WhatsApp chats and the emails I got from Ms. Dong Jianzhen and from the Paradise Gardens Hotel.", "首先，請完成樂隊在 Atlantic Plaza 商場表演當天的全日時間表。參考 Skype 會議筆記、我的 WhatsApp 對話、Dong Jianzhen 女士及 Paradise Gardens Hotel 的電郵。"),
    ("You also need to work on the Hong Kong Bubblegum Fan Club website. We’ve now written a biography for all the band members except for Charlie Chiba. So I want you to write a short biography of Charlie Chiba. Mention the following things:", "你還要處理香港 Bubblegum 歌迷會網站。其他成員的傳記已寫好，請為 Charlie Chiba 撰寫簡短傳記，涵蓋以下資料："),
    ("Look at the transcript of the Listen Up! podcast, and the information I found from iTunes, Dredger Magazine and Buzz Online. Don’t forget you’ll be writing for Bubblegum’s teenage fans.", "參考 Listen Up! 播客逐字稿、iTunes、Dredger Magazine 和 Buzz Online 的資料；讀者是 Bubblegum 的青少年歌迷。"),
    ("Finally, remember I’ve agreed to allow the pupils from St. Godfrey’s Catholic School to interview Bubblegum. Please write them an email answering their questions. Make the rules about interviews and questions clear to them. I’ll forward you a scan of their letter and the email from the Paradise Gardens Hotel too. Look at your notes from the Skype conference, the letter the pupils sent me and the email from the Paradise Gardens Hotel as well as my WhatsApp chats and the Listen Up! podcast.", "最後，我已同意讓 St. Godfrey’s Catholic School 的學生訪問樂隊。請電郵回答他們的問題，清楚交代訪問和提問規則。參考會議筆記、學生來信、酒店電郵、WhatsApp 對話及播客。"),
]
email_window = '<div class="email-window"><div class="email-headers"><div><strong>To:</strong> Starsky Chung</div><div><strong>From:</strong> Malcolm Parker</div><div><strong>Date:</strong> 14 April 2015</div><div><strong>Subject:</strong> Things to do</div></div><div class="email-content">' + ''.join(b(*p) for p in email[:4]) + '<ul><li>Her early life</li><li>Her career before she joined Bubblegum (you can include negative things here!)</li><li>Her career and achievements after she joined Bubblegum</li></ul><p class="translation" lang="zh-Hant">她的早年生活、加入 Bubblegum 前的事業（可提負面資料）、加入後的事業與成就。</p>' + ''.join(b(*p) for p in email[4:]) + '<p>Malcolm</p></div></div>'
put(4, '<section class="recreated-page email-document" aria-label="Malcolm Parker email to Starsky Chung"><h2>Email from Malcolm Parker to Starsky Chung</h2>' + email_window + '</section>')

def bubble(who, en, zh, outgoing=False):
    return f'<div class="chat-bubble{" outgoing" if outgoing else ""}"><strong>{escape(who)}:</strong>{b(en,zh)}</div>'


chat5 = bubble("Ajala","Hi Malcolm, I can meet Bubblegum at Atlantic Plaza at 1:30pm on the day to take photographs. Did Ms. Dong tell you where she wants the band to be photographed?","我可在下午 1:30 到 Atlantic Plaza 為 Bubblegum 拍照。Dong 女士有說在哪裏拍嗎？") + bubble("Malcolm","She said the main entrance. Don’t forget we also need you to take more photographs at 3.30pm. Don’t be late because the band are signing CDs at 4 o’clock. I’ll ask Starsky to put these points in the band’s appointments for Atlantic Plaza later and send you a copy.","在正門。另外下午 3:30 要再拍照；樂隊 4 時簽唱片，別遲到。我會請 Starsky 把這些寫入當日行程。",True)
dong = [("Dear Mr. Parker", "Parker 先生："),("Just to say again how very excited we are about Bubblegum’s visit to Atlantic Plaza.","我們非常期待 Bubblegum 到訪 Atlantic Plaza。"),("I have some important instructions for the band’s performance at 2.30pm. Could you remind the band about wearing the T-shirts we provided? Also, we’d be grateful if the band could thank Atlantic Plaza at the end of the show. After thanking Atlantic Plaza, I would then like the band to have their photograph taken with me.","下午 2:30 的表演有幾項重要指示：請樂隊穿我們提供的 T 恤，演出後感謝 Atlantic Plaza，然後與我合照。"),("As regards dining on the day, I’d like to invite the group to have breakfast with me in my office at 8.30 a.m. and then for lunch I have arranged for them to go to the ‘Fresh and Healthy’ Restaurant in Atlantic Plaza at 12.30 pm.","當天早上 8:30，我邀請樂隊到辦公室共進早餐；中午 12:30 已安排他們在商場的 Fresh and Healthy 餐廳午膳。")]
put(5, '<section class="recreated-page bubblegum-docs" aria-label="Ajala WhatsApp and Dong email"><h2>WhatsApp chat between Malcolm Parker and Ms. Ajala Chaterjee</h2><div class="bubblegum-chat"><div class="chat-time">08:48</div>' + chat5 + '</div><h2>Email from Dong Jianzhen to Malcolm Parker</h2><div class="email-document"><div class="email-window"><div class="email-headers"><div><strong>To:</strong> Malcolm Parker</div><div><strong>From:</strong> Dong Jianzhen</div><div><strong>Date:</strong> April 8 2015</div><div><strong>Subject:</strong> Atlantic Plaza visit</div></div><div class="email-content">' + ''.join(b(*p) for p in dong) + '<p>Best regards<br>Dong Jianzhen<br>Managing Director of Atlantic Plaza</p></div></div></div></section>')

chat6 = [
    ("Malcolm","I’ve decided which songs I’d like you guys to sing at Atlantic Plaza. I want you to sing “You’re special” as the second song and “Hey! Don’t ignore me” as the third song. You guys will sing “Mirror of love” at the beginning of the performance because it will be your next hit. Please remember too that you must start the performance with a greeting.","我已決定 Atlantic Plaza 表演的歌曲：第一首《Mirror of love》，第二首《You’re special》，第三首《Hey! Don’t ignore me》。開場也要先向觀眾打招呼。"),
    ("Charlie","You mean like “Hello Hong Kong”?","例如說「Hello Hong Kong」？"),
    ("Malcolm","Yes, say that at the start. Don’t forget!","是的，開場時說，別忘記！"),
    ("Charlie","Okay Malcolm. Can you ask Starsky to write these points on the song list and in some special instructions so we remember. Can you also tell Starsky people should talk to us politely during interviews – you know, like, respectful. No questions about you know who’s family.","請 Starsky 把這些寫進歌單和特別指示。訪問者也要有禮貌，不要問那位成員家人的問題。"),
    ("Malcolm","You mean Mark Nelson’s family? Yes, I will tell Starsky. And I’ll ask Starsky to tell interviewers to talk about your latest CD and what you guys think of Hong Kong.","你指 Mark Nelson 的家人？我會告訴 Starsky，也請她提醒訪問者談新唱片和你們對香港的看法。"),
    ("Charlie","Yes, we’d love to talk about the “Sugar Love Mountain” CD. But no interviews longer than one hour. PLEASE!","我們很樂意談《Sugar Love Mountain》唱片，但訪問請不要超過一小時！"),
]
put(6, '<section class="recreated-page bubblegum-docs" aria-label="Malcolm and Charlie WhatsApp"><h2>WhatsApp chat between Malcolm Parker and Charlie Chiba</h2><div class="bubblegum-chat"><div class="chat-time">12:06</div>' + ''.join(bubble(w,e,z,w=="Charlie") for w,e,z in chat6) + '</div></section>')

angelina = [("Hi Malcolm","Malcolm 你好："),("Good to hear from you again. Hope the weather is better in London.","很高興再收到你的消息，希望倫敦天氣好一些。"),("Anyway, I’ve managed to find you a room for holding the interview (room 829). It’s excellent for conducting interviews and it will be available on 19th May (Tuesday) from 2:00pm to 5:00pm. I will personally make sure that no more than 4 people are allowed in to do the interview as you requested.","我找到適合訪問的 829 號房，5 月 19 日星期二下午 2 至 5 時可使用。我會按你的要求確保訪問者不超過四人。"),("Just to warn you that the hotel has some really tough rules about dress. Basically, the hotel will tell anyone who isn’t wearing smart clothes to leave. And sandals? Absolutely not!","酒店有嚴格衣着規定：衣着不整者會被請離，亦絕不能穿涼鞋。"),("Also, our helicopter will be ready at 5.30pm at Atlantic Plaza on 18th May (Monday). I am sure Bubblegum will enjoy the flight back to the hotel.","直升機將於 5 月 18 日星期一下午 5:30 在 Atlantic Plaza 準備好，接樂隊返回酒店。"),("Looking forward to another drink (or three!) with you soon.","期待很快再跟你喝幾杯。")]
bonnie = [("Dear Mr. Parker,","Parker 先生："),("We are students at St. Godfrey’s Catholic School and we are really BIG fans of Bubblegum. We think their music is really great to listen to and their image is really cool and trendy.","我們是 St. Godfrey’s Catholic School 的學生，也是 Bubblegum 的忠實歌迷，很喜歡他們的音樂和形象。"),("We would be so honoured if they could do an interview with some of our senior students from our Media Club. What we would like to know is:","如果他們能接受媒體學會高年級學生的訪問，我們會非常榮幸。我們想知道："),("The time, place and length of time for the interview. (Please note that due to school activities during the week Bubblegum are in Hong Kong, we will only be free after 4pm)","訪問的時間、地點和長度。由於校內活動，我們只在下午 4 時後有空。"),("I know this is short notice and the band will be really busy in Hong Kong, but if you could find any time in their schedule to have an interview with us then that would be amazing.","我知道提出得很倉促，樂隊訪港也很忙，但若能安排任何訪問時間就太好了。"),("Please tell Bubblegum how much we love them!","請向 Bubblegum 轉達我們的喜愛！")]
put(7, '<section class="recreated-page bubblegum-docs" aria-label="Angelina email and St. Godfrey’s letter"><h2>Email from Angelina Dai to Malcolm Parker</h2><div class="email-document"><div class="email-window"><div class="email-headers"><div><strong>To:</strong> Malcolm Parker</div><div><strong>From:</strong> Angelina Dai</div><div><strong>Date:</strong> April 1 2015</div><div><strong>Subject:</strong> Update</div></div><div class="email-content">' + ''.join(b(*p) for p in angelina) + '<p>Angelina<br>General Manager<br>Paradise Gardens Hotel</p></div></div></div><h2>Letter from pupils at St. Godfrey’s Catholic School to Malcolm Parker</h2><div class="bubblegum-letter"><h3>ST. GODFREY’S CATHOLIC SCHOOL</h3><p class="letter-date">March 20, 2015</p>' + ''.join(b(*p) for p in bonnie[:3]) + '<ul><li>' + b(*bonnie[3]) + '</li></ul>' + ''.join(b(*p) for p in bonnie[4:]) + '<p>Yours sincerely,<br>Bonnie Ng<br>Chairperson of the Media Club<br>St. Godfrey’s Catholic School</p></div></section>')

podcast = [
    ("Sarah Wilde","Woo! Charlie Chiba from Bubblegum. So how’s it going?","哇！Bubblegum 的 Charlie Chiba，最近怎樣？"),("Charlie Chiba","Great to be here.","很高興來到這裏。"),("Sara Wilde","So tell us about yourself Charlie.","Charlie，介紹一下自己吧。"),("Charlie Chiba","Well, I’m actually not from London like everyone thinks. I was born way up North.","其實我不像大家以為的那樣來自倫敦，我出生在很北的地方。"),("Sara Wilde","In Scotland, you mean?","你指蘇格蘭？"),("Charlie Chiba","Yeah, in a tiny village. In 1996.","對，一條小村莊，1996 年出生。"),("Sara Wilde","Wow! And your dad was Japanese right?","你爸爸是日本人，對嗎？"),("Charlie Chiba","Yes, but my mum is English. We moved down to London when I was 6 years old.","對，媽媽是英國人。我六歲時搬到倫敦。"),("Sara Wilde","Do you ever get scared by your fans, Charlie? You must have heard about that all-girl Japanese band who were attacked by a crazy man with a knife.","你會害怕歌迷嗎？你應該聽過那支日本女子樂隊被持刀男子襲擊的事。"),("Charlie Chiba","Oh, sometimes. But we have rules to protect us. If anyone wants to interview us then they need to…","有時會，但我們有保護自己的規則。想訪問我們的人需要……"),("Sara Wilde","…let me guess. Show our ID card, right? Ha ha. Actually listeners, we had to do this… and they searched our bags and equipment! Crazy!","讓我猜猜，要出示身分證？對，我們還要讓他們檢查袋子和器材！"),("Charlie Chiba","Those are the rules for interviewing us for every interview I’m afraid! Ha ha!","恐怕每次訪問都要遵守這些規則！"),("Sara Wilde","You joined Bubblegum in 2013, but what was your career like before you joined?","你 2013 年加入 Bubblegum，之前的事業如何？"),("Charlie Chiba","Oh dear. Ha, ha. What can I say? I did win best singer in the London Youth Music Awards, so I guess it wasn’t all bad news, I suppose.","這該怎說？我曾獲倫敦青年音樂獎最佳歌手，所以也不全是壞事。"),("Sara Wilde","Were you still at school then?","那時你還在上學嗎？"),("Charlie Chiba","Yeah, it was 2010. So yeah.","是，那是 2010 年。"),("Sara Wilde","Actually, I think I remember your solo album, “Oh So Pretty” in 2012. Oh dear! But let’s move on eh? Now, our listeners might be interested to know that you went to the same school as me.","我記得你 2012 年的個人專輯《Oh So Pretty》。我們換個話題吧；聽眾或許有興趣知道我們讀同一所學校。"),("Charlie Chiba","That’s right. Gray’s School of Music and Drama. Ha ha. But you were a few years above me.","對，Gray’s School of Music and Drama，不過你比我高幾級。"),("Sara Wilde","But we’re both still young. Ha ha. I suppose we had the same teachers though. Did you have Mr. Wildgoose?","但我們都還年輕。可能有同樣的老師。Wildgoose 先生教過你嗎？"),("Charlie Chiba","No, but I remember the stories!","沒有，但我記得他的故事！")]
put(8, '<section class="recreated-page interview-page" aria-label="Listen Up! podcast transcript"><h2>Transcript extract from <em>Listen Up!</em> podcast</h2><div class="transcript-sheet">' + ''.join(f'<div class="dialogue-turn"><strong>{escape(who)}:</strong>{b(en,zh)}</div>' for who,en,zh in podcast) + '</div></section>')

songs = [("Auto Motorik","6.32","Rael","Rael","Waiting Room","Dance"),("Dance addiction","4.21","Bubblegum","Charlie Chiba","Meet the Bubblegum","Pop"),("Emotion lol","3.23","Cute Cute","Yannie Ming","Pink Rabbits","Pop"),("Voodoo","5.32","Crème Brulee","Les McQueen","Just Desserts","Rock")]
table = '<div class="music-table-scroll"><table><thead><tr>' + ''.join(f'<th>{h}</th>' for h in ["Song Title","Time","Artist","Songwriter","Album","Genre"]) + '</tr></thead><tbody>' + ''.join('<tr>' + ''.join(f'<td>{escape(v)}</td>' for v in row) + '</tr>' for row in songs) + '</tbody></table></div>'
downloads = [("Let’s Play",12),("Dance Addiction",11),("She’s like Wow",9),("Got the vibe?",7.5),("Love Me Forever",7)]
bar_svg = '<svg role="img" aria-label="Most downloaded songs in UK, 2014" viewBox="0 0 680 310"><title>Most Downloaded Songs in UK (2014)</title><line x1="65" y1="245" x2="670" y2="245" stroke="#304649"/><line x1="65" y1="22" x2="65" y2="245" stroke="#304649"/>'
for tick in range(0,15,2):
    y=245-tick*15
    bar_svg+=f'<line x1="65" y1="{y}" x2="670" y2="{y}" stroke="#c8d2d0"/><text x="58" y="{y+4}" text-anchor="end">{tick}</text>'
for i,(title,value) in enumerate(downloads):
    x=93+i*116
    bar_svg+=f'<rect x="{x}" y="{245-value*15}" width="64" height="{value*15}" fill="#718d8c"/><text x="{x+32}" y="264" text-anchor="middle">{escape(title)}</text>'
bar_svg+='</svg>'
vote_bubbles=[("Toons to Dance To","thumb-1"),("Oh So Pretty","thumb-2"),("Three Chimneys","thumb-3"),("Just Desserts","thumb-4")]
votes = '<div class="vote-axis"><span>600 000 votes</span><span>400 000 votes</span><span>200 000 votes</span><span>0 votes</span></div><div class="vote-items">' + ''.join(f'<div><img src="assets/page-09-{name}.webp" alt="Original thumbs-down illustration for {escape(title, quote=True)}"><strong>{escape(title)}</strong></div>' for title,name in vote_bubbles) + '</div>'
put(9, '<section class="recreated-page bubblegum-charts" aria-label="iTunes table, download chart and album votes"><h2>iTunes screenshot</h2><div class="itunes-panel"><div class="itunes-toolbar">File　Edit　View　Controls　Store　Advanced　Help <strong>iTunes</strong></div><div class="itunes-controls">◀　▶　▷　♫　　▰▰▰▰　　　　　Search Play...</div>' + table + '<footer>709 songs, 2 days, 4.68 GB</footer></div><p class="translation" lang="zh-Hant">iTunes 列出歌曲名稱、長度、歌手、作曲者、專輯及類型；Bubblegum 的〈Dance addiction〉由 Charlie Chiba 創作。</p><h2>Most Downloaded Songs in UK (2014) from <em>Dredger Magazine</em></h2><figure class="bubblegum-bar-chart">' + bar_svg + '<figcaption>Millions of Downloads</figcaption><p class="translation" lang="zh-Hant">2014 年英國下載量最高的歌曲；縱軸單位為百萬次下載。</p></figure><h2><em>Buzz Online</em> Worst Albums of 2012 by listener votes</h2><figure class="bubblegum-vote-chart">' + votes + '<figcaption>Listener votes, 2012</figcaption><p class="translation" lang="zh-Hant">《Oh So Pretty》是圖中獲最多「最差專輯」選票的作品。</p></figure><p class="end-note">THIS IS THE LAST PAGE OF THE PART B1 DATA FILE</p></section>')


def inp(key, label, width=""):
    return f'<input data-note="10-{key}" aria-label="{escape(label, quote=True)}"{f" class={width!r}" if width else ""}>'


times=[("8:15am","Meet the driver and go to Atlantic Plaza"),("8:30am",None),("10:00am",None),("12:30pm",None),("1:30pm",None),("2:30pm","Give the live performance in the main hall of Atlantic Plaza"),("3.30pm",None),("4.00pm",None),("5:30pm",None)]
schedule = '<div class="bubblegum-schedule"><h4>Schedule for show at Atlantic Plaza shopping mall</h4><label>Date &amp; Day: ' + inp("date","Schedule date and day") + '</label><div class="table-scroll"><table><thead><tr><th>TIME</th><th>APPOINTMENT</th></tr></thead><tbody>' + ''.join(f'<tr><td>{t}</td><td>{escape(v) if v else inp("time-"+t,"Appointment at "+t)}</td></tr>' for t,v in times) + '</tbody></table></div><h5>Special instructions for the live performance at 2:30pm</h5><ul><li>Each band member should come on stage after their name is announced.</li>' + ''.join(f'<li>{inp("instruction-"+str(i),"Special instruction "+str(i),"full")}</li>' for i in range(1,5)) + '</ul><h5>Song list (in order)</h5><ol>' + ''.join(f'<li>{escape(name) if name else inp("song-"+str(i),"Song "+str(i))}</li>' for i,name in enumerate([None,None,None,"Party time all the time","Dance Addiction",None],1)) + '</ol></div>'
put(10, '<section class="recreated-page answer-book bubblegum-answer" aria-label="2015 B1 QAB page 1"><div class="answer-book-header"><span>HKDSE 2015 · ENGLISH LANGUAGE · PAPER 3 PART B1 · Question-Answer Book</span><strong>B1</strong></div><h3>Task 5: Schedule <small>(18 marks)</small></h3>' + b("Complete the schedule below using information from the B1 Data File and your notes.","利用乙部一資料檔及筆記完成下列時間表。") + schedule + '<p class="answer-end">END OF TASK 5</p></section>')


def essay(page,key,title,zh,lead="",height=680):
    cid=f"2015-b1-{page}-{key}"
    return f'<section class="recreated-page answer-book" aria-label="2015 B1 QAB page {page-9}"><h3>{escape(title)}</h3>{lead}<p class="translation" lang="zh-Hant">{escape(zh)}</p><label class="answer-field" for="{cid}">{escape(title)}</label><textarea class="answer-box" id="{cid}" data-note="{page}-{key}" data-count-id="{cid}" style="min-height:{height}px" aria-label="{escape(title,quote=True)}"></textarea><p class="answer-count" data-count-for="{cid}">0 words</p>'


put(11,essay(11,"bio","Task 6: Short biography (18 marks)","任務 6：Charlie Chiba 的簡短傳記，約 120 字。",b("Write a short biography of Charlie Chiba using information from the B1 Data File. Write around 120 words.","利用乙部一資料檔為 Charlie Chiba 寫一篇約 120 字的簡短傳記。")+'<h4>All About Charlie Chiba</h4>')+'</section>')
put(12,essay(12,"bio-cont","Task 6: Short biography, continued","任務 6：簡短傳記續頁。",height=300)+'<p class="answer-end">END OF TASK 6</p><h3>Task 7: Email <small>(18 marks)</small></h3>'+b("Write an email replying to the pupils at St. Godfrey’s Catholic School using information from the B1 Data File and your notes. Write around 150 words.","利用乙部一資料檔及筆記回覆 St. Godfrey’s Catholic School 的學生，約 150 字。")+'<label class="answer-field" for="2015-b1-12-email">Task 7 email</label><textarea class="answer-box" id="2015-b1-12-email" data-note="12-email" data-count-id="2015-b1-12-email" style="min-height:420px" aria-label="Task 7 email"></textarea><p class="answer-count" data-count-for="2015-b1-12-email">0 words</p></section>')
put(13,essay(13,"email-cont","Task 7: Email, continued","任務 7：電郵續頁。",height=720)+'<p class="answer-end">END OF TASK 7<br>END OF PART B1</p></section>')
