"""Source-specific native reconstruction of 2022 Shiny Diamond Paper 3 B2."""
from pathlib import Path
from html import escape
import re
B=Path(__file__).resolve().parent;L=B/'layouts';R=(B/'source/2022-b2-df-clean.txt').read_text()
a=re.split(r'=+\nPDF page \d+ / printed page (\d+)\n=+\n',R)
P={int(a[i]):[re.sub(r'\s+',' ',x.strip()) for x in a[i+1].split('\n\n') if x.strip()] for i in range(1,len(a),2)}
def put(n,s):(L/f'2022-b2-page-{n:02}.html').write_text(s.rstrip()+'\n')
def bi(t,z):return f'<div class="bilingual"><p lang="en">{escape(t)}</p><p class="translation" lang="zh-Hant">{escape(z)}</p></div>'
def paras(p,start,end,z):
 q=p[start:end];assert len(q)==len(z),(len(q),len(z),q)
 return ''.join(bi(t,c) for t,c in zip(q,z))
def email(to,fr,sent,sub,body):
 return '<div class="email-window"><div class="email-toolbar">File　 Message　 Junk　 Delete　 Reply　 Reply All　 Forward　 Move　 Mark Unread　 Follow up</div><div class="email-headers">'+''.join(f'<div><b>{x}:</b> {escape(y)}</div>' for x,y in [('To',to),('From',fr),('Sent',sent),('Subject',sub)])+'</div><div class="email-content">'+body+'</div></div>'
def ans(n,key,label,h=710):
 ident=f'2022-b2-{n}-{key}';return f'<label class="answer-field" for="{ident}">{escape(label)}</label><textarea id="{ident}" class="answer-box" data-note="{n}-{key}" data-count-id="{ident}" style="min-height:{h}px"></textarea><p class="answer-count" data-count-for="{ident}">0 words</p>'
cover=(L/'2022-b1-page-01.html').read_text();cover=cover.replace('aria-label="2022 DSE Paper 3 Part B1 Data File cover"','aria-label="2022 DSE Paper 3 Part B2 Data File cover"').replace('PART B1</div>','PART B2</div>').replace('<strong>B1</strong><span>EASY SECTION','<strong>B2</strong><span>DIFFICULT SECTION').replace('<h2>PART B1</h2>','<h2>PART B2</h2>').replace('INSTRUCTIONS FOR PART B1','INSTRUCTIONS FOR PART B2').replace('The Question-Answer Book for Part B1 is inserted','The Question-Answer Book for Part B2 is inserted').replace('乙部一問答冊夾於本資料檔內','乙部二問答冊夾於本資料檔內');put(1,cover)
p=P[2];z=['你是 Nico Lin，在設計、製造及銷售霓虹燈產品與服務的 Shiny Diamond Lighting Ltd 工作；上司 Floyd Mann 請你處理寫作任務。','你將聆聽香港電台藝術文化節目《Wish You Were Here》的播客，主持 Julia Din 訪問公司東主 Pris Fong 和首席設計師、霓虹藝術家 Rick Lai。','錄音播放前有五分鐘閱讀問答冊及資料檔，熟悉情境和任務。','根據問答冊、資料檔及錄音的指示完成任務。聆聽時可在資料檔第 3 頁做筆記。','現在有五分鐘熟悉問答冊及資料檔。']
toc=[(3,'Listening note-taking sheet for the Wish You Were Here podcast'),(4,'Email from Floyd Mann'),(5,'Newspaper Clipping from the Hong Kong Newspaper'),(5,'Emily Plays Travel Blog'),(6,'Extracts from Pris Fong’s Diary'),(7,'Shiny Diamond Performance Report'),(8,'2022 Shiny Diamond Customer Survey Results'),(8,'Shiny Diamond Products Brochure Page'),(9,'Email from Wan Yuen Estate Residents’ Association'),(10,'Attachment to the Wan Yuen Estate Residents’ Association Email'),(11,'Meeting Minutes of the Shiny Diamond Management Committee')]
put(2,'<section class="recreated-page situation-page" aria-label="Shiny Diamond situation and contents"><div class="situation-box"><h2>Part B</h2><h3>Situation</h3>'+paras(p,2,7,z)+'</div><div class="contents-box"><h3>Contents</h3><ol>'+''.join(f'<li><a href="#page-{n}">{escape(t)} <span>{n}</span></a></li>' for n,t in toc)+'</ol></div></section>')
heads=[('Awards','獎項'),('Products and Services of Shiny Diamond Lighting Ltd','公司產品及服務'),('History of Shiny Diamond Lighting Ltd','公司歷史'),('Jobs at Shiny Diamond Lighting Ltd','公司職位'),('3D Projections and Neon','3D 投影與霓虹燈')]
put(3,'<section class="recreated-page conference-notes diamond-notes" aria-label="Wish You Were Here note-taking sheet"><h2>Listening note-taking sheet for the <em>Wish You Were Here</em> podcast</h2><p>Listen to this arts and culture podcast hosted by Julia Din, with guests Pris Fong and Rick Lai.</p><p class="translation" lang="zh-Hant">聆聽 Julia Din 主持、Pris Fong 及 Rick Lai 參與的藝術文化播客。</p><div class="notes-form-body">'+''.join(f'<h3>{escape(en)}</h3><p class="translation" lang="zh-Hant">{zh}</p><textarea data-note="3-{i}" rows="5" aria-label="Notes: {escape(en,quote=True)}"></textarea>' for i,(en,zh) in enumerate(heads,1))+'</div></section>')
p=P[4];z=['Nico：','這星期很忙。你是公關主任，請盡快處理以下文字工作。','第一，Pris Fong 女士想在網站刊登公司簡史：簡述創辦及命名的靈感、夢想如何實現，以及 1990 年起的增長和認可。可參考她的日記和剪報。','第二，回覆 Wan Yuen Estate Residents’ Association 的電郵，解答他們對附近戶外燈光裝置的憂慮。','第三，為 Fong 女士撰寫香港藝術館燈光裝置未來展覽的開幕演說，討論 3D 投影、無人機展示和霓虹燈的持久魅力。她已寫好開場白。','建議收聽《Wish You Were Here》播客，其中有有用資訊。','別忙到「燒保險絲」！','Floyd Mann','總經理']
put(4,'<section class="recreated-page diamond-email" aria-label="Floyd Mann email"><h2>Email from Floyd Mann</h2>'+email('Nico Lin','Floyd Mann','April 26 2022 10:18 AM','Things to do',paras(p,3,12,z))+'</section>')
p=P[5];nz=['香港居民 Pris Fong 上週攀登馬納斯魯峰時險遇不測。獲救後，她說冒險生涯可能結束。','馬納斯魯峰位於尼泊爾喜馬拉雅山脈，海拔 8,163 米，是世界第八高峰，以危險聞名。','Fong 女士受傷後認為，這次經歷啟發她創辦公司，甚至想到公司名稱。','她深深感謝救援人員和加德滿都醫院的醫護。','下週山上預料有暴風雨，登山者獲勸暫避。']
bz=['昨晚我在東京抬頭看到怪東西：太空侵略者、北極光，還是精靈？','都不是。近兩千架無人機像巨大的蜘蛛網照亮夜空，是東京奧運開幕式的一部分。','我有幸與亞洲大型煙火公司 Flashbangs 的行政總裁 Peter O’Rourke 一同觀賞。','他是戶外燈光展示專家；我問他這是否行業未來。','他的回答是：「我不認為。」','真的嗎？我覺得難以置信。','他說，同時編排數千架無人機十分複雜。','而且昂貴。傳統燈光展示暫時不用怕無人機取代。','我們最後一起吃壽司、喝煎茶，和好如初。']
news='<article class="diamond-clipping"><h3>'+escape(p[1])+'</h3><time>'+escape(p[2])+'</time>'+paras(p,3,8,nz)+'</article>'
blog='<article class="diamond-blog"><h3>'+escape(p[9])+'</h3><time>'+escape(p[10])+'</time>'+paras(p,11,20,bz)+'</article>'
put(5,'<section class="recreated-page diamond-press" aria-label="Mountain newspaper clipping and Tokyo travel blog"><h2>Newspaper Clipping from the <em>Hong Kong Newspaper</em></h2>'+news+'<h2>Emily Plays Travel Blog</h2>'+blog+'</section>')
p=P[6];dz=['昨夜在山上險些出事；疼痛、寒冷，不知能否下山，希望這不是最後一篇日記。','漫長而痛苦的一天，嚮導冒生命危險背我下山，我感激自己仍活着。','今天乘直升機去加德滿都醫院，離開時看到陽光下的馬納斯魯峰，畫下難忘景象。','醫生確診嚴重扭傷足踝；需要休養，也開始思考將來。','回香港後我要追逐夢想，創辦製作霓虹燈的公司；公司名稱就在我的素描裡。','回到香港，先去接受訓練，展開新「冒險」。']
entries=''
for idx,date,zh in [(2,1,dz[0]),(4,3,dz[1]),(6,5,dz[2]),(9,8,dz[3]),(11,10,dz[4]),(14,13,dz[5])]:
 entries+=f'<article class="diary-entry"><h3>{escape(p[date])}</h3>{bi(p[idx],zh)}'+('<figure><img src="assets/2022-b2-mountain.webp" alt="Original sketch of Manaslu mountain, sun and diamond"><figcaption>Pris Fong’s mountain sketch</figcaption></figure>' if date==5 else '')+'</article>'
 if date==10:entries+='<p class="diary-ellipsis">……..</p>'
put(6,'<section class="recreated-page diamond-diary" aria-label="Pris Fong diary excerpts"><h2>Extracts from Pris Fong’s Diary</h2><div class="diary-sheet">'+entries+'</div></section>')
p=P[7]
def graph(title,axis,vals,labels):
 # Coordinates are transcribed visually from the original graph, whose middle points have no printed numbers.
 pts=' '.join(f'{48+i*104},{190-v*145/axis:.1f}' for i,v in enumerate(vals))
 return f'<figure class="diamond-graph"><figcaption>{escape(title)}</figcaption><svg viewBox="0 0 380 230" role="img" aria-label="{escape(title,quote=True)}: start {labels[0]}, end {labels[1]}"><g stroke="#b8c8c4" fill="none"><path d="M48 42V190H370"/><path d="M48 190H370M48 153H370M48 116H370M48 79H370M48 42H370"/></g><polyline points="{pts}" fill="none" stroke="#496578" stroke-width="4"/><g fill="#273f42" font-size="13" font-family="Arial"><text x="47" y="210">1990</text><text x="145" y="210">2000</text><text x="250" y="210">2010</text><text x="340" y="210">2022</text><text x="48" y="36">{axis}</text><text x="45" y="166">{labels[0]}</text><text x="345" y="{190-vals[-1]*145/axis-8:.1f}">{labels[1]}</text></g></svg></figure>'
charts=graph('Number of staff (1990–2022)',80,[14,43,40,65],('14','65'))+graph('Profit in millions of HK dollars (1990–2022)',300,[20,135,125,214],('20','214'))
rank1990=['Orion Enterprises','Quasar Technologies','SkyRig','Neon Dreams','Sinthetics'];rank2022=['Quasar Technologies','Shiny Diamond Lighting Ltd','Tyrell Corporation','Orion Enterprises','La Luna Darkside']
rank='<section class="diamond-ranking"><h3>Asia’s Top 5 Largest Lighting Companies</h3><div class="table-scroll"><table><thead><tr><th>Ranking</th><th>1990 · Company</th><th>2022 · Company</th></tr></thead><tbody>'+''.join(f'<tr><th>{i}</th><td>{escape(a)}</td><td>{escape(b)}</td></tr>' for i,(a,b) in enumerate(zip(rank1990,rank2022),1))+'</tbody></table></div></section>'
foot='<aside class="diamond-guidelines"><h4>Footnote · [1] EPD Light Emission Guidelines (extract)</h4><h5>Section 1.8.1 Light Pollution Prevention in Outdoor Lighting Displays</h5><p>Light emitted must not:<br>– exceed levels which interfere with human sleep</p><h5>Section 1.8.2 Safety in Indoor Lighting Displays</h5><p>Light surface temperature must:<br>– be within the range specified by the Fire Services Department</p><p class="translation" lang="zh-Hant">戶外燈光不得強到干擾睡眠；室內燈具表面溫度須符合消防處規定。</p></aside>'
put(7,'<section class="recreated-page diamond-report" aria-label="Shiny Diamond performance report"><h2>Shiny Diamond Performance Report</h2><div class="diamond-report-sheet"><h3>Growth information for investors (as at 31/3/2022)</h3><div class="diamond-charts">'+charts+'</div>'+rank+'<h3>Our commitment</h3>'+bi(p[16],'公司遵守環保署燈光排放指引，承諾為顧客尋找合適的燈光方案。')+foot+'</div></section>')
p=P[8]
survey='<section class="diamond-survey"><h3>2022 Shiny Diamond Customer Survey Results</h3><p>Take note: our recent customer survey speaks for itself!</p><table><thead><tr><th>Question: What do you love most about neon lights?</th><th>Response %</th></tr></thead><tbody><tr><td>Their warm glow.</td><td>93%</td></tr><tr><td>They are old-fashioned.</td><td>2%</td></tr></tbody></table><p class="translation" lang="zh-Hant">93% 喜歡霓虹燈的暖光；2% 選擇「老派」。</p></section>'
brochure='<section class="diamond-brochure"><h3>Shiny Diamond Products Brochure Page</h3><h4>Special Feature: Our Futuristic Lighting Products — 3D-like effects!</h4><div class="diamond-product"><h5>Product name: The Breeze</h5><div class="product-pictures"><img src="assets/2022-b2-breeze-diagram.webp" alt="Original diagram of The Breeze rotating blade of light"><img src="assets/2022-b2-breeze-photo.webp" alt="Original The Breeze 3D-like light effect"></div><p>Rotating ‘blade’ of light · Remarkable 3D-like visuals!</p><p class="translation" lang="zh-Hant">旋轉的光之「葉片」，呈現近似 3D 的視覺效果。</p></div><div class="diamond-product"><h5>Product name: The Wall</h5><div class="product-pictures"><img src="assets/2022-b2-wall-diagram.webp" alt="Original The Wall projection diagram"><img src="assets/2022-b2-wall-photo.webp" alt="Original water-wall projection photo"></div><p>Projection onto ‘wall’ of water — looks just like real 3D!</p><p class="translation" lang="zh-Hant">投影到水牆上，看起來宛如真正的 3D。</p></div><p class="brochure-footer">Ask in store for prices!</p></section>'
put(8,'<section class="recreated-page diamond-brochure-page" aria-label="Customer survey and product brochure">'+survey+brochure+'</section>')
p=P[9];z=['致有關人士：','我們是 Wan Yuen Estate 的居民。Fortune Phoenix Towers 擬安裝由貴公司承辦的 50 米乘 300 米戶外燈光展示，天台並設有旋轉投影立方體。','第一個憂慮是光污染：如此大型的夜間燈光或令面向大廈的住宅如同白晝。','第二是旋轉立方體的安全；2015 年曾有類似裝置倒塌並壓毀汽車，附件為相關新聞。','期待你們盡快回應這些嚴重關注。','此致','Eric Chan，Wan Yuen Estate Residents’ Association 主席']
put(9,'<section class="recreated-page diamond-email" aria-label="Wan Yuen Estate residents email"><h2>Email from Wan Yuen Estate Residents’ Association</h2>'+email('Contact Us @ Shiny Diamond Lighting Ltd','Eric Chan','April 20 2022 11:27 AM','Concerns over Fortune Phoenix Towers Lighting Display',paras(p,3,10,z))+'</section>')
p=P[10];z=['Harold Tsang 上週三早上發現一個五米高燈光裝置壓毀了自己的汽車，嚇了一跳。','他看到閃光並聽到巨響，望出窗外便看到汽車被大型招牌砸毀。','裝置原是保險廣告，從 North Dragon Gardens 的天台鬆脫墜下，無人受傷。','承辦安裝的 Shiny Diamond 代表 Rick Lai 表示，初步相信事故源於保養不足。','獨立工程師團隊其後確認原安裝通過全部安全檢查。','居民 Carol Bodega 說，幸好無人受傷，否則可能有人被壓傷。','大廈管理處拒絕評論。']
put(10,'<section class="recreated-page diamond-press" aria-label="Lighting display accident news attachment"><h2>Attachment to the Wan Yuen Estate Residents’ Association Email</h2><article class="diamond-clipping"><h3>'+escape(p[1])+'</h3><time>'+escape(p[2])+'</time>'+paras(p,3,10,z)+'</article></section>')
p=P[11];z=['Fong 女士詢問居民協會對 Fortune Phoenix Towers 裝置的憂慮是否有道理。','Khatoon 先生認為公司受到不公平指責，並指出法律要求大廈管理處晚上 11 時前調暗戶外燈光。','Lai 先生說，自事故後，公司會與各大廈管理處合作，確保定期保養。','Fong 女士要求回信強調上述事實、提出與居民見面，並表明公司關心附近居民；回應時避免談「過失」和「責任」。','Fong 女士建議公司考慮無人機展示作霓虹燈替代方案，並派發 Emily Plays 的博客。','Lai 先生認同博客的整體看法，雖然展示十分精彩。','Khatoon 先生指出無人機需良好天氣，安全限制令用途有限；顧客調查顯示霓虹燈仍有吸引力，應繼續作重點。','Fong 女士同意，會議結束。']
meta='<dl class="meeting-meta"><dt>Date</dt><dd>Friday 22nd April 2022, 2pm</dd><dt>Venue</dt><dd>Main Conference Room</dd><dt>In attendance</dt><dd>Ms Pris Fong · Mr Bati Khatoon (Installation Team Leader) · Mr Rick Lai (Chief Designer) · Mr Floyd Mann (General Manager)</dd></dl>'
mins='<div class="meeting-sheet"><h3>Meeting Minutes of the Shiny Diamond Management Committee</h3>'+meta+'<h4>'+escape(p[3])+'</h4>'+paras(p,4,8,z[:4])+'<h4>'+escape(p[8])+'</h4>'+paras(p,9,13,z[4:])+'</div>'
put(11,'<section class="recreated-page diamond-minutes" aria-label="Shiny Diamond Management Committee minutes">'+mins+'<p class="source-end">THIS IS THE LAST PAGE OF THE PART B2 DATA FILE</p></section>')
tasks={12:(8,'Company History for Website',18,'Write a short history of Shiny Diamond Lighting Ltd for the company’s website using information from the B2 Data File and your notes. Write around 150 words.','運用乙部二資料檔和筆記，為公司網站撰寫約 150 字的公司簡史。'),14:(9,'Email Response',17,'Write an email responding to the Wan Yuen Estate Residents’ Association using information from the B2 Data File. Write around 170 words.','運用乙部二資料檔，寫約 170 字電郵回覆 Wan Yuen Estate Residents’ Association。'),17:(10,'Speech for Art Museum Opening',18,'Complete the speech using information from the B2 Data File and your notes. The introduction has already been provided for you. Write around 180 words.','運用乙部二資料檔和筆記，接續已提供的開場白，完成約 180 字演說。')}
intro='Ladies and gentlemen, it is an honour to be invited to speak to you at this, the opening of the museum’s new exhibition. The title of my talk is “Lighting the way: what to look forward to in the next 10 years of lighting displays” and there are three main areas I’d like to discuss.'
for n,(task,title,marks,prompt,zh) in tasks.items():
 head='<div class="qab-heading"><span>HKDSE 2022 · ENGLISH LANGUAGE · PAPER 3 PART B2</span><strong>B2 · DIFFICULT SECTION</strong></div>' if n==12 else ''
 extra=('<div class="email-answer-head"><p>To: Mr Chan Kat Yi, Eric</p><p>Subject: Re: Concerns over Fortune Phoenix Towers Lighting Display</p></div>' if n==14 else '')+(bi(intro,'各位先生女士，很榮幸受邀在博物館新展覽開幕之際發言。今天的演講題為「照亮前路：未來十年燈光展示展望」，我會談三個主要方面。') if n==17 else '')
 put(n,f'<section class="recreated-page answer-book diamond-answer" aria-label="Task {task}: {escape(title)}">{head}<h2>Task {task}: {escape(title)} <small>({marks} marks)</small></h2>{bi(prompt,zh)}{extra}{ans(n,"response",title,785)}</section>')
for n,task,end in [(13,8,'END OF TASK 8'),(15,9,''),(16,9,'END OF TASK 9'),(18,10,''),(19,10,'END OF TASK 10 · END OF PART B2')]:
 put(n,f'<section class="recreated-page answer-book diamond-answer" aria-label="Task {task} answer continuation"><h2>Task {task} · Answer continuation</h2><p class="translation" lang="zh-Hant">任務 {task} 續答頁</p>{ans(n,"continuation",f"Task {task} answer continuation",810)}<p class="source-end">{end}</p></section>')
