"""Author the 2016 Social History Museum B2 source as native pages."""
from html import escape
from pathlib import Path
import re
BASE=Path(__file__).resolve().parent;ROOT=BASE/'layouts'
RAW=(BASE/'source/2016-b2-df-clean.txt').read_text()
PAGES={int(n):[x.strip() for x in re.split(r'\n\s*\n',chunk) if x.strip() and not x.strip().startswith('2016-DSE-')] for n,chunk in re.findall(r'(?:^|\n)Page (\d+)\n(.*?)(?=\nPage \d+\n|\Z)',RAW,re.S)}
def put(n,s):(ROOT/f'2016-b2-page-{n:02}.html').write_text(s.rstrip()+'\n',encoding='utf-8')
def norm(s):return re.sub(r'\s+',' ',s.strip())
def bi(en,zh):return f'<div class="bilingual"><p lang="en">{escape(norm(en))}</p><p class="translation" lang="zh-Hant">{escape(zh)}</p></div>'
def ans(n,key,label,height=700):
 ident=f'2016-b2-{n}-{key}'
 return f'<label class="answer-field" for="{ident}">{escape(label)}</label><textarea id="{ident}" class="answer-box" data-note="{n}-{key}" data-count-id="{ident}" style="min-height:{height}px" aria-label="{escape(label,quote=True)}"></textarea><p class="answer-count" data-count-for="{ident}">0 words</p>'
put(1,(ROOT/'2012-b2-page-01.html').read_text().replace('2012','2016'))
p=PAGES[1];situ_zh=['你是 Indy Wong，在香港社會歷史博物館擔任 Lara Gau 的助理；她有幾項工作請你幫忙。','你將聆聽播客《Nosing Around》中 Patty Leung 與 Jack Jones 博士的訪問。','錄音前有五分鐘閱讀問答冊及資料檔，熟悉情境與任務。','按問答冊及錄音指示完成任務。所需資料在問答冊、資料檔和錄音內；聆聽時可在資料檔第 3 頁記筆記。','現在有五分鐘熟悉問答冊及資料檔。']
toc=[(3,'Listening note-taking sheet for podcast Nosing Around'),(4,'Email from Lara Gau to Indy Wong'),(4,'Staff manual on borrowing of items'),(5,'Minutes from museum staff meeting'),(6,'Email from Ip Lai Ping from the Shun Yee Tak Village Hall'),(7,'WhatsApp messages from the Social History Museum group'),(8,'Transcript of interview with Wang Chung Village resident'),(9,'Article from Hong Kong News August 30, 1983'),(9,'Question Wizard online survey results of museum visitors'),(10,'Email from Ms O’Conner')]
put(2,'<section class="recreated-page situation-page" aria-label="Social History Museum situation and contents"><div class="situation-box"><h2>Part B</h2><h3>Situation</h3>'+''.join(bi(x,y) for x,y in zip(p[2:7],situ_zh))+'</div><div class="contents-box"><h3>Contents</h3><ol>'+''.join(f'<li><a href="#page-{n}">{escape(t)} <span>{n}</span></a></li>' for n,t in toc)+'</ol></div></section>')
p=PAGES[2];labels=[('Social History Museum (and directions)','社會歷史博物館及路線'),('Wang Chung Traditional Farmhouse and Village','王涌傳統農舍與村莊'),('Dr Jones’ Talk','Jones 博士的講座'),('Chang Yee Tak Plough','鄭義德犁')]
put(3,'<section class="recreated-page conference-notes" aria-label="Nosing Around note sheet"><h2>Listening note-taking sheet for podcast <em>Nosing Around</em></h2><div class="notes-form-body">'+''.join(f'<h3>{escape(en)}</h3><p class="translation" lang="zh-Hant">{zh}</p><textarea data-note="3-{i}" rows="6" aria-label="Notes: {escape(en,quote=True)}"></textarea>' for i,(en,zh) in enumerate(labels,1))+'</div></section>')
p=PAGES[3];mail_zh=['Indy 你好：','香港近況如何？墨西哥很好玩，回來再告訴你。我外出期間有三件事請你做。','請回覆 Ip 女士有關借用鄭義德犁的電郵，回答她的問題。我們也想拍下犁具放在博物館新海報上，請代為詢問。','請為博物館網站介紹王涌村傳統農舍，說明發現經過、村莊有趣的資料，並簡述農舍廚櫃的奇妙故事。Jones 博士會透過 WhatsApp 提供一些構思。','請為博物館董事會撰寫報告的主要部分，提出館方遇到的問題、相關事件及建議。先參考 O’Conner 女士的電郵和近期職員會議紀錄；正式存檔報告須以段落撰寫。','Lara']
email='<div class="email-window"><div class="email-headers"><div><b>To:</b> Indy Wong</div><div><b>Sent:</b> Fri 8 April 2016 3:14 AM</div><div><b>From:</b> Lara Gau</div><div><b>Subject:</b> Things to do</div></div><div class="email-content">'+''.join(bi(x,y) for x,y in zip(p[2:8],mail_zh))+'</div></div>'
manual_zh=['所有借用的貴重物品必須加罩展示，避免參觀者擅自觸摸或搬動造成損壞後歸咎博物館。','不可聘用沒有相關經驗或未受訓的搬運工。物品的來回運費由博物館支付。','特別借用而不在展廳展示的物品，須存於地下室大型儲物設施並上鎖保管。','博物館須在敲定運輸安排前為借用物品購買保險；保險涵蓋運送及展示期間的損壞。']
manual='<div class="museum-manual"><h3>Section 3.2: Care of borrowed items</h3>'+''.join(f'<h4>{escape(p[i])}</h4>{bi(p[i+1],zh)}' for i,zh in zip((10,12,14,16),manual_zh))+'</div>'
put(4,'<section class="recreated-page museum-email" aria-label="Lara Gau email and staff manual"><h2>Email from Lara Gau to Indy Wong</h2>'+email+'<h2>Staff manual on borrowing of items</h2>'+manual+'</section>')
p=PAGES[4];meeting_zh=['Gau 女士仍在爭取借用鄭義德犁，將回覆借出方的電郵，並徵詢如何令對方放心。','Jones 博士提醒眾人，按政策犁具必須加玻璃罩；他還建議長駐保安員看守，以說服借出方。','Gau 女士同意加玻璃罩，但否決保安員建議；其他委員同意。她問能否在犁具到達前訓練全職職員處理貴重物品。','委員一致同意，並確認所有職員會在展覽前完成訓練。','Jones 博士說董事會關注近期館內多宗事件，要求提交報告；請 Gau 女士和 Howard 先生表達看法。','Howard 先生提到訪客問題：Chow 先生的報告指出，昨天公眾假期有 13 名訪客先後在洗手間吸煙。','Gau 女士問昨日下午疏散是否與此事有關。','Howard 先生確認吸煙觸發了火警鐘。','Jones 博士提及香港國際小學委員會的投訴，建議職員在學校團體參觀全程隨時提供協助。','兩人同意，但指只有全職職員可全程陪同；兼職職員可製作學校團體工作紙。Jones 博士同意實施。','Howard 先生也請委員參考近期網上問卷的結果。']
put(5,'<section class="recreated-page meeting-minutes museum-minutes" aria-label="Museum staff meeting minutes"><h2>Minutes from museum staff meeting</h2><div class="meeting-sheet"><h3>Staff meeting of the Hong Kong Social History Museum</h3><dl class="meeting-meta"><dt>Date</dt><dd>Tues. April 5, 2016</dd><dt>Venue</dt><dd>Museum Seminar Room 2</dd><dt>Chairperson</dt><dd>Dr Jack Jones, Director</dd><dt>Members</dt><dd>Limahl Howard, Building Management Director; Lara Gau, Public Relations and Retail</dd><dt>Secretary</dt><dd>Cindy Lau</dd></dl><h3>Minutes of meeting</h3>'+''.join(bi(x,y) for x,y in zip(p[5:16],meeting_zh))+'<p>Meeting ended 2:55pm.</p></div></section>')
p=PAGES[5];ipzh=['尊敬的 Gau 女士：','感謝來信請求借用鄭義德犁。決定前，我們需要更多資料。','首先，請說明為何特別希望借用這件犁具。','其次，請說明犁具在館內如何確保安全、如有損毀如何處理，以及運輸安排，包括費用和搬運人員經驗。','期待收到你的回覆。','此致','Ip Lai Ping 女士，順義德村公所負責人，新界']
put(6,'<section class="recreated-page museum-email" aria-label="Ip Lai Ping email"><h2>Email from Ip Lai Ping from the Shun Yee Tak Village Hall</h2><div class="email-window"><div class="email-headers"><div><b>To:</b> Lara Gau</div><div><b>Sent:</b> Fri 1 April 2016 11:36 AM</div><div><b>From:</b> Ip Lai Ping</div><div><b>Subject:</b> Chang Yee Tak Plough</div></div><div class="email-content">'+''.join(bi(x,y) for x,y in zip(p[2:9],ipzh))+'</div></div></section>')
p=PAGES[6];messages=[('Dr Jack Jones',p[2],'Lara 請我記下王涌村、農舍及洪水的資料。水塘水位降至歷史低點後發現農舍。1983 年水災時，廚櫃左門有奇怪字跡。我訪問過認識此事的王女士，逐字稿見連結。','8:08 AM',''),('Dr Jack Jones','','', '8:10 AM','<img src="assets/2016-b2-plough.webp" alt="Original photograph of a traditional Chinese plough with Mrs Wang’s father">'),('Dr Jack Jones',p[8],'這是我找到的傳統中式犁具照片；照片中是受訪女士的父親。','8:12 AM',''),('Lara Gau',p[11],'換個話題：關於洗手間吸煙問題的報告，可否在有人打開洗手間門時播放「禁止吸煙」廣播？','9:27 AM',''),('Dr Jack Jones',p[14],'我喜歡這主意，贊成！','9:57 AM','')]
chat=''.join(f'<div class="museum-bubble"><strong>{escape(name)}</strong>{art}{bi(en,zh) if en else ""}<time>{time}</time></div>' for name,en,zh,time,art in messages)
put(7,'<section class="recreated-page museum-whatsapp" aria-label="Social History Museum WhatsApp group"><h2>WhatsApp messages from the Social History Museum group</h2><div class="whatsapp-sheet">'+chat+'</div></section>')
p=PAGES[7];talkzh=['王涌村很有名，我也聽過珍珠米。你能多說一點嗎？','我父親的珍珠米吸引全中國買家；村中其他農民也一樣。當年需求很大，連富裕家庭也覺得昂貴。','可惜村莊已不在，你能描述它原來的樣子嗎？','村莊很美，市區遊客週末會來看稻田。','對，S 形的田。我有些照片，真美。','我記得王涌村的大水災。','是 1983 年的颱風愛倫嗎？','大概是。兩個靠廚櫃生還的女孩，我認識她們。她們的母親告訴我經過。','她有提到廚櫃門上的刻字嗎？','有，是向觀音祈禱的字。','她們刻在右門嗎？','不是右門，是左門；她們等待救援時刻上的。','原來如此。我記錯了。1990 年後你搬到粉嶺，變化很大嗎？','初時很懷念從前，頭幾年也難以適應城市生活；但粉嶺很好，我參與屋苑居民會並幫助其他人。雖然今年已 79 歲，仍有較年輕的人需要幫忙。我有 14 個孫兒和一個曾孫女，親友最重要；在王涌村和粉嶺都有親友。']
turns=''
for raw,zh in zip(p[2:16],talkzh):
 name,_,body=raw.partition(': ');turns+=f'<div class="museum-interview-turn"><b>{escape(name)}</b>{bi(body,zh)}</div>'
put(8,'<section class="recreated-page museum-interview" aria-label="Wang Chung resident interview transcript"><h2>Transcript of interview with Wang Chung Village resident</h2><p class="interview-url">https://hkshm.org/researchproject14</p><div class="interview-sheet">'+turns+'<p>[Recording ends]</p></div></section>')
p=PAGES[8];article_zh=['颱風愛倫帶來傷亡及破壞，但昨天有兩名小姊妹奇蹟獲救。七歲的李文怡和九歲的李文晴在家遭突發洪水沖毀後，靠着家中漂浮的木廚櫃堅持兩天，等候救援。','女孩母親李太太說，她們祈求觀音相救，禱告得到回應。','救援人員昨晚在新界西北部一處水浸稻田發現姊妹，兩人已與父母團聚。']
news='<article class="museum-news"><h3>Living on a prayer</h3><p>By Jovi Bon · 30th August 1983</p>'+''.join(bi(x,y) for x,y in zip(p[3:6],article_zh))+'</article>'
rows=[('No. of signs','標示數量',[('Too many',3),('Satisfactory',436),('Not enough',13)]),('Size of letters on signs','標示字體大小',[('Too big',7),('Satisfactory',33),('Too small',344)]),('Colour of signs','標示顏色',[('Eye-catching',34),('Satisfactory',1),('Not eye-catching',401)])]
survey='<div class="survey-results-museum"><h3>Question Wizard</h3><table><thead><tr><th>Issue</th><th>Response</th><th>Visitors</th></tr></thead><tbody>'+''.join(f'<tr><th scope="row">{escape(issue)}</th><td>{escape(r)}</td><td>{v}</td></tr>' for issue,_,replies in rows for r,v in replies)+'</tbody></table><p class="translation" lang="zh-Hant">問卷顯示：436 人認為標示數量適中；344 人認為字太小；401 人認為標示顏色不顯眼。</p></div>'
put(9,'<section class="recreated-page museum-news-survey" aria-label="1983 news report and visitor survey"><h2>Article from <em>Hong Kong News</em>, August 30, 1983</h2>'+news+'<h2>Question Wizard online survey results of museum visitors</h2>'+survey+'</section>')
p=PAGES[9];ocon_zh=['尊敬的 Jones 博士：','我代表香港國際小學委員會，就參觀社會歷史博物館的問題提出關注。','首先，我擔心兒童安全。我們一名女學生從大型塑膠牛展品跌下，手臂骨折。館方有責任；一般小學生覺得展品太沉悶，應設置可安全互動的展品，也需要更多職員協助教師。','委員還反映館內標示不足。我們參觀時，有師生因而在閉館時迷失於地下室，請調查。','希望館方盡快處理或回覆這些問題。這些孩子將來可能成為成年訪客，關乎博物館未來。','期待迅速回覆。','此致','O’Conner 女士，St. Sinead’s Girls School 校長，香港國際小學委員會主席']
put(10,'<section class="recreated-page museum-email" aria-label="Ms O’Conner complaint email"><h2>Email from Ms O’Conner</h2><div class="email-window"><div class="email-headers"><div><b>To:</b> Jack Jones</div><div><b>Sent:</b> Sat 2 April 2016 8:46 AM</div><div><b>From:</b> S. O’Conner</div><div><b>Subject:</b> School visits to the Social History Museum</div></div><div class="email-content">'+''.join(bi(x,y) for x,y in zip(p[2:10],ocon_zh))+'</div></div><p class="source-end">THIS IS THE LAST PAGE OF THE PART B2 DATA FILE</p></section>')
tasks=[(11,8,'Email to Ms Ip Lai Ping','Write an email to Ms Ip Lai Ping about the Chang Yee Tak Plough using information from the B2 Data File and your notes. Write around 120 words.','運用乙部二資料檔及筆記，電郵 Ip Lai Ping 女士談借用鄭義德犁，約寫 120 字。','Ip Lai Ping'),(13,9,'Introduction to Wang Chung traditional farmhouse and village','Write an introduction to Wang Chung traditional farmhouse and village for the museum website using information from the B2 Data File and your notes. Write around 150 words.','運用乙部二資料檔及筆記，為博物館網站介紹王涌村傳統農舍及村莊，約寫 150 字。',None),(15,10,'Report to Museum Board','Write the main section of the report to the Museum Board using information from the B2 Data File. Write around 200 words.','運用乙部二資料檔，撰寫呈交博物館董事會報告的主要部分，約寫 200 字。',None)]
for n,task,title,prompt,zh,to in tasks:
 head='<div class="qab-heading"><span>HKDSE 2016 · ENGLISH LANGUAGE · PAPER 3 PART B2</span><strong>B2 · DIFFICULT SECTION</strong></div>' if n==11 else ''
 field=(f'<div class="email-answer-head"><p><b>To:</b> {escape(to)}</p><label><b>Subject:</b> <input data-note="{n}-subject" aria-label="Email subject"></label></div>' if to else '')+ans(n,'response',title,790)
 put(n,f'<section class="recreated-page answer-book museum-answer" aria-label="Task {task}: {escape(title)}">{head}<h2>Task {task}: {escape(title)} <small>(18 marks)</small></h2>{bi(prompt,zh)}{field}</section>')
for n,task,end in [(12,8,'END OF TASK 8'),(14,9,'END OF TASK 9'),(16,10,'END OF TASK 10 · END OF PART B2')]:put(n,f'<section class="recreated-page answer-book museum-answer" aria-label="Task {task} answer continuation"><h2>Task {task} · Answer continuation</h2><p class="translation" lang="zh-Hant">任務 {task} 續答頁</p>{ans(n,"continuation",f"Task {task} answer continuation",820)}<p class="source-end">{end}</p></section>')
