"""Author 2015 Bubblegum B2 as source-specific native documents and QAB fields."""
from html import escape
from pathlib import Path
import re
BASE=Path(__file__).resolve().parent; ROOT=BASE/'layouts'
RAW=(BASE/'source/2015-b2-df-clean.txt').read_text()
PAGES={int(n):[x.strip() for x in re.split(r'\n\s*\n',chunk) if x.strip()] for n,chunk in re.findall(r'PAGE (\d+) / 9\n.*?\n=+\n(.*?)(?=\n=+\nPAGE|\Z)',RAW,re.S)}
def put(n,s):(ROOT/f'2015-b2-page-{n:02}.html').write_text(s.rstrip()+'\n',encoding='utf-8')
def norm(s):return re.sub(r'\s+',' ',s.strip())
def bi(en,zh):return f'<div class="bilingual"><p lang="en">{escape(norm(en))}</p><p class="translation" lang="zh-Hant">{escape(zh)}</p></div>'
def ans(n,key,label,height=600):
 ident=f'2015-b2-{n}-{key}'
 return f'<label class="answer-field" for="{ident}">{escape(label)}</label><textarea id="{ident}" class="answer-box" data-note="{n}-{key}" data-count-id="{ident}" style="min-height:{height}px" aria-label="{escape(label,quote=True)}"></textarea><p class="answer-count" data-count-for="{ident}">0 words</p>'
put(1,(ROOT/'2012-b2-page-01.html').read_text().replace('2012','2015'))
p=PAGES[1];zh=['你是 Starsky Chung，在管理流行樂隊與歌手的國際經理人公司 North Star Artists 工作。','上司 Malcolm Parker 在倫敦辦公室工作，將派英國樂隊 Bubblegum 來港宣傳新唱片；你須照顧樂隊在港行程。','你將聆聽 Malcolm Parker、音樂錄影帶導演 Eduardo de Luca 和你之間的 Skype 電話會議。','錄音前有五分鐘閱讀問答冊和資料檔，熟悉情境及任務。','依照問答冊和錄音指示完成任務。資料見問答冊、資料檔和錄音；聆聽時可在資料檔第 3 頁記筆記。','現在有五分鐘熟悉問答冊與資料檔。']
toc=[(3,'Listening note-taking sheet for the Skype conference on April 2'),(4,'Email from Malcolm Parker to Starsky Chung'),(4,'Information page for Ultimatum Products'),(5,'Bubblegum MyFace Page'),(6,'Email from Anca Ma to Starsky Chung'),(7,'Article from The Hong Kong Economic Times'),(8,'Skype chat between Eduardo de Luca and Malcolm Parker'),(9,'Article from Gossip Week magazine'),(9,'Email from Eduardo de Luca to Malcolm Parker'),(10,'Extract of transcript of UK news programme A Closer Look at the Week’s News')]
put(2,'<section class="recreated-page situation-page bubble-situation" aria-label="Bubblegum situation and contents"><div class="situation-box"><h2>Part B</h2><h3>Situation</h3>'+''.join(bi(x,y) for x,y in zip(p[2:8],zh))+'</div><figure class="bubble-cover-photo"><img src="assets/2015-b2-bubblegum.webp" alt="Original source illustration of Bubblegum band"><figcaption>Bubblegum</figcaption></figure><div class="contents-box"><h3>Contents</h3><ol>'+''.join(f'<li><a href="#page-{n}">{escape(t)} <span>{n}</span></a></li>' for n,t in toc)+'</ol></div></section>')
p=PAGES[2];labels=[('Performance at Atlantic Plaza','Atlantic Plaza 演出'),('Music Video (May 19)','5 月 19 日音樂錄影帶'),('Rules about interviews with band','樂隊訪問規則'),('Merchandise / Souvenirs for Asian Tour','亞洲巡演周邊商品／紀念品')]
put(3,'<section class="recreated-page conference-notes" aria-label="Skype conference note sheet"><h2>'+escape(p[0])+'</h2><div class="notes-form-body">'+''.join(f'<h3>{escape(en)}</h3><p class="translation" lang="zh-Hant">{zh}</p><textarea data-note="3-{i}" rows="6" aria-label="Notes: {escape(en,quote=True)}"></textarea>' for i,(en,zh) in enumerate(labels,1))+'</div></section>')
p=PAGES[3]
emailzh=['親愛的 Starsky：','Bubblegum 五月來港前，我需要你完成幾件事。','請電郵 Ultimatum Products，告訴他們希望製作哪些產品，並索取報價。我會傳給你廠商的資料頁。你也可參考 Bubblegum 的 MyFace 頁面，根據粉絲投票及留言選擇受歡迎的產品；別忘了 Skype 會議內容。','我已讀過 Ma 女士回覆你有關 5 月 19 日在 The Peak Sky Deck 拍攝的查詢。請電郵回答她的疑問及顧慮，說服她批准。','我們還需處理 Mark Nelson 與《Gossip Week》攝影師事件引起的負面宣傳。請為香港粉絲網站寫短文：先簡述事件，再回應雜誌的指稱，最後簡述其他名人遭遇的類似事件。不要直接引述；文章應以事實為主。','Malcolm']
mail='<div class="email-window"><div class="email-headers"><div><b>To:</b> Starsky Chung</div><div><b>From:</b> Malcolm Parker</div><div><b>Date:</b> 14 April 2015</div><div><b>Subject:</b> Things to do</div></div><div class="email-content">'+''.join(bi(x,y) for x,y in zip(p[2:8],emailzh))+'</div></div>'
upzh=['感謝查詢我們的服務。Ultimatum Products 能以具競爭力的價格，製作多種高品質零售產品。','如欲查詢產品製造，請電郵產品部 Daniella Wong 女士，列明所需產品；亦請說明產品將用於甚麼活動，方便我們建議其他產品。','為更準確初步估算製作時間及成本，請列明訂購數量和基本設計特點，例如形狀、物料，以及文字或圖片印在產品哪個位置。']
web='<div class="ultimatum-window"><div class="browser-bar">UP UP　 File　 Edit　 View　 Go　 Bookmarks　 Tools　 Help</div><div class="browser-strip">http://www.ultimatumprod.com</div><header>ULTIMATUM</header><main>'+''.join(bi(x,y) for x,y in zip(p[11:14],upzh))+'</main></div>'
put(4,'<section class="recreated-page bubble-email" aria-label="Malcolm Parker email and Ultimatum Products site"><h2>Email from Malcolm Parker to Starsky Chung</h2>'+mail+'<h2>Information page for Ultimatum Products</h2>'+web+'</section>')
p=PAGES[4];ideas=[('Annie Chan','Cool! Let’s have a selection of Bubblegum clothes.','234','3','希望有不同款式的 Bubblegum 服飾。'),('Zombiegirlz','How about some lipstick for all us girl fans?','5','677','女生粉絲用的唇膏如何？'),('Bubblegirl46','Love to have Bubblegum soft toy animals. So cute!!!','430','2','我想要 Bubblegum 動物毛公仔，太可愛了！'),('SinnyLooper','I love cool temporary tattoos - let’s have Bubblegum tattoos. We can print them on our arms.','899','6','我想要 Bubblegum 暫時性紋身，可印在手臂上。'),('Rita Sanchez','Bubblegum crisps anyone?','1','145','有人想要 Bubblegum 薯片嗎？'),('Pony','I want to have Bubblegum key chains.','567','6','我想要 Bubblegum 鎖匙扣。')]
comments=[('Harry Sun','Clothes are cool. But in different colours, right? Why are they always white!','衣服不錯，但應有不同顏色，不要總是白色。'),('Liam Brown','Yeah - different colours! Good idea! What’s with the lipstick idea!!! Ug!!','不同顏色是好主意；唇膏的主意真差。'),('Nancy Kipkirui','Bubblegum lipstick - horrible!','Bubblegum 唇膏很糟糕！'),('Kashif Chachar','Soft toys are my favourite idea. Love Teddy bears... how about different animals as well?','毛公仔最好；除了泰迪熊，也可做不同動物。'),('Sweet Bean','Awesome idea. Also pandas ’cos Bubblegum are coming to China. And have the Bubblegum logo. Where? On the belly! I’d also buy key chains.','熊貓也很好，因為 Bubblegum 會來中國；把標誌放在公仔肚子上。我也會買鎖匙扣。'),('Maggie Wang','Key chains are cool but metal NOT plastic!!!!','鎖匙扣要金屬的，不要塑膠的。')]
ideahtml=''.join(f'<article class="myface-idea"><b>{escape(u)}</b>{bi(en,zh)}<small>☺ {yes}　☹ {no}</small></article>' for u,en,yes,no,zh in ideas)
commenthtml=''.join(f'<article class="myface-comment"><b>{escape(u)}</b>{bi(en,zh)}</article>' for u,en,zh in comments)
put(5,'<section class="recreated-page bubble-myface" aria-label="Bubblegum MyFace page"><h2>Bubblegum MyFace Page</h2><div class="myface-window"><div class="browser-bar">BG BG　 File　 Edit　 View　 Go　 Bookmarks　 Tools　 Help</div><div class="browser-strip">http://www.myface.bubblegum.hk</div><header><h3>Bubblegum</h3><small>8 days ago</small></header>'+bi(p[3],'Bubblegummers 大家好！我們下月來香港及亞洲，想知道你們喜歡哪些周邊商品和紀念品，請分享建議！')+'<p class="myface-help">Click [add idea] to suggest items　 Click ☺ or ☹ to vote　 Click [comment icon] to leave comments</p><h4>[add idea]</h4><div class="myface-ideas">'+ideahtml+'</div><h4>[comments]</h4>'+commenthtml+'</div></section>')
p=PAGES[5]
mazh={2:'親愛的 Chung 女士：',3:'感謝查詢在 The Peak Sky Deck 拍攝流行音樂錄影帶。董事會仍在商討；坦白說我們通常不接受這類請求，決定前需要更多資料。',4:'請說明為何特別選擇此處拍攝，以及對 Sky Deck 或香港旅遊有何益處。我們也需要實際拍攝詳情，尤其擔心影響營運及保安。請列出超過 40 公斤的重型設備。',5:'此致',6:'Anca Ma 女士',7:'The Peak Sky Deck 經理',9:'親愛的 Ma 女士：',10:'我初步查詢英國樂隊 Bubblegum 可否於今年 5 月 19 日在 The Peak Sky Deck 拍攝影片。',11:'此致',12:'Starsky Chung，North Star Artists 行政主任'}
body=''.join(bi(p[i],mazh[i]) for i in range(2,8))
quoted=''.join(bi(p[i],mazh[i]) for i in range(9,13))
put(6,'<section class="recreated-page bubble-email" aria-label="Anca Ma email and original enquiry"><h2>Email from Anca Ma to Starsky Chung</h2><div class="email-window"><div class="email-headers"><div><b>To:</b> Starsky Chung</div><div><b>From:</b> Anca Ma</div><div><b>Date:</b> 10 April 2015</div><div><b>Subject:</b></div></div><div class="email-content">'+body+'<div class="quoted-email"><h3>----- Original Message -----</h3><p>To: Anca Ma &lt;anca.ma@psd.com.hk&gt;<br>From: Starsky Chung &lt;starsky.chung@northstarartists.com.hk&gt;<br>Date: 2 April, 2015<br>Subject:</p>'+quoted+'</div></div></div></section>')
p=PAGES[6]
newszh={2:'香港旅遊工作小組最近詢問途經香港機場的國際旅客能否認出世界知名地標。結果顯示，許多海外旅客仍不熟悉香港地標。',6:'小組發言人 Harold Tam 上週在記者會評論調查結果。',7:'他指出結果令人失望，香港沒有像紐約自由女神像那樣舉世知名的地標，值得思考如何讓世界認識本港地標。',8:'另一項訪問最近購買外國機票的歐美旅客的調查，問他們最喜歡外遊時哪些活動。'}
rows=[('Statue of Liberty','New York','USA','98%','TV, movies and music videos'),('The Great Wall of China','Beijing','China','94%','TV, movies and music videos'),('Tsim Sha Tsui Clock Tower','Hong Kong','China','31%','tourist brochures'),('The Peak Sky Deck','Hong Kong','China','27%','tourist brochures')]
table='<div class="table-scroll"><table><caption>TABLE 1: Most recognized landmarks in major world cities</caption><thead><tr><th>Landmark</th><th>City</th><th>Country</th><th>% of respondents who recognized it</th><th>Where did they recognize it from?</th></tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{escape(v)}</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div><p class="translation" lang="zh-Hant">地標辨認率：自由女神像 98%、萬里長城 94%、尖沙咀鐘樓 31%、山頂觀景台 27%。前兩者主要從電視、電影和音樂錄影帶認識；香港兩個地標則主要從旅遊小冊子認識。</p>'
svg='''<figure class="landmark-chart"><figcaption>FIGURE 1: Activities most enjoyed by tourists from USA and Europe visiting foreign countries</figcaption><svg viewBox="0 0 500 260" role="img" aria-label="Pie chart in the source: visiting landmarks is the largest segment, shopping is smaller, and relaxing is the smallest"><circle cx="250" cy="128" r="92" fill="#dfe7e5"/><path d="M250 128 L250 36 A92 92 0 1 1 168 169 Z" fill="#637f80" stroke="#fff" stroke-width="2"/><path d="M250 128 L168 169 A92 92 0 0 1 211 45 Z" fill="#a9bcba" stroke="#fff" stroke-width="2"/><path d="M250 128 L211 45 A92 92 0 0 1 250 36 Z" fill="#e1e8e6" stroke="#fff" stroke-width="2"/><text x="192" y="19">Relaxing</text><text x="53" y="155">Shopping</text><text x="350" y="187">Visiting landmarks</text></svg><p class="translation" lang="zh-Hant">圖中最大部分為參觀地標，其次是購物，最小部分為休閒放鬆。原卷沒有標示百分比。</p></figure>'''
put(7,'<section class="recreated-page bubble-newspaper" aria-label="Hong Kong Economic Times article"><h2>Article from <em>The Hong Kong Economic Times</em></h2><article class="economic-sheet"><h3>'+escape(p[1])+'</h3>'+bi(p[2],newszh[2])+table+'<small>SOURCE: © The Hong Kong Tourism Working Group</small>'+''.join(bi(p[i],newszh[i]) for i in (6,7,8))+svg+'<small>SOURCE: © The Hong Kong Tourism Working Group</small></article></section>')
p=PAGES[7]
chatzh=['Starsky 有聯絡 The Peak Sky Deck 嗎？','有，但對方尚未承諾。','真奇怪，我以為他們會熱烈歡迎。','我們要想辦法讓他們放心，拍攝不會造成太多問題。','上週我們在紐約自由女神像拍攝，因粉絲湧至，得另外聘一百名保安。香港要這樣做嗎？','應該不用。香港拍攝地點會保密，不准任何人在 Twitter 或 Facebook 透露；但拍攝時可能需要關閉 Sky Deck。','我們需要關閉整棟建築。不過可建議午夜、營業時間以外拍攝，約六小時完成，像在紐約那樣。','Sky Deck 經理想知道設備重量，你可傳給我嗎？','沒問題。我立刻電郵給你。Mark Nelson 是怎麼回事？《Gossip Week》說他很暴力。','別信那些胡話。Mark 很溫和，從未做過這種事。那位攝影師說謊。','我想你說得對，遲些再談。']
chat=''
for raw,zh in zip(p[3:14],chatzh):
 m=re.match(r'(Eduardo|Malcolm): (.*?)\s+(\d+:\d+ PM)$',raw,re.S)
 if not m:raise ValueError(raw[:80])
 who,msg,clock=m.groups();chat+=f'<div class="skype-message {who.lower()}"><strong>{who}</strong>{bi(msg,zh)}<small>{clock}</small></div>'
put(8,'<section class="recreated-page bubble-skype" aria-label="Eduardo and Malcolm Skype chat"><h2>Skype chat between Eduardo de Luca and Malcolm Parker</h2><div class="skype-window"><div class="skype-top">Show messages from: <b>yesterday</b> | 7 days | 30 days | 3 months | 6 months</div><h3>Yesterday, Monday, April 13, 2015</h3>'+chat+'</div></section>')
p=PAGES[8];gzh={2:'「瘋狂 Mark」這次令一名攝影師和自己的名聲都跌進溝渠。',4:'新晉樂隊 Bubblegum 的 Mark Nelson，未來幾週恐怕有事要煩惱。',5:'《Gossip Week》攝影師 Ruari King 聲稱 Nelson 昨天像猛獸般向他撲來。',6:'King 說他在倫敦 Notting Hill 拍名人照片，看到 Mark 後上前拍照，Mark 突然發狂把他推倒。',8:'King 稱自己是名人暴力事件的最新受害者，擔心 Nelson 對他造成的傷害。',9:'他說自己傷勢嚴重，雙腿痛得無法步行，並指控 Nelson 危害辛勤工作的普通人。'}
article='<article class="gossip-sheet"><h3>'+escape(p[1])+'</h3><p class="gossip-deck">'+escape(p[2])+'</p><p class="gossip-byline">'+escape(norm(p[3]))+'</p><figure><img src="assets/2015-b2-photographer.webp" alt="Original photograph accompanying the Gossip Week report"><figcaption>'+escape(p[7].removeprefix('Image caption: '))+'</figcaption></figure>'+''.join(bi(p[i],gzh[i]) for i in (4,5,6,8,9))+'</article>'
raw=p[14].splitlines()[1:];rows=[]
for line in raw:
 if '|' in line:
  a,b=line.split('|',1);rows.append((a.strip(),b.strip()))
equipment='<div class="table-scroll"><table><thead><tr><th>Equipment</th><th>Weight (approx.)</th></tr></thead><tbody>'+''.join(f'<tr><td>{escape(a)}</td><td>{escape(b)}</td></tr>' for a,b in rows)+'</tbody></table></div><p class="translation" lang="zh-Hant">設備重量：兩部相機 6 公斤、攝影吊臂 60 公斤、布幕及支架 10 公斤、樂隊服裝 10 公斤、連支架燈具 45 公斤、化妝箱 3 公斤、咪桿 4 公斤。</p>'
mail='<div class="email-window"><div class="email-headers"><div><b>To:</b> Malcolm Parker</div><div><b>From:</b> Eduardo de Luca</div><div><b>Date:</b> 13 April 2015</div><div><b>Subject:</b> Equipment list</div></div><div class="email-content">'+bi(p[12],'Malcolm 你好：')+bi(p[13],'按你要求，附上拍攝設備清單截圖。')+equipment+bi(p[15],'期待在香港見到你。')+bi(p[16],'再見！')+bi(p[17],'Eduardo')+'</div></div>'
put(9,'<section class="recreated-page bubble-gossip" aria-label="Gossip Week article and Eduardo equipment email"><h2>Article from <em>Gossip Week</em> magazine</h2>'+article+'<h2>Email from Eduardo de Luca to Malcolm Parker</h2>'+mail+'</section>')
p=PAGES[9]
news_zh=['本週報章焦點之一，是名人與狗仔隊的暴力事件。演員 Bernie Lee 仍在康復：他和太太於倫敦南部餐廳用餐時與攝影師發生衝突。','我們剛吃完，攝影師衝進來不停拍照。我叫他離開，他把相機推到我臉前，割傷鼻子，令我翌日的拍攝工作也要取消。','我們越來越關注攝影師的行為，特別是他們對名人的做法。有些名人感到脆弱；歌手 Donna Rae 深夜被跟蹤後非常害怕，曾多次報警。','我不得不報警。他們令我非常憤怒；我需要保護，現在害怕出門。','更令人擔憂的是，有攝影師似乎故意營造名人攻擊自己的假象，最近 Bubblegum 的 Mark Nelson 一案就是例子。','我在家附近邊走邊和女友通電話，一名攝影師把相機貼到我面前不停閃光。他倒著走邊拍照，自己絆倒。我伸手幫他站起來，他卻大叫說我推他；轉眼又站起來四處拍我，真難以置信。']
turns=''
for i,zh in zip((2,4,6,8,10,12),news_zh):turns+=f'<div class="news-turn"><h3>{escape(p[i-1])}</h3>{bi(p[i],zh)}</div>'
put(10,'<section class="recreated-page bubble-transcript" aria-label="A Closer Look at the Week’s News transcript"><h2>Extract of transcript of UK news programme <em>A Closer Look at the Week’s News</em></h2><div class="news-script">'+turns+'</div><p class="source-end">THIS IS THE LAST PAGE OF THE PART B2 DATA FILE</p></section>')

tasks=[(11,8,'Email to Ultimatum Products','Write an email to Ultimatum Products using information from the B2 Data File and your notes. Write around 120 words.','運用乙部二資料檔及筆記，電郵 Ultimatum Products，約寫 120 字。','Daniella Wong (Ultimatum Products)'),(13,9,'Email to The Peak Sky Deck','Write an email to the manager at The Peak Sky Deck using information from the B2 Data File and your notes. Write around 180 words.','運用乙部二資料檔及筆記，電郵 The Peak Sky Deck 經理，約寫 180 字。','Anca Ma'),(15,10,'Article','Write a short article about the incident involving Mark Nelson for the Hong Kong fans’ website using information from the B2 Data File. Write around 200 words.','運用乙部二資料檔，為香港粉絲網站撰寫 Mark Nelson 事件的短文，約寫 200 字。',None)]
for n,task,title,prompt,zh,to in tasks:
 head='<div class="qab-heading"><span>HKDSE 2015 · ENGLISH LANGUAGE · PAPER 3 PART B2</span><strong>B2 · DIFFICULT SECTION</strong></div>' if n==11 else ''
 field=(f'<div class="email-answer-head"><p><b>To:</b> {escape(to)}</p><label><b>Subject:</b> <input data-note="{n}-subject" aria-label="Email subject"></label></div>' if to else '')+ans(n,'response',title,780)
 put(n,f'<section class="recreated-page answer-book bubble-answer" aria-label="Task {task}: {escape(title)}">{head}<h2>Task {task}: {escape(title)} <small>(18 marks)</small></h2>{bi(prompt,zh)}{field}</section>')
for n,task,end in [(12,8,'END OF TASK 8'),(14,9,'END OF TASK 9'),(16,10,'END OF TASK 10 · END OF PART B2')]:put(n,f'<section class="recreated-page answer-book bubble-answer" aria-label="Task {task} answer continuation"><h2>Task {task} · Answer continuation</h2><p class="translation" lang="zh-Hant">任務 {task} 續答頁</p>{ans(n,"continuation",f"Task {task} answer continuation",820)}<p class="source-end">{end}</p></section>')
