"""Source-authored 2014 Paper 3 B2 exotic-pets source documents and QAB."""
from html import escape
from pathlib import Path

ROOT=Path(__file__).resolve().parent/'layouts'
def put(n,s): (ROOT/f'2014-b2-page-{n:02}.html').write_text(s.rstrip()+'\n',encoding='utf-8')
def bi(en,zh): return f'<div class="bilingual"><p lang="en">{escape(en)}</p><p class="translation" lang="zh-Hant">{escape(zh)}</p></div>'
def area(page,key,label,height):
 ident=f'2014-b2-{page}-{key}'
 return f'<label class="answer-field" for="{ident}">{escape(label)}</label><textarea class="answer-box" id="{ident}" data-note="{page}-{key}" data-count-id="{ident}" style="min-height:{height}px" aria-label="{escape(label,quote=True)}"></textarea><p class="answer-count" data-count-for="{ident}">0 words</p>'

cover=(ROOT/'2014-b1-page-01.html').read_text().replace('Part B1','Part B2').replace('PART B1','PART B2').replace('B1','B2').replace('EASY SECTION','DIFFICULT SECTION').replace('乙部一','乙部二')
cover=cover.replace('Part B2 (Tasks 5 – 7)','Part B1 (Tasks 5 – 7)').replace('乙部二（任務 5 至 7）','乙部一（任務 5 至 7）').replace('either B2 or B2','either B1 or B2').replace('乙部二或乙部二','乙部一或乙部二')
put(1,cover)
situation=[('You are Joey Wong. You are an assistant at the Kowloon Exotic Pets Hospital, which takes care of people’s unusual pets. Your boss, Kerry Lam, has asked you to help with the development of the Hospital’s website and other tasks.','你是 Joey Wong，任職於照顧特殊寵物的九龍珍奇寵物醫院。上司 Kerry Lam 請你協助建立醫院網站及處理其他工作。'),('You will listen to a recording of a podcast. In the podcast you will hear an interview with Neelay Shah and Wendy Yee.','你將聆聽一段播客訪問，受訪者是 Neelay Shah 和 Wendy Yee。'),('Before the recording is played, you will have five minutes to study the Question-Answer Book and the Data File for Part B1 and the Question-Answer Book and the Data File for Part B2. Remember you must choose to do the tasks in either Part B1 or Part B2. Do NOT attempt both Parts B1 and B2.','錄音前有五分鐘閱讀乙部一及乙部二的問答冊與資料檔。只須選做其中一部，不要同時作答兩部。'),('Complete the tasks by following the instructions in the Question-Answer Book that you choose and on the recording. You will find all the information you need in the Question-Answer Book and Data File that you choose and on the recording. As you listen you can make notes on page 3 of the Data File.','按你選擇的問答冊及錄音指示完成任務。所需資料在所選問答冊、資料檔及錄音中；可在資料檔第 3 頁記筆記。'),('You now have five minutes to familiarize yourself with the Part B Question-Answer Book and the Data File.','現在有五分鐘熟悉乙部問答冊和資料檔。')]
toc=[(3,'Listening note-taking sheet for the Pet Club podcast'),(4,'Email from Kerry Lam to Joey Wong'),(4,'Statistics from Online Today magazine, November 29, 2013'),(5,'Course Advertisement from Hong Kong Metropolitan University'),(5,'Article from The Gamer magazine'),(6,'Interview excerpt from student podcast: A different kind of nurse!'),(7,'Extract from book: Inside the Virtual Jungle and Pets Online'),(7,'Article from the Hong Kong Times, November 2013'),(8,'Excerpt from the Elderly News magazine'),(9,'Letter in the Kowloon Herald'),(9,'Article from the Hong Kong Telegraph, March 2014'),(10,'Excerpt from Kowloon Exotic Pets Hospital annual report'),(11,'Email from Neelay Shah to Kerry Lam')]
put(2,'<section class="recreated-page situation-page" aria-label="2014 B2 situation and contents"><div class="situation-box"><h2>Part B</h2><h3>Situation</h3>'+''.join(bi(*p) for p in situation)+'</div><div class="contents-box"><h3>Contents</h3><ol>'+''.join(f'<li><a href="#page-{n}">{escape(t)} <span>{n}</span></a></li>' for n,t in toc)+'</ol></div></section>')

notes=[('Exotic pets — Definition','珍奇寵物：定義'),('Reasons to have an exotic pet','飼養珍奇寵物的原因'),('Examples of exotic pets in Hong Kong','香港珍奇寵物的例子'),('Email 1','電郵一'),('Email 2','電郵二'),('Advice for exotic pet owners','給珍奇寵物主人的建議')]
put(3,'<section class="recreated-page conference-notes" aria-label="Pet Club podcast notes"><h2>Listening note-taking sheet for the <em>Pet Club</em> podcast</h2><div class="notes-form-body">'+''.join(f'<h3>{escape(en)}</h3><p class="translation" lang="zh-Hant">{escape(zh)}</p><textarea data-note="3-{i}" rows="5" aria-label="Notes: {escape(en,quote=True)}"></textarea>' for i,(en,zh) in enumerate(notes,1))+'</div></section>')

kerry=[('Dear Joey,','Joey：'),('I’d like your help with a few things.','我有幾件事想請你幫忙。'),('We’re updating our website and we’ve decided to include an information page which has advice for young people or school leavers on becoming a veterinary nurse. Please can you write this page? You might want to include information about:','我們正在更新網站，計劃加入資訊頁，向年輕人或離校生介紹如何成為獸醫護士。請你撰寫，可涵蓋：'),('Please give a title. You may want to start by checking your notes from the Pet Club podcast.','請加上標題。可先查看《Pet Club》播客的筆記。'),('Next month, we’re going to have an open day and I’m going to give a speech and I’d like you to write it for me. As we’re thinking about having a virtual pet page on our website, I’d like to talk about virtual pets. Please include a brief background on virtual pets and focus on how old people use virtual pets. I suggest that you start by looking at that ‘Inside the Virtual Jungle’ book.','下月我們將舉辦開放日；我會發表演說，請你代筆。網站也在考慮虛擬寵物專頁，因此我想談虛擬寵物。簡述背景，重點說明長者如何使用虛擬寵物；可參考《Inside the Virtual Jungle》。'),('Please write a letter to the editor of the Kowloon Herald in response to the letter from Mr. W. Squeers, which criticizes the Kowloon Exotic Pets Hospital. Make sure you mention all of the voluntary work we do for the community in Hong Kong. You might want to start by looking at Mr. Squeers’ letter in the Kowloon Herald.','請寫信給《Kowloon Herald》編輯，回應 W. Squeers 先生批評醫院的來信。務必提及我們為香港社區提供的所有義務服務。可先讀他的來信。'),('Thanks for your help.','謝謝幫忙。')]
chart='<figure class="virtual-pet-chart"><figcaption>Virtual Pet Users by Age</figcaption><div class="pie" role="img" aria-label="Under 18: 37%; 18–29: 17%; 30–65: 20%; Over 65: 26%"></div><ul><li>Under 18 — 37%</li><li>18–29 — 17%</li><li>30–65 — 20%</li><li>Over 65 — 26%</li></ul><p class="translation" lang="zh-Hant">虛擬寵物玩家年齡：未滿 18 歲佔 37%；18–29 歲佔 17%；30–65 歲佔 20%；65 歲以上佔 26%。</p></figure>'
put(4,'<section class="recreated-page exotic-email-chart" aria-label="Kerry Lam email and Online Today age chart"><h2>Email from Kerry Lam to Joey Wong</h2><div class="email-window"><div class="email-headers"><div><strong>To:</strong> Joey Wong</div><div><strong>From:</strong> Kerry Lam</div><div><strong>Date:</strong> 12 April, 2014</div><div><strong>Subject:</strong> Work to be done</div></div><div class="email-content">'+''.join(bi(*p) for p in kerry[:3])+'<ul><li>what veterinary nurses do and professional qualities they need</li><li>qualifications and future prospects</li><li>challenges</li></ul><p class="translation" lang="zh-Hant">獸醫護士的職責和所需專業素質；資格與發展前景；工作挑戰。</p>'+''.join(bi(*p) for p in kerry[3:])+'<p>Kerry</p></div></div><h2>Statistics from <em>Online Today</em> magazine, November 29, 2013</h2>'+chart+'</section>')

ad=[('Here at Hong Kong Metropolitan University we have been training veterinary nurses for over 7 years. Our teaching staff come from all over the world, including New Zealand, South Africa and Russia. Our programmes are designed to train you in all the skills necessary to be a veterinary nurse. You’ll also study communication and the course includes a six-month internship (local or overseas). You can choose from a full-time degree, diploma or certificate programme. Just click here for more details.','香港大都會大學培訓獸醫護士逾七年，教師來自紐西蘭、南非、俄羅斯等地。課程涵蓋獸醫護士所需技能、溝通技巧，以及為期六個月的本地或海外實習。可選全日制學位、文憑或證書課程。'),('See below for what some of our recent graduates are doing:','以下是部分近年畢業生的發展：')]
graduates=[('I’ve got a placement as a veterinary nurse in a horse clinic. Being able to specialize like this will hopefully be the key to my future career.','我在馬匹診所獲得獸醫護士職位，希望這種專科經驗有助未來發展。','2014-b2-graduate-horse.webp'),('I wasn’t sure about whether I really wanted to be a vet, so I did the diploma course first. In September I’m going to start studying full-time to become a vet!','我原本未確定是否想做獸醫，所以先修讀文憑課程。九月將開始全日制獸醫學習！','2014-b2-graduate-vet.webp')]
gamer=[('My spies tell me that the world of gaming has taken an unusual turn this week. The story is that there’s a community of old people in Florida, USA doing some serious game time to collect online virtual pets of all things. Mrs Crannery, a retired teacher, 76, explains it this way:','據報美國佛羅里達州有一群長者投入遊戲，收集網上的虛擬寵物。76 歲退休教師 Crannery 太太解釋：'),('Well, we got into the online stuff like the virtual pet thing and car racing games to keep our minds active as we get older. We do the usual things with our virtual pets. I’ve got two horses. It’s certainly better than spending your time on those card playing games sites.','我們玩虛擬寵物和賽車遊戲，是為了年紀漸長時保持頭腦活躍。我有兩匹虛擬馬，總比只玩網上紙牌好。'),('More news from the busy elderly virtual pet breeders – here’s more from Perry Schmidt, our virtual pets expert: ‘new websites are appearing where, believe it or not readers, owners are cross-breeding animals and creating, like, super pets!’','虛擬寵物專家 Perry Schmidt 說，新網站讓主人雜交動物，創造出「超級寵物」。'),('One is a Draglion – a cross between a lion and a Komodo dragon, imagine that! Lots of excitement about this because it’s so super unusual. No one knows what these elderly gamers will come up with next but you can bet, we’ll keep ya posted!','例如獅子與科莫多龍雜交的 Draglion。大家因其奇特而興奮，未來這群長者還會創造甚麼，令人期待。')]
put(5,'<section class="recreated-page exotic-course-gamer" aria-label="Veterinary course advertisement and Gamer article"><h2>Course Advertisement from Hong Kong Metropolitan University</h2><div class="course-ad"><h3>Train to be a Veterinary Nurse</h3>'+''.join(bi(*p) for p in ad)+''.join('<div class="graduate"><img src="assets/'+img+'" alt="Original veterinary graduate photograph">'+bi(en,zh)+'</div>' for en,zh,img in graduates)+'</div><h2>Article from <em>The Gamer</em> magazine</h2><article class="gamer-article"><h3>Grandmothers with virtual pets?!</h3>'+''.join(bi(*p) for p in gamer)+'</article></section>')

talk=[('Host','We’re lucky enough today to be sitting with three new graduates from the School of Veterinary Medicine at King George University, Canada. They’ve all just completed their course in Veterinary Nursing. Please welcome Ian McBain, Randall Worthing and Candy Tse. Okay, let’s start with the easy question: What is a veterinary nurse? What do you do?','今天我們訪問加拿大 King George University 獸醫學院的三位獸醫護理畢業生：Ian McBain、Randall Worthing 和 Candy Tse。獸醫護士是做甚麼的？'),('Ian','Well, most obviously we provide care and support for animals when they get sick.','我們在動物生病時提供護理與支持。'),('Host','Okay. Great. So, you just finished your training. What do you think the best bit of being a veterinary nurse is going to be then?','你們剛完成培訓，最期待這份工作的哪部分？'),('Ian','I think the clinical duties. In the training, we did so many different things. We even got to do minor surgical procedures. I did a cat that had been in a fight.','我期待臨床職責。培訓中接觸許多工作，甚至做過小型手術。我處理過一隻打架受傷的貓。'),('Randall','Yeah, I had to do some dental cleaning!','我做過牙齒清潔！'),('Candy','I’ve not done that. What animal was it?','我還沒做過。是哪種動物？'),('Randall','A rabbit!','一隻兔子！'),('Host','And from what you’ve seen in your internships, what were the challenges of being a trainee veterinary nurse?','你們實習時遇到甚麼挑戰？'),('Candy','I think it was learning not to be nervous with animals.','我得學會在動物面前不緊張。'),('Host','Was that hard?','難嗎？'),('Candy','At first, but it got better — I asked the experienced nurses for tips and copied them!','起初難，但後來改善了。我向資深護士請教並學習他們的做法。'),('Ian','For me it was the shift work, you know, I had to be on call at night. Make sure you go to bed on time. That’s my advice!','對我而言是輪班，晚上也要候命。我的建議是準時睡覺！'),('Host','How about you, Randall?','Randall，你呢？'),('Randall','The biggest challenge for me personally was when a sick animal died. I had to learn to develop a strategy to cope with that one.','最大的挑戰是病重動物死亡，我得學會應對。'),('Candy','Yeah, that’s a tough one.','對，那很難受。'),('Host','Okay, let’s move on — what about the future? What can you do now? Any plans?','接下來談談將來。你們有甚麼計劃？')]
put(6,'<section class="recreated-page interview-page exotic-podcast" aria-label="Veterinary nursing student podcast transcript"><h2>Interview excerpt from student podcast: <em>A different kind of nurse!</em></h2><div class="transcript-sheet">'+''.join('<div class="podcast-turn"><strong>'+escape(who)+':</strong>'+bi(en,zh)+'</div>' for who,en,zh in talk)+'</div></section>')

book=[('The usage of virtual pets¹ has similarly increased with widespread, cheaper access to the internet (e.g. Alessi 2005; Cheng and Lewis 2012). In this connection, Y’Ev (2011) examined the use of virtual pets amongst adult users aged 60 and over in Hong Kong. The findings reveal that users usually become interested in virtual pets for a variety of reasons, as illustrated in the comments from these focus group participants:','隨著網絡更普及、價格更低，虛擬寵物的使用也增加。Y’Ev 研究了香港 60 歲或以上成年人，發現長者接觸虛擬寵物有不同原因。'),('It started out with me and my grandson, he’d come to stay and he taught me how to use the computer and then how to have a virtual pet, it’s wonderful. (May, 88, Mong Kok)','最初是孫兒教我用電腦和養虛擬寵物，很棒。（旺角，88 歲 May）'),('I really wanted a dog, but wasn’t allowed one in my apartment building so I got an online pet. Simple as that. (Wing, 68, Mei Fu)','我很想養狗，但大廈不准，於是養網上寵物。（美孚，68 歲 Wing）')]
fish=[('Have you been for a walk in a Hong Kong park recently? Did you see something big swimming in the water of the pond? Perhaps you have seen one of the notorious alligator gars. An alligator gar is a species of non-native fish which is threatening local native fish. Mr. Neelay Shah from the AFCD explains more. ‘Our studies have found that we are seeing fewer local fish in streams, ponds and lakes because the alligator gar is becoming dominant; they eat the local fish.’','你在香港公園池塘或許見過鱷雀鱔。這種外來魚威脅本地魚；漁護署的 Neelay Shah 說，牠們吃本地魚，令溪流和池塘的本地魚數量減少。'),('But how did they get there? ‘They’re released by owners after they buy them from pet shops, grow them and then they become too big to keep,’ says Mr. Shah. ‘We need to get the message out that releasing exotic pets like these into the wild is not a good idea. Eight months ago the Kowloon Exotic Pets Hospital started a scheme called Operation Gar. The hospital helps us by volunteering their services to relocate gars to Ocean Park. We are also in the middle of a joint campaign with the hospital that provides free workshops to educate people about the threat to the ecosystem if something is released into the wild. Check www.kexoticpets.com.hk or our website for details.’','主人從寵物店買魚，養大後因無法繼續飼養而放生。Shah 強調不應把珍奇寵物放到野外。八個月前醫院展開 Operation Gar，義務協助漁護署把鱷雀鱔遷往海洋公園，並合辦免費工作坊，教育公眾放生對生態系統的威脅。')]
put(7,'<section class="recreated-page exotic-book-fish" aria-label="Virtual pets book and Hong Kong Times article"><h2>Extract from book: <em>Inside the Virtual Jungle and Pets Online</em></h2><article class="academic-extract">'+bi(*book[0])+''.join('<blockquote>'+bi(*p)+'</blockquote>' for p in book[1:])+bi('¹ In this chapter, the definition of a virtual pet will follow that of Kohonen et al. (2010: xix), i.e. “a digital application which simulates online the experience of having a real pet.”','本章依 Kohonen 等人（2010）的定義：虛擬寵物是模擬真實飼養寵物經驗的網上數碼應用程式。')+'</article><h2>Article from the <em>Hong Kong Times</em>, November 2013</h2><article class="newspaper-sheet"><h3>Foreign fish fall foul of the law</h3>'+''.join(bi(*p) for p in fish)+'</article></section>')

elderly_intro=('After all the fuss about Generation Y and the numerous reports in the media about the older generation not being able to do the simple things online, we asked you, our readers, to get in touch and tell us what you are doing online. To prove a point, and to provide a little challenge, we asked you to contact us — by SMS! Here are some samples from the hundreds of text messages we received. Congratulations to everyone who contacted us. Just shows that us oldies can still learn new tricks!','傳媒常說長者連簡單網上操作也做不到，因此我們請讀者透過短訊告訴大家如何使用網絡。以下選出數百則回覆中的幾則，證明長者也能學新事物。')
sms=[('Eileen, 76, London','I do everything online now — the shopping, talking to my grandchildren, my banking. I wish I’d had all of this when I was younger.','我現在上網購物、與孫兒聊天、處理銀行事務。真希望年輕時已有這些。'),('Kam, 80, Hong Kong','I’ve built up a pretty extensive breeding exchange programme of virtual birds online. Although I don’t trade them for money, I swap them for other birds I haven’t got.','我建立了龐大的網上虛擬雀鳥繁殖交換計劃。雖不賣錢，但會交換未擁有的雀鳥。'),('Patrice, 66, France','I’ve used the Internet to trace my family tree back four hundred years and found cousins I didn’t know I had on the other side of the world. We’re now in regular touch — all online!','我在網上追溯四百年家族史，找到身處世界另一端、從未知道的表親；如今定期網上聯絡。'),('Bill, 69, Chicago','Me and my friends have got about 6 online accounts each with different virtual pet sites and we breed virtual cats. We’re selling them to other online breeders. I tell you, we can make about 50 dollars a month each — good money if you’re retired.','我和朋友各有約六個不同虛擬寵物網站帳戶，繁殖虛擬貓再賣給其他玩家。每人每月約賺 50 美元，對退休人士不錯。'),('Winnie, 72, Kansas','I keep virtual horses online with my husband. We’ve got a virtual ranch called Ponderosa. We’re the oldest virtual horse whisperers on the web!','我和丈夫養虛擬馬，還有一座名叫 Ponderosa 的虛擬牧場。我們大概是網上最年長的「馬語者」！')]
put(8,'<section class="recreated-page exotic-elderly" aria-label="Elderly News magazine feature"><h2>Excerpt from the <em>Elderly News</em> magazine</h2><article><h3>Talking about the digital generation?</h3>'+bi(*elderly_intro)+'<div class="elderly-messages">'+''.join(f'<blockquote>{bi(en,zh)}<cite>{escape(name)}</cite></blockquote>' for name,en,zh in sms)+'</div></article></section>')

letter=[('March 23, 2014','2014 年 3 月 23 日'),('Dear Editor,','編輯先生／女士：'),('I’m writing to express my anger about the Kowloon Exotic Pets Hospital. This hospital supports the exotic pet trade. It is doing this by helping people keep exotic pets and is only concerned about making money. It should be shut down immediately.','我對九龍珍奇寵物醫院非常不滿。它幫人飼養珍奇寵物，支持相關貿易，只顧賺錢，應立即關閉。'),('The trade in some exotic pets can have some serious effects. What if a pet owner no longer wants their pet and lets it go into the wild? This damages the ecosystem. Just look at the recent Hong Kong Times story about the alligator gars. Another point is that some exotic animals carry diseases and this can put the public in danger.','珍奇寵物貿易可能造成嚴重後果。主人棄養放生會破壞生態，鱷雀鱔便是例子。有些珍奇動物亦攜帶疾病，危及公眾。'),('I’m sure that others will agree with me.','我相信其他人也同意。'),('Yours faithfully,','此致'),('Mr. W. Squeers','W. Squeers 先生')]
orphan=[('A recent arrival in Hong Kong has found a home after receiving an unfriendly welcome from a local family. Danny, a 0.8 metre corn snake was bought in a pet shop in Tsim Sha Tsui last month by a 16-year-old school student.','一條新來港的 0.8 米玉米蛇 Danny 被本地家庭棄養後找到了新家；牠上月由一名 16 歲學生在尖沙咀寵物店購買。'),('‘They just came into the clinic and gave me a bag with a snake in it!’ said Max Tong, the local vet. ‘So I rang my friends at the Kowloon Exotic Pets Hospital. They have a free programme; it’s fantastic — they take in all kinds of unwanted exotic pets and look after them until a new home can be found.’','獸醫 Max Tong 說，家庭把裝蛇的袋交到診所，他便聯絡九龍珍奇寵物醫院。醫院的免費計劃收留各種被棄養的珍奇寵物，照顧牠們直到找到新家。'),('Kerry Lam, from the Kowloon Exotic Pets Hospital explains, ‘There’s no way any exotic pet should be homeless, otherwise they can end up in the wild in Hong Kong. We’ll take any animal, no questions asked, and it’s all completely free of charge.’','醫院的 Kerry Lam 說，珍奇寵物不應無家可歸，否則可能流入香港野外。醫院免費接收任何動物，不追問原因。')]
put(9,'<section class="recreated-page exotic-letter-news" aria-label="Kowloon Herald letter and Telegraph orphan report"><h2>Letter in the <em>Kowloon Herald</em></h2><article class="letter-sheet">'+''.join(bi(*p) for p in letter)+'</article><h2>Article from the <em>Hong Kong Telegraph</em>, March 2014</h2><article class="newspaper-sheet"><h3>Orphan Pet Finds Hope</h3>'+''.join(bi(*p) for p in orphan)+'</article></section>')

report1=('This year the Orphan Programme was again run as a complimentary service to the community. The Orphan Programme Committee reports a summary of cases handled in the last five years (see Figure 1, below). A request has been put forward for one extra member of staff to be involved in the Programme on a full-time basis. It is this board’s recommendation that the funding requirement be discussed at the next Annual General Meeting scheduled for May, 2014.','本年度「孤兒計劃」繼續免費服務社區。委員會報告過去五年的個案數，並提出增聘一名全職員工。董事會建議於 2014 年 5 月的週年大會討論經費。')
report2=('As part of the latest government drive in this area (see press release in Appendix 6), two full-time vets from the Hospital have been working with Mr. Neelay Shah from the Agriculture, Fisheries and Conservation Department in the last financial year. Their duties included, most notably, assisting the AFCD vets in raids on pet shops throughout Hong Kong in crimes related to exotic pets (see also Appendix 7). The Hospital envisages that such operations will continue in the next financial year.','配合政府最新行動，醫院兩名全職獸醫過去財政年度與漁護署 Neelay Shah 合作，包括協助突擊搜查涉嫌珍奇寵物罪行的寵物店。醫院預計下年度會繼續相關行動。')
bars=[(2009,23),(2010,44),(2011,43),(2012,75),(2013,109)]
svg='<svg class="orphan-chart" viewBox="0 0 640 350" role="img" aria-label="Cases handled by Orphan Programme rose from about 23 in 2009 to about 109 in 2013">'
for tick in range(0,121,20):
 y=288-tick*2
 svg+=f'<line x1="75" y1="{y}" x2="610" y2="{y}" stroke="#c2ccca"/><text x="50" y="{y+5}" font-size="15">{tick}</text>'
for i,(year,n) in enumerate(bars):
 x=110+i*103;h=n*2;y=288-h
 svg+=f'<rect x="{x}" y="{y}" width="51" height="{h}" fill="#66787a"/><text x="{x+5}" y="314" font-size="15">{year}</text>'
svg+='<text x="330" y="345" text-anchor="middle" font-size="15">Year</text><text transform="translate(18 200) rotate(-90)" font-size="15">Number of cases</text></svg>'
put(10,'<section class="recreated-page exotic-annual" aria-label="Kowloon Exotic Pets Hospital annual report"><h2>Excerpt from Kowloon Exotic Pets Hospital annual report</h2><article class="annual-sheet"><h3>6.1 Free Orphan Programme</h3>'+bi(*report1)+'<figure>'+svg+'<figcaption>Figure 1: Cases Handled (2009–2013)</figcaption></figure><p class="translation" lang="zh-Hant">圖一：2009 至 2013 年處理個案數持續上升。</p><h3>6.2 Voluntary Operations with Hong Kong Government</h3>'+bi(*report2)+'</article></section>')

neelay=[('Dear Kerry,','Kerry：'),('I’m writing to thank everyone at the Kowloon Exotic Pets Hospital for volunteering to help with the recent AFCD open day. The exhibition you provided was really very educational — all the kids seemed to enjoy meeting the spiders and snakes. I particularly like the way you’re helping us get the message across to the community that the incidence of disease with exotic pets is low if care is taken when they are handled. People need to be educated about this not frightened by the tabloid press about it.','感謝醫院義務協助漁護署最近的開放日。你們的展覽十分有教育意義，孩子們也很喜歡接觸蜘蛛和蛇。你們幫忙向社區說明，只要小心處理珍奇寵物，染病機會很低；公眾需要教育，不應被小報嚇倒。'),('Thanks for all your help, Kerry.','Kerry，謝謝你們的幫忙。'),('Best regards,','此致')]
put(11,'<section class="recreated-page exotic-thanks" aria-label="AFCD thank-you email"><h2>Email from Neelay Shah to Kerry Lam</h2><div class="email-window"><div class="email-headers"><div><strong>To:</strong> Kerry Lam</div><div><strong>From:</strong> Neelay Shah</div><div><strong>Subject:</strong> Thank you for helping with AFCD open day</div></div><div class="email-content">'+''.join(bi(*p) for p in neelay)+'<p>Neelay Shah<br>Agriculture, Fisheries and Conservation Department<br>The Government of the Hong Kong SAR</p></div></div><p class="end-note">THIS IS THE LAST PAGE OF THE PART B2 DATA FILE</p></section>')

def write_page(n,task,title,lead,zh,height=730,end=''):
 return '<section class="recreated-page answer-book exotic-answer" aria-label="2014 B2 Question-Answer Book page '+str(n-11)+'"><h3>'+escape(task)+' <small>(18 marks)</small></h3>'+bi(lead,zh)+(f'<h4>{escape(title)}</h4>' if title else '')+area(n,f'task-{task.split()[1].rstrip(":")}',task,height)+(f'<p class="answer-end">{end}</p>' if end else '')+'</section>'
put(12,'<section class="recreated-page answer-book exotic-answer" aria-label="2014 B2 Question-Answer Book page 1"><div class="answer-book-header"><span>HKDSE 2014 · ENGLISH LANGUAGE · PAPER 3 PART B2 · Question-Answer Book</span><strong>B2</strong></div><h3>Task 8: Information page <small>(18 marks)</small></h3>'+bi('Write your information page using information from the B2 Data File and your notes. Write around 150 words.','利用乙部二資料檔和筆記撰寫約 150 字的資訊頁。')+area(12,'information','Task 8 information page',700)+'</section>')
put(13,'<section class="recreated-page answer-book exotic-answer" aria-label="2014 B2 Question-Answer Book page 2"><h3>Task 8: Information page, continued</h3><p class="translation" lang="zh-Hant">任務 8：資訊頁續頁。</p>'+area(13,'information-cont','Continue the information page',690)+'<p class="answer-end">END OF TASK 8</p></section>')
put(14,'<section class="recreated-page answer-book exotic-answer" aria-label="2014 B2 Question-Answer Book page 3"><h3>Task 9: Speech <small>(18 marks)</small></h3>'+bi('Write your speech using information from the B2 Data File. Write around 150 words.','利用乙部二資料檔撰寫約 150 字的演說稿。')+'<h4>Virtual Pets and their Elderly Owners</h4>'+area(14,'speech','Task 9 speech',730)+'</section>')
put(15,'<section class="recreated-page answer-book exotic-answer" aria-label="2014 B2 Question-Answer Book page 4"><h3>Task 9: Speech, continued</h3><p class="translation" lang="zh-Hant">任務 9：演說稿續頁。</p>'+area(15,'speech-cont','Continue the speech',690)+'<p class="answer-end">END OF TASK 9</p></section>')
put(16,'<section class="recreated-page answer-book exotic-answer" aria-label="2014 B2 Question-Answer Book page 5"><h3>Task 10: Letter to the editor <small>(18 marks)</small></h3>'+bi('Write your letter to the editor using information from the B2 Data File and your notes. You do not need to include addresses. Write around 200 words.','利用乙部二資料檔和筆記撰寫約 200 字的讀者來函；毋須寫地址。')+area(16,'letter','Task 10 letter to the editor',730)+'</section>')
put(17,'<section class="recreated-page answer-book exotic-answer" aria-label="2014 B2 Question-Answer Book page 6"><h3>Task 10: Letter to the editor, continued</h3><p class="translation" lang="zh-Hant">任務 10：讀者來函續頁。</p>'+area(17,'letter-cont','Continue the letter to the editor',690)+'<p class="answer-end">END OF TASK 10<br>END OF PART B2</p></section>')
