"""Source-authored 2022 B1 neon-light documents, chats, leaflet and product page."""
from html import escape
from pathlib import Path

ROOT=Path(__file__).resolve().parent/'layouts'
def put(n,s): (ROOT/f'2022-b1-page-{n:02}.html').write_text(s.rstrip()+'\n',encoding='utf-8')
def bi(en,zh): return f'<div class="bilingual"><p lang="en">{escape(en)}</p><p class="translation" lang="zh-Hant">{escape(zh)}</p></div>'
def inp(n,label): return f'<input data-note="14-{n}" aria-label="{escape(label,quote=True)}">'
def area(n,label,height): return f'<textarea class="answer-box" data-note="{n}" style="min-height:{height}px" aria-label="{escape(label,quote=True)}"></textarea>'

put(1,(ROOT/'2018-b1-page-01.html').read_text().replace('2018','2022'))
situation=[('You are Nico Lin. You work for Shiny Diamond Lighting Ltd, a company that designs, makes and sells neon lighting products and services. Your work involves writing and editing texts for company use. Your boss, Floyd Mann, has asked you to do some tasks.','你是 Nico Lin，在設計、製造和銷售霓虹燈產品及服務的 Shiny Diamond Lighting Ltd 工作，負責撰寫和編輯公司文字。上司 Floyd Mann 指派你一些工作。'),('You will listen to a podcast of Wish You Were Here, an arts and culture radio programme on Hong Kong Radio. On the podcast you will hear Julia Din interview Pris Fong, owner of Shiny Diamond Lighting Ltd, and her chief designer and neon artist Rick Lai.','你將聆聽香港電台文化藝術節目《Wish You Were Here》的播客。主持 Julia Din 訪問公司東主 Pris Fong、首席設計師兼霓虹藝術家 Rick Lai。'),('Before the recording is played, you will have five minutes to study the Question-Answer Book and the Data File to familiarise yourself with the situation and the tasks.','錄音前有五分鐘閱讀問答冊和資料檔，熟悉情境與任務。'),('Complete the tasks by following the instructions in the Question-Answer Book and on the recording. You will find all the information you need in the Question-Answer Book, the Data File and on the recording. As you listen you can make notes on page 3 of the Data File.','請依問答冊及錄音指示完成任務。所有所需資料都在問答冊、資料檔和錄音中；可在資料檔第 3 頁記筆記。'),('You now have five minutes to familiarise yourself with the Question-Answer Book and the Data File.','現在有五分鐘熟悉問答冊和資料檔。')]
toc=[(3,'Listening note-taking sheet for the Wish You Were Here podcast'),(4,'Email from Floyd Mann to Nico Lin'),(5,'Customer Comments on the Shiny Diamond Website'),(6,'Messages from the Shiny Diamond Management WhatsApp Group – Chat 1'),(7,'Messages from the Shiny Diamond Management WhatsApp Group – Chat 2'),(8,'Inventory from Previous Stock Take'),(9,'Shiny Diamond Company Handbook (Extracts)'),(10,'Interview with Neon Master Rick Lai in Hong Kong Arts and Crafts Magazine')]
put(2,'<section class="recreated-page situation-page" aria-label="2022 Part B situation and contents"><div class="situation-box"><h2>Part B</h2><h3>Situation</h3>'+''.join(bi(*p) for p in situation)+'</div><div class="contents-box"><h3>Contents</h3><ol>'+''.join(f'<li><a href="#page-{n}">{escape(t)} <span>{n}</span></a></li>' for n,t in toc)+'</ol></div></section>')

note_heads=[('History of Shiny Diamond Lighting Ltd','Shiny Diamond Lighting Ltd 的歷史'),('Awards','獎項'),('Products and Services of Shiny Diamond Lighting Ltd','公司的產品與服務'),('3D Projections and Neon','3D 投影與霓虹燈')]
put(3,'<section class="recreated-page conference-notes" aria-label="Wish You Were Here podcast notes"><h2>Listening note-taking sheet for the <em>Wish You Were Here</em> podcast</h2>'+bi('Listen to this arts and culture podcast hosted by Julia Din, with guests Pris Fong and Rick Lai.','聆聽由 Julia Din 主持、Pris Fong 和 Rick Lai 作嘉賓的文化藝術播客。')+'<div class="notes-form-body">'+''.join(f'<h3>{escape(en)}</h3><p class="translation" lang="zh-Hant">{escape(zh)}</p><textarea data-note="3-{i}" rows="6" aria-label="Notes: {escape(en,quote=True)}"></textarea>' for i,(en,zh) in enumerate(note_heads,1))+'</div></section>')

mail=[('Dear Nico,','Nico：'),('Busy week I’m afraid. As Public Relations Officer, can you apply your magic with words and get onto the following things ASAP?','恐怕這週很忙。作為公關主任，請發揮你的文字功力，盡快處理以下工作。'),('First, write an email to the students at the Hong Kong Design School to encourage them to apply to join Shiny Diamond Lighting Ltd as trainees. Write it so that it gets their interest and is clear about how they should apply. Listen to the Wish You Were Here podcast, and look at the company handbook and Rick Lai’s interview in the Hong Kong Arts and Crafts magazine for details.','先寫電郵給香港設計學校的學生，鼓勵他們申請成為公司的培訓生。內容要吸引他們，並清楚說明申請方法。可參考播客、公司手冊和《Hong Kong Arts and Crafts》對 Rick Lai 的訪問。'),('Next, Pris wants us to make a how-to leaflet to be given out to customers when they visit our neon light factory. I have put in the pictures, but you will need to finish the text. Use full sentences and don’t use bullet points! Take a look at the company handbook and Rick Lai’s interview in the Hong Kong Arts and Crafts magazine.','接着，Pris 想製作參觀霓虹燈工廠時派發給客人的製作指南。我已放入圖片，請你完成文字。要用完整句子，不要用項目符號！參考公司手冊和 Rick Lai 的訪問。'),('Finally, we need to update the webpage for our products. Look at the inventory from the previous stock take and the company handbook. Rick Lai and Pris Fong also discuss some product details on the Wish You Were Here podcast.','最後，我們需要更新產品網頁。參考上次盤點清單、公司手冊，以及播客中 Rick Lai 和 Pris Fong 談及的產品資料。'),('I’ve noticed customers discussing our products in the Customer Comments section of our website. That might help you with some of these tasks. Rick Lai and Pris Fong were also discussing all of these tasks on the Management WhatsApp group — I’ll forward the messages to you.','我注意到客人在網站留言區討論產品，或許對部分任務有幫助。Rick Lai 和 Pris Fong 也在管理層 WhatsApp 群組討論，我會轉發訊息給你。'),('Don’t blow a fuse!','別把保險絲燒掉了！')]
put(4,'<section class="recreated-page email-document" aria-label="Floyd Mann email to Nico Lin"><h2>Email from Floyd Mann to Nico Lin</h2><div class="email-window"><div class="email-tabs"><span>File</span><span>Message</span></div><div class="email-toolbar">'+''.join(f'<span>{x}</span>' for x in ['Junk','Delete','Reply','Reply All','Forward','Move','Mark Unread','Follow up'])+'</div><div class="email-headers"><div><strong>To:</strong> Nico Lin</div><div><strong>Sent:</strong> April 26 2022 10:18 AM</div><div><strong>From:</strong> Floyd Mann</div><div><strong>Subject:</strong> Things to do</div></div><div class="email-content">'+''.join(bi(*p) for p in mail)+'<p>Floyd Mann<br>General Manager</p></div></div></section>')

comments=[('LA2019AD','Thank you so much Shiny Diamond. You’re the best! Our wedding photos were such a success because of the neon sign background. I’d recommend everyone to have a neon sign in the background when taking photos.','非常感謝 Shiny Diamond！婚禮相片因霓虹燈背景而十分成功。我推薦大家拍照時用霓虹燈作背景。',[('SpinnerBoy','Totally agree. Excellent photo backgrounds.','完全同意，是很棒的拍照背景。'),('TyrellsNeice','Thumbs up!','讚！')]),('Voidkompf','What I love most about these neon signs is that you can place them on a table.','我最喜歡的是這些霓虹燈可以放在桌上。',[('AlanLaddjr','Brilliant idea.','好主意。'),('DaveG','I’ve got two signs on my table at home.','我家桌上有兩塊霓虹燈牌。')])]
put(5,'<section class="recreated-page neon-comments" aria-label="Shiny Diamond customer comments"><h2>Customer Comments on the Shiny Diamond Website</h2>'+''.join('<article class="neon-comment"><strong>'+escape(user)+':</strong>'+bi(en,zh)+'<h3>Replies</h3>'+''.join('<div class="neon-reply"><strong>'+escape(u)+': </strong>'+bi(e,z)+'</div>' for u,e,z in replies)+'</article>' for user,en,zh,replies in comments)+'</section>')

chat1=[('Floyd','Hi Nico! These are the messages about the Recruitment Email and the How-to Leaflet.','Nico，以下訊息與招聘電郵和製作指南有關。'),('Rick','We’re asking Nico to write the trainee recruitment email. What’s a good way to start the email? I mean, how can we attract the most creative candidates?','我們請 Nico 寫培訓生招聘電郵。開頭怎樣寫才能吸引最有創意的應徵者？'),('Pris','Begin with a question. Get them curious.','用問題開頭，引起他們好奇。'),('Rick','What kind of question?','問甚麼問題？'),('Pris','How about asking them if they enjoy making things with their hands?','不如問他們是否喜歡親手製作東西？'),('Rick','Great idea. That will make a big impact, right at the beginning of the email. And how do they apply?','好主意，電郵一開始就能留下深刻印象。他們如何申請？'),('Pris','They can simply reply to the recruitment email.','直接回覆招聘電郵即可。'),('Rick','Of course! We should definitely include that. I have another question about the How-to Leaflet.','當然！一定要寫進去。關於製作指南我還有一個問題。'),('Pris','Shoot.','說吧。'),('Rick','Should we mention where customers can hang their signs? In the “display” section, I mean.','我們要在「展示」部分寫明客人可以把燈牌掛在哪裏嗎？'),('Pris','Sure. They can hang the signs on a wall. Wait: where else do customers place their signs?','當然。他們可以掛在牆上。等等，客人還會把燈牌放在哪裏？'),('Rick','Let me check the Customer Comments.','讓我看看客人留言。')]
chat2=[('Floyd','Nico — these are the messages about the Webpage for Products. Thanks.','Nico，以下訊息與產品網頁有關。謝謝。'),('Pris','On the webpage, I’ve added a 10% discount on the Hong Kong Skyline design.','我在網頁上為香港天際線款式加了九折優惠。'),('Rick','Are you sure you want to do that?','你確定嗎？'),('Pris','Yes — we need to get more interest in the product.','確定，我們要讓更多人對產品感興趣。'),('Rick','OK, we can. But it’ll reduce our profit.','可以，但利潤會減少。'),('Pris','Good point. How about we only have the discount for the first 20 orders? That’ll get people more interested, but allow us to make money later.','說得對。不如只給首 20 張訂單折扣？既能吸引顧客，之後也能賺錢。'),('Rick','OK, sounds good. Get Nico to add that to the section on price.','好，叫 Nico 加到價格一欄。'),('Pris','Speaking of which, did you get Nico to add an example answer for the FAQ on what messages customers can write?','說起來，你有叫 Nico 在常見問題加入可寫訊息的範例嗎？'),('Rick','Not yet. Was it “Love lives forever!” we were going to use?','還沒有。原本打算用「Love lives forever!」嗎？'),('Pris','Yes, that’s right. It’s our most popular message by far. Another FAQ is about the delivery time. Are we down to 1 month now?','對，那是最受歡迎的訊息。另一個常見問題是送貨時間，現在縮短至一個月了嗎？'),('Rick','Even better - we can deliver in around 3 weeks.','更快，大約三星期就能送達。'),('Pris','One more thing on the customer-designed signs. Does the webpage state which file format customers should use to upload their design?','還有自訂燈牌：網頁有寫客人上載設計時應用甚麼檔案格式嗎？'),('Rick','I wasn’t sure, so I left it blank. It should be JPEG files, right?','我不肯定，所以留空了。應該是 JPEG 吧？'),('Pris','Yes, and PNG files too.','對，也可以用 PNG。')]
def chat(title,lines): return '<section class="recreated-page two-group-chats neon-chat" aria-label="'+escape(title,quote=True)+'"><h2>'+escape(title)+'</h2><div class="chat-conversation"><h3>Shiny Diamond Management</h3><div class="chat-shell">'+''.join(f'<div class="chat-bubble {"outgoing" if who=="Pris" else ""}"><strong>{who}</strong>{bi(en,zh)}</div>' for who,en,zh in lines)+'</div></div></section>'
put(6,chat('Messages from the Shiny Diamond Management WhatsApp Group — Chat 1',chat1))
put(7,chat('Messages from Shiny Diamond Management WhatsApp Group — Chat 2',chat2))
# Page 8 has its separately authored inventory table.

handbook=[('2.1 Planning the sign — process:',['Download customer design','Give it to the lighting designer']),('2.2 Making the sign — machines used:',['The Glass Heater','The cleaning machine']),('2.3 Displaying the sign:',['Fix the glass tubes onto a solid surface']),('6.1 Trainee Applicants',['Experience in sculpture needed','Must provide evidence of previous work']),('6.2 Interviews',['Successful applicants will be shortlisted','These will be invited to an interview'])]
put(9,'<section class="recreated-page neon-handbook" aria-label="Shiny Diamond company handbook"><h2>Shiny Diamond Company Handbook (Extracts)</h2><div class="handbook-sheet"><h3>2. Overview of Production Process (Customer Design)</h3>'+''.join(f'<section><h4>{escape(h)}</h4><ul>'+''.join(f'<li>{escape(item)}</li>' for item in items)+'</ul></section>' for h,items in handbook[:3])+'<h3>6. Training and Recruitment</h3>'+''.join(f'<section><h4>{escape(h)}</h4><ul>'+''.join(f'<li>{escape(item)}</li>' for item in items)+'</ul></section>' for h,items in handbook[3:])+'</div><p class="translation" lang="zh-Hant">製作流程：下載客人的設計、交給燈光設計師；用加熱及清潔機器處理玻璃管，再固定於堅固表面。培訓生須有雕塑經驗和作品證明；合資格申請者會獲面試邀請。</p></section>')

interview=[('Hong Kong Arts and Crafts','What do you enjoy most about your work?','你最喜歡工作中的哪一部分？'),('Rick Lai','There are many aspects to the job I enjoy but what I love most is taking a customer’s design and turning it into a neon sign. It’s quite a complicated process. Basically, in the planning stage, when we receive the design, we use a grid.','這份工作有許多我喜歡的部分，但我最喜歡把客人的設計變成霓虹燈牌。過程相當複雜；規劃時收到設計，我們會使用方格。'),('Hong Kong Arts and Crafts','Why do you do that?','為甚麼？'),('Rick Lai','We use it to decide how many glass tubes we need. That’s all before we start making the sign using a machine called the Glass Heater.','方格讓我們計算需要多少玻璃管，之後才用「玻璃加熱器」製作燈牌。'),('Hong Kong Arts and Crafts','What does that do?','這機器有甚麼用？'),('Rick Lai','We use it to bend the glass tubes. We then have another machine which cleans the glass tubes.','用來彎曲玻璃管；之後另一部機器會清潔玻璃管。'),('Hong Kong Arts and Crafts','How does it get them clean?','它怎樣清潔？'),('Rick Lai','It uses electricity. Shocking, right? Also, whenever we move the glass tubes, they can be broken very easily so we have to be very, very careful with them. That’s the boring part for me, because I like to work quickly! Finally, we are also very careful to test if the tubes are working before we move on to the display stage. One time, a customer returned a faulty sign. It was so embarrassing!','用電力清潔。很意外吧？玻璃管搬動時很容易破，所以必須非常小心。我喜歡做事快，這是我覺得無聊的部分。到展示階段前還要仔細測試玻璃管；有一次客人退回故障燈牌，真令人尷尬！'),('Hong Kong Arts and Crafts','What is the future for lighting design in Hong Kong?','香港燈光設計的前景如何？'),('Rick Lai','It’s very bright! We are looking for trainees at the moment, so if any of your readers are interested, please apply to be a trainee.','前景非常光明！我們正在招聘培訓生，有興趣的讀者可以申請。'),('Hong Kong Arts and Crafts','How can they apply?','他們如何申請？'),('Rick Lai','The instructions will be in recruitment emails we are sending out soon. One thing to pay attention to, though: applicants must send us 4 or 5 photos of their previous work. That way, we can really get a feel for their ability.','申請方法會寫在即將寄出的招聘電郵。請注意：申請者必須提交四至五張過往作品相片，讓我們了解其能力。')]
put(10,'<section class="recreated-page interview-page neon-interview" aria-label="Rick Lai magazine interview"><h2>Interview with Neon Master Rick Lai in <em>Hong Kong Arts and Crafts Magazine</em></h2><div class="transcript-sheet">'+bi('We spoke with Rick Lai, Hong Kong’s top lighting designer, who works for the award-winning Shiny Diamond Lighting Ltd.','我們訪問了香港頂尖燈光設計師 Rick Lai；他任職於屢獲殊榮的 Shiny Diamond Lighting Ltd。')+''.join(f'<div class="interview-turn"><strong>{escape(who)}:</strong>{bi(en,zh)}</div>' for who,en,zh in interview)+'</div><p class="end-note">THIS IS THE LAST PAGE OF THE PART B1 DATA FILE</p></section>')

put(11,'<section class="recreated-page answer-book neon-recruitment" aria-label="2022 B1 QAB recruitment email"><div class="answer-book-header"><span>HKDSE 2022 · ENGLISH LANGUAGE · PAPER 3 PART B1 · Question-Answer Book</span><strong>B1</strong></div><h3>Task 5: Recruitment Email <small>(18 marks)</small></h3>'+bi('Write an email to students at the Hong Kong Design School using information from the B1 Data File and your notes. Write around 100 words.','利用乙部一資料檔和筆記，寫一封約 100 字的電郵給香港設計學校學生。')+'<div class="answer-email-head"><p><strong>To:</strong> Hong Kong Design School Students</p><p><strong>Subject:</strong> An Exciting Opportunity!</p></div><p>Dear Student,</p>'+area('11-email','Recruitment email',650)+'</section>')

put(12,'<section class="recreated-page answer-book neon-leaflet" aria-label="2022 B1 QAB how-to leaflet first page"><h3>Task 5: Recruitment Email, continued</h3>'+area('12-email-cont','Recruitment email continuation',230)+'<p class="answer-end">END OF TASK 5</p><h3>Task 6: How-to Leaflet <small>(18 marks)</small></h3>'+bi('Complete the leaflet using information from the B1 Data File. Write around 120 words.','利用乙部一資料檔完成約 120 字的製作指南。')+'<div class="leaflet-sheet"><h4>Have you ever wondered how a neon sign is made?<br>Find out below!</h4><h5>Planning the sign</h5><div class="leaflet-art"><img src="assets/2022-b1-planning-art.webp" alt="Original sketch of a designer drawing a sign"><img src="assets/2022-b1-grid-art.webp" alt="Original OPEN design on a grid"></div>'+area('12-planning','Planning the sign',350)+'</div></section>')
put(13,'<section class="recreated-page answer-book neon-leaflet" aria-label="2022 B1 QAB how-to leaflet second page"><div class="leaflet-sheet"><h5>Making the sign</h5><div class="leaflet-art"><img src="assets/2022-b1-making-art.webp" alt="Original illustration of a glassworker making a neon sign"></div>'+area('13-making','Making the sign',440)+'<h5>Displaying the sign</h5><div class="leaflet-art"><img src="assets/2022-b1-display-art.webp" alt="Original OPEN neon sign illustration"></div>'+area('13-displaying','Displaying the sign',350)+'</div><p class="answer-end">END OF TASK 6</p></section>')

product_rows=[('Don’t Panic!','2022-b1-dont-panic.webp','2','Colour(s)','3','Size','HK$400','Sorry! Just sold out.'),('U.F.O.','2022-b1-ufo.webp','4','Colour(s)','6','Small size','HK$900 (large); 5. HK$ '+inp(5,'Small UFO price')+' (small)','In stock – order now!'),('Hong Kong Skyline','2022-b1-skyline.webp',None,'Buildings are orange, pink and purple.',None,'200 by 120cm','HK$2000; 7. 10% Discount '+inp(7,'Discount condition'),'8. Date available: '+inp(8,'Availability date'))]
def product_row(row):
 name,img,c1,t1,c2,t2,price,avail=row
 colour=(f'{c1}. '+inp(c1,t1)) if c1 else escape(t1)
 size=(f'{c2}. '+inp(c2,t2)) if c2 else escape(t2)
 return '<tr><th><img src="assets/'+img+'" alt="Original '+escape(name,quote=True)+' neon design"><br>'+escape(name)+'</th><td>'+colour+'</td><td>'+price+'</td><td>'+size+'</td><td>'+avail+'</td></tr>'
custom=[('Weddings','2022-b1-love.webp','9. These are perfect to use as '+inp(9,'Wedding sign use')),('Birthdays','2022-b1-cake.webp','10. On the cake we will put '+inp(10,'Birthday cake wording')+' of the birthday boy or girl.'),('Shops','2022-b1-open.webp','11. We make signs for '+inp(11,'Types of shops'))]
prod='<div class="neon-product-page"><header><strong>Shiny Diamond Lighting Ltd</strong>　1. Winner of '+inp(1,'Award')+'</header><h4>Our Popular Indoor Neon Light Designs</h4><div class="table-scroll"><table><thead><tr><th></th><th>Colour(s)</th><th>Price</th><th>Size</th><th>Availability</th></tr></thead><tbody>'+''.join(product_row(r) for r in product_rows)+'</tbody></table></div><h4>We can make YOUR design</h4>'+''.join(f'<section class="custom-product"><img src="assets/{img}" alt="Original {name} neon artwork"><p><strong>{name}</strong>　{body}</p></section>' for name,img,body in custom)+'<h4>Frequently-Asked Questions (FAQs)</h4><div class="faq-row"><strong>What message can I write?</strong><span>A popular example is: 12. '+inp(12,'Popular message')+'</span></div><div class="faq-row"><strong>When will it be delivered?</strong><span>Usually it takes around 13. '+inp(13,'Delivery time')+'</span></div><div class="faq-row">Upload your design here (Format: 14. '+inp(14,'Image file formats')+' files)</div></div>'
put(14,'<section class="recreated-page answer-book neon-products" aria-label="2022 B1 QAB product webpage"><h3>Task 7: Webpage for Products <small>(17 marks)</small></h3>'+bi('Complete the webpage using information from the B1 Data File and your notes.','利用乙部一資料檔和筆記完成產品網頁。')+prod+'<p class="answer-end">END OF TASK 7<br>END OF PART B1</p></section>')
