"""Source-specific native reconstruction of 2020 Star Pod Paper 3 B2."""
from pathlib import Path
from html import escape
import re
B=Path(__file__).resolve().parent;L=B/'layouts';RAW=(B/'source/2020-b2-df-clean.txt').read_text();a=re.split(r'=+\nPAGE (\d+) / 10\n=+\n',RAW)
P={int(a[i]):[re.sub(r'\s+',' ',x.strip()) for x in a[i+1].split('\n\n') if x.strip()] for i in range(1,len(a),2)}
def put(n,s):(L/f'2020-b2-page-{n:02}.html').write_text(s.rstrip()+'\n')
def bi(x,z):return f'<div class="bilingual"><p lang="en">{escape(x)}</p><p class="translation" lang="zh-Hant">{escape(z)}</p></div>'
def ps(p,a,b,z):
 assert len(p[a:b])==len(z),(a,b,z)
 return ''.join(bi(x,y) for x,y in zip(p[a:b],z))
def ans(n,k,label,h=730):
 i=f'2020-b2-{n}-{k}';return f'<label class="answer-field" for="{i}">{escape(label)}</label><textarea id="{i}" class="answer-box" data-note="{n}-{k}" data-count-id="{i}" style="min-height:{h}px"></textarea><p class="answer-count" data-count-for="{i}">0 words</p>'
def email(to,fr,sent,sub,body):return '<div class="email-window"><div class="email-toolbar">File　 Message　 Junk　 Delete　 Reply　 Reply All　 Forward　 Move　 Mark Unread　 Follow up</div><div class="email-headers">'+''.join(f'<div><b>{k}:</b> {escape(v)}</div>' for k,v in [('To',to),('From',fr),('Sent',sent),('Subject',sub)])+'</div><div class="email-content">'+body+'</div></div>'
cover=(L/'2017-b2-page-01.html').read_text().replace('2017','2020');put(1,cover)
p=P[1];z=['你是 Nico Lin，任職推廣太空探索及為兒童舉辦冒險營的 Star Pod，是總監 Ellen Ochoa 的助理。','你會聽 Star Pod 播客，Ellen Ochoa 與 Captain Trillion Choi 及 Professor Marvin Adams 對話；請在適當標題下記筆記。','錄音前有五分鐘閱讀問答冊和資料檔，熟悉情境與任務。','按問答冊及錄音指示完成任務；所需資料在問答冊、資料檔及錄音中，聽時可在資料檔第 3 頁記筆記。','現在有五分鐘熟悉問答冊及資料檔。']
toc=[(3,'Listening note-taking sheet for the Star Pod podcast'),(4,'Email from Ellen Ochoa to Nico Lin'),(5,'Minutes of Management Committee meeting'),(6,'Planet Tarkov Problem-Solving Activity PowerPoint slide from last year'),(6,'Standard Medical Examination Form'),(7,'Instructors’ feedback from last year’s Planet Tarkov Problem-Solving Activity'),(8,'Letter from Locae Foundation'),(9,'Multi-Axis Trainer (M.A.T.) Engineering Assessment by Scotty Wong'),(10,'Star Pod Website'),(11,'Space Capsule Transport Feasibility Assessment by Scotty Wong')]
put(2,'<section class="recreated-page situation-page" aria-label="Star Pod situation and contents"><div class="situation-box"><h2>Part B</h2><h3>Situation</h3>'+ps(p,2,7,z)+'</div><div class="contents-box"><h3>Contents</h3><ol>'+''.join(f'<li><a href="#page-{n}">{escape(t)} <span>{n}</span></a></li>' for n,t in toc)+'</ol></div></section>')
heads=[('Dangers of Mars: Oxygen','火星危險：氧氣'),('Dangers of Mars: Temperature','火星危險：溫度'),('Dangers of Mars: Dust storms','火星危險：沙塵暴'),('Tarkov','Tarkov 星球'),('Star Pod Adventure Camp','Star Pod 冒險營'),('Open Day','開放日')]
put(3,'<section class="recreated-page conference-notes" aria-label="Star Pod podcast note sheet"><h2>'+escape(P[2][0])+'</h2>'+bi(P[2][1],'聆聽 Ellen Ochoa 與 Captain Trillion Choi、Professor Marvin Adams 的播客對話。')+'<div class="notes-form-body">'+''.join(f'<h3>{escape(x)}</h3><p class="translation" lang="zh-Hant">{z}</p><textarea data-note="3-{i}" rows="5" aria-label="Notes: {escape(x,quote=True)}"></textarea>' for i,(x,z) in enumerate(heads,1))+'</div></section>')
p=P[3];z=['Nico 你好：','今週需要你做個真正的英雄。','第一，撰寫一段活潑精彩的影片開場稿，向兒童介紹 Tarkov 問題解決活動；參考管理委員會會議紀錄及 Marvin Adams 教授在播客中的說法。','第二，為管理委員會撰寫 M.A.T. 意外報告：交代女孩經歷、醫生結論、工程師對故障的解釋，以及議定建議。','第三，婉拒 Locae Foundation 的請求，解釋原因並提出公司可提供的支持，語氣要體貼。','倒數開始！十、九、八……','Ellen']
put(4,'<section class="recreated-page star-email" aria-label="Ellen Ochoa email"><h2>Email from Ellen Ochoa to Nico Lin</h2>'+email('Nico Lin','Ellen Ochoa','Fri 3 April 2020 9:02AM','Things to do',ps(p,3,10,z))+'</section>')
p=P[4];z=['Chawla 女士提醒委員會：去年用作介紹 Tarkov 活動的投影片將改為影片，並請大家參考導師的改善意見及她的批註。','Ochoa 女士同意這些批註，會請 Nico 按意見修改影片稿。','Wong 先生報告多軸訓練器的工程檢查；Ochoa 女士另建議修剪建築物上方樹枝，並確認屋頂會用矽膠密封。','Ochoa 女士提及 Locae Foundation 的來信；Wong 先生介紹太空艙運送可行性評估。','Ochoa 女士認同評估結論；她私下提到財政困難，認為應更明智用錢。','Chawla 女士建議邀請慈善機構成為開放日貴賓，與特別嘉賓午膳，並給予太空艙的專屬參觀機會。','Wong 先生指出 M.A.T. 仍在維修，故只可開放太空艙。']
meta='<dl class="meeting-meta"><dt>Date</dt><dd>30th March 2020, 3:00 PM</dd><dt>Venue</dt><dd>Meeting Room 101</dd><dt>In attendance</dt><dd>Ms Ellen Ochoa · Ms Sunita Chawla · Mr Scotty Wong · Mr Bowie Ma</dd></dl>'
mins='<div class="meeting-sheet"><h3>Minutes of Management Committee meeting</h3>'+meta+'<h4>'+escape(p[3])+'</h4>'+ps(p,4,6,z[:2])+'<h4>'+escape(p[6])+'</h4>'+bi(p[7],z[2])+'<h4>'+escape(p[8])+'</h4>'+ps(p,9,13,z[3:])+'</div>'
put(5,'<section class="recreated-page star-minutes" aria-label="Management Committee minutes">'+mins+'</section>')
p=P[5];slide='<div class="star-slide"><h3>Planet Tarkov Problem-Solving Activity</h3><img src="assets/2020-b2-logo.webp" alt="Original Star Pod logo"><h4>Background:</h4><ul><li>You are crew on colony spaceship heading to LV-426</li><li>Colony spaceship hit by comet<br>Stop at Tarkov for repairs</li><li>Repairs will take 1 x year</li><li>You arrive in Spring on Tarkov</li></ul><h4>Extreme seasons on Planet Tarkov:</h4><ul><li>Summer</li><li>Winter</li></ul><h4>Grouping and Timing:</h4><ul><li>10 people per group</li><li>30 mins discuss, 3 mins present ideas to everyone</li></ul><p class="translation" lang="zh-Hant">去年版本：太空船遭彗星撞擊，停在 Tarkov 維修一年；每組十人，討論三十分鐘、匯報三分鐘。</p></div>'
medlines=['“Can you tell me if you have any discomfort?”','“Yes, doctor. My head. It really hurts.”','“I see. A headache, yes?”','“Yes, doctor.”','“And what would you say caused this?”','“Being stuck in that machine. The M.A.T.. It was horrible. Stuck like that.”','“Like what?”','“You know, upside down.”','“How long were you like that then?”','“About thirty seconds.”']
medical='<div class="star-medical"><h3>Standard Medical Examination Form</h3><img src="assets/2020-b2-logo.webp" alt="Original Star Pod logo"><dl><dt>Patient’s Name</dt><dd>Ms Rey Liu</dd><dt>Age</dt><dd>11</dd><dt>Doctor</dt><dd>Dr Xixi Yang</dd><dt>Date</dt><dd>26th March 2020</dd></dl><h4>Description:</h4><p>The patient arrived in my office at 10:15 am complaining of a severe headache. See transcript below.</p><div class="medical-dialogue">'+''.join(f'<p>{escape(x)}</p>' for x in medlines)+'</div><p class="translation" lang="zh-Hant">Rey Liu 說，她被困在倒轉的 M.A.T. 約三十秒，之後劇烈頭痛。</p><h4>Conclusions:</h4>'+bi('As a precautionary measure, I called her parents and then I took her to Waglan Memorial Hospital, where no issues regarding her health were observed.','醫生通知家長並送她到醫院；檢查未發現健康問題。')+'</div>'
put(6,'<section class="recreated-page star-slide-med" aria-label="Tarkov slide and medical form"><h2>Planet Tarkov Problem-Solving Activity PowerPoint slide from last year</h2>'+slide+'<h2>Standard Medical Examination Form</h2>'+medical+'</section>')
p=P[6];fz=['簡化情境：直接說他們墜落 Tarkov；目標改成撐過一年等待救援。','同意全部採納。','把每組十人減為五人，活動延長至兩小時；另建議加入更多物理知識。','同意人數及時間調整，但不要把活動變成科學課。','建議做 3D 模型；保留春天抵達；另加入更多科學背景。','3D 模型無預算，亦不想變成科學課。','須讓學生明白 Tarkov 夏冬兩季有多極端，加入有趣事實。','同意，請天文學家 Marvin Adams 提供資料。']
rows=''
for i in range(4):
 rows+=f'<tr><th>Instructor {i+1}<div>{bi(re.sub(r'^Instructor \d+ ', '', p[2+i*2]),fz[i*2])}</div></th><td>{bi(re.sub(r'^Sunita Chawla’s Comments: ', '', p[3+i*2]),fz[i*2+1])}</td></tr>'
put(7,'<section class="recreated-page star-feedback" aria-label="Instructor feedback with Sunita comments"><h2>Instructors’ feedback from last year’s Planet Tarkov Problem-Solving Activity</h2><div class="table-scroll"><table><thead><tr><th>Instructors’ feedback</th><th>Sunita Chawla’s Comments</th></tr></thead><tbody>'+rows+'</tbody></table></div></section>')
p=P[7];lz=['敬啟者：','自 1993 年起，基金會協助弱勢兒童透過有益經歷建立信心，許多人成為醫生、工程師和科學家。','一名校友說基金會給他希望與發揮才能的動力。','今年活動主題是太空探索，故向亞洲領先的 Star Pod 提出請求。','基金會希望借用太空艙複製品，讓孩子留下難忘回憶。','如果同意，請考慮以下詳情。','感謝考慮，希望攜手豐富孩子的生活。','此致','Denise Leung，Locae Foundation 總監']
letter='<div class="star-letter"><header><h3>Locae Foundation</h3><p>~Making young lives matter~</p></header><p>26 March 2020</p><address>Upper Wong Tai Sin Estate II<br>Industry House<br>204 Ching Tak Street<br>Chuk Un</address>'+ps(p,4,10,lz[:6])+'<ul><li>We would like to borrow the capsule from 23rd to 27th of April</li><li>Children would play inside and outside the capsule under close supervision.</li></ul><p class="translation" lang="zh-Hant">希望在 4 月 23 日至 27 日借用，讓孩子在監督下於艙內外活動。</p>'+ps(p,11,14,lz[6:])+'</div>'
put(8,'<section class="recreated-page star-letter-page" aria-label="Locae Foundation letter"><h2>Letter from Locae Foundation</h2>'+letter+'</section>')
eng='<div class="star-assessment"><h3>Engineering Assessment</h3><img class="star-logo" src="assets/2020-b2-logo.webp" alt="Original Star Pod logo"><dl class="assessment-meta"><dt>Machine / Component</dt><dd>Multi-Axis Trainer</dd><dt>Fault / Problem</dt><dd>Motor failure</dd><dt>Date / time of incident</dt><dd>9:45 AM Thurs 26 March 2020</dd></dl><h4>Supporting Diagrams:</h4><div class="star-diagrams"><figure><img src="assets/2020-b2-building.webp" alt="Original cross-section diagram: micro cracks in roof, water droplets, M.A.T. and main door"><figcaption>Fig 1: Cross Section View of Multi-Axis Trainer Building</figcaption></figure><figure><img src="assets/2020-b2-mat.webp" alt="Original CCTV photograph of the M.A.T. incident"><figcaption>Fig 2: CCTV footage of incident</figcaption></figure></div><dl class="assessment-meta"><dt>Cause of roof cracks</dt><dd>Falling branches</dd><dt>Cause of falling branches</dt><dd>Storm</dd><dt>Recommendations</dt><dd>Seal micro cracks on roof</dd></dl><p class="translation" lang="zh-Hant">暴風雨令樹枝墜下，屋頂出現微裂縫，水滴滲入導致馬達故障；建議密封裂縫。</p></div>'
put(9,'<section class="recreated-page star-engineering" aria-label="M.A.T. engineering assessment"><h2>Multi-Axis Trainer (M.A.T.) Engineering Assessment by Scotty Wong</h2>'+eng+'</section>')
p=P[9];wz=['開放日快到了！想了解冒險營，歡迎參加，現場有豐富活動和贈品。','本月稍後的開放日會有神秘特別嘉賓。','貴賓可與神秘嘉賓共進午餐。','猜猜是誰？提示：曾獲體操冠軍，也去過太空。','想到了嗎？敬請留意詳情。','冒險營大受歡迎，將由每年兩次擴至四次，在三月、五月、八月和十一月舉辦。','在此報名。']
post1='<article class="star-post"><header><img src="assets/2020-b2-logo.webp" alt="Star Pod logo"><div><b>Star Pod</b><small>2 April at 10:12</small></div></header><h4>Star Pod Adventure Camp<br>Star Pod Open Day</h4>'+ps(p,5,10,wz[:5])+'<footer>Like　 Comment　 Share</footer></article>'
post2='<article class="star-post"><header><img src="assets/2020-b2-logo.webp" alt="Star Pod logo"><div><b>Star Pod</b><small>18 March at 16:45</small></div></header><h4>Exciting news!</h4>'+ps(p,13,15,wz[5:])+'<footer>Like　 Comment　 Share</footer></article>'
put(10,'<section class="recreated-page star-web-page" aria-label="Star Pod website news posts"><h2>Star Pod Website</h2><div class="star-browser"><div class="browser-top">Star Pod　 File　 Edit　 View　 Go　 Bookmarks　 Tools　 Help</div><div class="browser-url">https://www.starpod.com/</div><nav>Home　 Create</nav><h3>Latest News</h3>'+post1+post2+'</div></section>')
p=P[10];background=p[3].removeprefix('Background: ');recommendation=p[7].removeprefix('Recommendation: ')
assess='<div class="star-assessment"><h3>Feasibility Assessment</h3><img class="star-logo" src="assets/2020-b2-logo.webp" alt="Original Star Pod logo"><dl class="assessment-meta"><dt>Machine / Component</dt><dd>Replica Space Capsule</dd><dt>Background</dt><dd>'+bi(background,'2005 年公司向美國小型供應商 CST 購入太空艙複製品；CST 於 2008 年結業，這個罕有的艙若受損將難以取代。')+'</dd><dt>Issue</dt><dd>Feasibility of moving</dd></dl><h4>Findings:</h4><div class="table-scroll"><table><thead><tr><th>Issue</th><th>Recommend moving?</th><th>Engineer’s comments</th></tr></thead><tbody><tr><td>Fragile</td><td>No</td><td>General structure sound; indications of stress fractures on the bottom part of the capsule.</td></tr></tbody></table></div><h4>Recommendation</h4>'+bi(recommendation,'根據上述情況，管理層應拒絕 Locae 的借用請求。')+'<figure class="capsule-photo"><img src="assets/2020-b2-capsule.webp" alt="Original photograph of replica space capsule at Star Pod Camp"><figcaption>Fig 1: Replica Space Capsule at Star Pod Camp</figcaption></figure></div>'
put(11,'<section class="recreated-page star-engineering" aria-label="Space capsule transport feasibility assessment"><h2>Space Capsule Transport Feasibility Assessment by Scotty Wong</h2>'+assess+'<p class="source-end">THIS IS THE LAST PAGE OF THE PART B2 DATA FILE</p></section>')
tasks={12:(8,'Introductory Video Script',18,'Write a script for the Planet Tarkov Problem-Solving Activity introductory video using information from the B2 Data File and your notes. Write around 150 words.','運用乙部二資料檔及筆記，撰寫約 150 字的 Tarkov 活動影片開場稿。'),14:(9,'Incident Report',18,'Write an incident report for what happened on the M.A.T. using information from the B2 Data File. Write around 150 words.','運用乙部二資料檔，撰寫約 150 字的 M.A.T. 意外報告。'),16:(10,'Email Reply',17,'Write an email replying to the Locae Foundation using information from the B2 Data File and your notes. Write around 200 words.','運用乙部二資料檔及筆記，撰寫約 200 字電郵回覆 Locae Foundation。')}
for n,(t,title,marks,prompt,z) in tasks.items():
 h='<div class="qab-heading"><span>HKDSE 2020 · ENGLISH LANGUAGE · PAPER 3 PART B2</span><strong>B2 · DIFFICULT SECTION</strong></div>' if n==12 else ''
 subject='<div class="email-answer-head"><label>Subject: <input data-note="16-subject" aria-label="Email subject"></label></div>' if n==16 else ''
 put(n,f'<section class="recreated-page answer-book star-answer" aria-label="Task {t}: {escape(title)}">{h}<h2>Task {t}: {escape(title)} <small>({marks} marks)</small></h2>{bi(prompt,z)}{subject}{ans(n,"response",title,780)}</section>')
for n,t,end in [(13,8,'END OF TASK 8'),(15,9,'END OF TASK 9'),(17,10,''),(18,10,'END OF TASK 10 · END OF PART B2')]:put(n,f'<section class="recreated-page answer-book star-answer" aria-label="Task {t} answer continuation"><h2>Task {t} · Answer continuation</h2><p class="translation" lang="zh-Hant">任務 {t} 續答頁</p>{ans(n,"continuation",f"Task {t} answer continuation",820)}<p class="source-end">{end}</p></section>')
