"""Rebuild 2017 Golden Flower Island B2 as original-format native documents."""
from html import escape
from pathlib import Path
import re
BASE=Path(__file__).resolve().parent;ROOT=BASE/'layouts';RAW=(BASE/'source/2017-b2-df-clean.txt').read_text()
PAGES={int(n):[x.strip() for x in re.split(r'\n\s*\n',chunk) if x.strip() and not x.strip().startswith('2017-DSE-')] for n,chunk in re.findall(r'PAGE (\d+) OF 10\n.*?\n={20,}\n(.*?)(?=\n={20,}\nPAGE|\Z)',RAW,re.S)}
def put(n,s):(ROOT/f'2017-b2-page-{n:02}.html').write_text(s.rstrip()+'\n',encoding='utf-8')
def norm(s):return re.sub(r'\s+',' ',s.strip())
def bi(en,zh):return f'<div class="bilingual"><p lang="en">{escape(norm(en))}</p><p class="translation" lang="zh-Hant">{escape(zh)}</p></div>'
def ans(n,key,label,height=700):
 ident=f'2017-b2-{n}-{key}'
 return f'<label class="answer-field" for="{ident}">{escape(label)}</label><textarea id="{ident}" class="answer-box" data-note="{n}-{key}" data-count-id="{ident}" style="min-height:{height}px" aria-label="{escape(label,quote=True)}"></textarea><p class="answer-count" data-count-for="{ident}">0 words</p>'
def email(name,to,from_,sent,subject,body):
 return '<div class="email-window"><div class="email-toolbar">File　 Message　 Junk　 Delete　 Reply　 Reply All　 Forward　 Move　 Mark Unread　 Follow up</div><div class="email-headers">'+''.join(f'<div><b>{k}:</b> {escape(v)}</div>' for k,v in [('To',to),('From',from_),('Sent',sent),('Subject',subject)])+'</div><div class="email-content">'+body+'</div></div>'
put(1,(ROOT/'2012-b2-page-01.html').read_text().replace('2012','2017').replace('<strong>B1</strong>','<strong>B2</strong>').replace('3-B1-DF-1','3-B2-DF-1'))
p=PAGES[1];zh=['你是 Gehry Zhang，在地產發展商 Dragon Peak Properties（DPP）工作。上司 Norman Kwok 負責宣傳及市場推廣。公司剛完成 Jade Islands，並在規劃 Golden Flower Island 項目。','你將聆聽 Charlie Meadows 主持的《Business Matters》電台座談，嘉賓有 Norman Kwok 和環保組織 Green Treasure 的 Ann Lam。','錄音前有五分鐘閱讀問答冊與資料檔，熟悉情境及任務。','按問答冊及錄音指示完成任務。所需資料在問答冊、資料檔和錄音；聆聽時可在資料檔第 3 頁做筆記。','現在有五分鐘熟悉問答冊與資料檔。']
toc=[(3,'Listening note-taking sheet for the radio panel show Business Matters'),(4,'Email from Norman Kwok to Gehry Zhang, 8 April'),(4,'Extract from Flora and Fauna of South China by J.R. Hartley'),(5,'Email from Norman Kwok to Activities and Engineering Teams, 2 March'),(5,'PlinyPedia entry for Mariana Tse'),(6,'Email from Mari Nakamura to Gehry Zhang, 28 March'),(7,'Email from Ripple Wu to Gehry Zhang, 29 March'),(8,'Email from Norman Kwok to Gehry Zhang, 6 April'),(9,'Skype chat between Ripple Wu and Gehry Zhang, 6 April'),(10,'Article from Hong Kong Real Estate Monthly'),(11,'Minutes from Golden Flower Adventure Mall team meeting')]
put(2,'<section class="recreated-page situation-page" aria-label="Dragon Peak situation and contents"><div class="situation-box"><h2>Part B</h2><h3>Situation</h3>'+''.join(bi(x,y) for x,y in zip(p[2:7],zh))+'</div><div class="contents-box"><h3>Contents</h3><ol>'+''.join(f'<li><a href="#page-{n}">{escape(t)} <span>{n}</span></a></li>' for n,t in toc)+'</ol></div></section>')
p=PAGES[2];labs=[('Facts about the Jade Islands','Jade Islands 的資料'),('Problems with the Jade Islands','Jade Islands 的問題'),('Golden Flower Adventure Mall','Golden Flower Adventure Mall'),('Issues concerning Golden Flower Island','Golden Flower Island 的問題')]
put(3,'<section class="recreated-page conference-notes" aria-label="Business Matters note sheet"><h2>Listening note-taking sheet for the radio panel show <em>Business Matters</em></h2><div class="notes-form-body">'+''.join(f'<h3>{escape(en)}</h3><p class="translation" lang="zh-Hant">{zh}</p><textarea data-note="3-{i}" rows="6" aria-label="Notes: {escape(en,quote=True)}"></textarea>' for i,(en,zh) in enumerate(labs,1))+'</div></section>')
p=PAGES[3];mailzh=['Gehry 你好：','請替我撰寫以下文件。','下週一我與 Manu Architects 跟進商場概念圖，會向他們反映初步方案。員工應已把意見寄給你。請整理哪些元素應保留、哪些不應保留，以及各元素應如何改進。','第二，請為公司網站撰文，概述 DPP 在香港如何保護環境，包括最近成果，以及 Golden Flower Island 的蘭花和蝴蝶保育措施，讓公眾知道公司重視環保。','第三，請根據昨天會議撰寫邀請函給 Tse 女士，說明她在開幕典禮的角色及工作。她經常拒絕同類邀請，請參考她的 PlinyPedia 資料，找出與項目相符的興趣或信念，以提高接受機會。','謝謝你的努力。','此致','Norman']
mail=email('Norman','Gehry Zhang','Norman Kwok','Sat 8 April 9:05AM','Things for you to do',''.join(bi(x,y) for x,y in zip(p[3:11],mailzh)))
book='<div class="nature-book"><h3>Golden Dragon Tail Butterfly</h3>'+bi(p[13],'金龍尾蝶在亞洲常見，卻只出現在華南極少數地區。它是華南唯一已知會為極罕有的 Splash of Gold Orchid 授粉的物種。這種蘭花如今只見於 Golden Flower Island。政府因特殊科學價值，只把島嶼一半劃為郊野公園，限制該區發展；另一半傳出 2017 年發展計劃，作者希望保護這些動植物。')+'</div>'
put(4,'<section class="recreated-page peak-email" aria-label="Norman email and butterfly book extract"><h2>Email from Norman Kwok to Gehry Zhang, 8 April</h2>'+mail+'<h2>Extract from <em>Flora and Fauna of South China</em> by J.R. Hartley</h2>'+book+'</section>')
p=PAGES[4];normzh=['各位同事：','謝謝今早出席 Manu Architects 初步商場概念方案介紹。請於 3 月 31 日前把對方案、功能發展的意見和建議寄給 Gehry，讓她整理。','謝謝','Norman']
mail=email('Norman','Mari Nakamura; Ripple Wu; Alison Lo','Norman Kwok','Thurs 2 March 11:35AM','Manu Architects’ Initial Concept Plan','<p><b>CC:</b> Gehry Zhang</p>'+''.join(bi(x,y) for x,y in zip(p[3:7],normzh))+'<figure class="mall-concept"><figcaption>Golden Flower Adventure Mall · Initial Concept Plan</figcaption><div class="concept-image"><img src="assets/2017-b2-mall.webp" alt="Original Golden Flower Adventure Mall concept image: jungle waterfall, ship and lake"><span class="castle">Castle</span><span class="ship">Shops &amp; restaurants on sailing ship</span><span class="fall">40 metres</span><span class="lake">Lake</span></div><p class="translation" lang="zh-Hant">概念圖標示：城堡、帆船上的商店及餐廳、40 米瀑布和湖泊。</p></figure>')
profile='<div class="plinypedia"><div class="profile-head"><div><h3>Mariana Tse</h3><p>Born: 22 June, 1995 (aged 21)<br>Occupation: singer, musician, actress<br>Genres: Canto-hop<br>Years active: 2012 - present</p></div><img src="assets/2017-b2-mariana.webp" alt="Original Mariana Tse portrait"></div><div class="profile-columns"><section><p>EARLY YEARS　☐<br>DISCOGRAPHY　☐<br>VIEWS &amp; CHARITY WORK　☑</p>'+bi(p[12],'Mariana 熱心保護海洋，是 Save Hong Kong Coral Communities 的發言人，曾呼籲商界保護海洋生物。')+'</section><section><p>CAREER　☐<br>PERSONAL LIFE　☐<br>HOBBIES &amp; INTERESTS　☑</p>'+bi(p[14],'Mariana 喜歡游泳，曾代表中學參加國際賽事，也熱愛在海中浮潛和潛水，親近海洋生物。')+'</section></div></div>'
put(5,'<section class="recreated-page peak-email" aria-label="Concept plan email and PlinyPedia profile"><h2>Email from Norman Kwok to Activities and Engineering Teams, 2 March</h2>'+mail+'<h2>PlinyPedia entry for Mariana Tse</h2>'+profile+'</section>')
p=PAGES[5];mzh=['Gehry：','以下是我的想法……','整體概念很出色，適合各種有趣活動。瀑布、帆船和湖泊都應保留作為主要特色，但城堡應刪去。','建議加入游泳池；Ripple 做過類似項目，會把她的意見寄給你。','為善用商場中央空間及配合叢林冒險主題，建議在泳池上方設高空滑索，附上照片供參考。','Mari Nakamura，活動組主管']
mail=email('Mari','Gehry Zhang','Mari Nakamura','Tues 28 March 4:37PM','Initial Concept Plan',''.join(bi(x,y) for x,y in zip(p[3:8],mzh[:5]))+'<figure class="activity-photo"><img src="assets/2017-b2-zipline.webp" alt="Original example photograph of ziplines over an indoor swimming pool"><figcaption>Stock photo: ziplines over a pool</figcaption></figure>'+bi(p[8],mzh[5]))
put(6,'<section class="recreated-page peak-email" aria-label="Mari Nakamura concept-plan email"><h2>Email from Mari Nakamura to Gehry Zhang, 28 March</h2>'+mail+'</section>')
p=PAGES[6];rzh=['Gehry 你好：','初步方案符合我們討論的叢林主題。我同意 Mari：叢林不該有城堡。','我建議把湖改成水族館。帆船上同時設商店和餐廳並不實際，應刪去商店。','我同意設泳池和滑索；我們近年在英國 Highland Adventure Centre 做過類似設施，效果很好。','這裡還有一個商場構思：','不能讓一般人在瀑布正中央像照片中那樣沿繩下降，應設在瀑布兩旁。','謝謝','Ripple']
mail=email('Ripple','Gehry Zhang','Ripple Wu','Wed 29 March 3:18PM','Golden Flower Adventure Mall',''.join(bi(x,y) for x,y in zip(p[3:8],rzh[:5]))+'<figure class="activity-photo"><img src="assets/2017-b2-abseil.webp" alt="Original example photograph of abseiling beside a waterfall"><figcaption>Example of abseiling near a waterfall</figcaption></figure>'+''.join(bi(x,y) for x,y in zip(p[8:11],rzh[5:])))
put(7,'<section class="recreated-page peak-email" aria-label="Ripple Wu concept-plan email"><h2>Email from Ripple Wu to Gehry Zhang, 29 March</h2>'+mail+'</section>')
p=PAGES[7]
forward='<div class="nested-mail"><h3>Alison Lo → Norman Kwok · Wed 5 April 2017 1:56PM</h3>'+bi(p[7],'Norman 你好：')+bi(p[8],'Highland Adventure Centre 當年的解決方案費用很高，設施關閉六個月，把瀑布從 45 米改建為 30 米後就不再形成雲霧，也再沒有類似問題。')+bi(p[9],'我尚未向 Gehry 寄出建議，因想先聽其他人看法。工程組認為建築師初步方案及員工建議的元素在技術上均可行，並非沒有先例。')+bi(p[10],'Alison Lo，工程組')+'</div>'
older='<div class="nested-mail"><h3>Norman Kwok → Alison Lo · Wed 5 April 2017 1:14PM</h3>'+bi(p[12],'Alison 你好：')+bi(p[13],'Ann Lam 昨天在電台《Business Matters》提到我們在英國 Highland Adventure Centre 的舊問題。我記得有麻煩，卻忘了細節和如何解決。請提醒我。')+bi(p[14],'Norman')+'</div>'
mail=email('Norman','Gehry Zhang','Norman Kwok','Thurs 6 April 11:12AM','FW: Re: Highland Adventure Centre',bi(p[3],'Gehry 你好：')+bi(p[4],'請看我與 Alison 的以下電郵，與你為下週一 Manu Architects 會議準備的文件有關。')+bi(p[5],'Norman')+forward+older)
put(8,'<section class="recreated-page peak-email" aria-label="Highland Adventure Centre forwarded email chain"><h2>Email from Norman Kwok to Gehry Zhang, 6 April</h2>'+mail+'</section>')
p=PAGES[8];skzh=['我想到你為 Norman 準備的商場方案摘要，有個更好的泳池建議。','好！是甚麼？','去年我在新加坡的商場項目，把泳池設在水族館旁邊，我們也可以這樣做。','泳池為甚麼要設在水族館旁？','泳客可以隔着玻璃與海洋動物一起游泳。','聽起來驚人！玻璃牆一定要夠厚。','是的，我還第一個下水測試。','你沒有被吃掉！','還活着！','好，我會加入建議。','我還想把泳池設在瀑布下，讓水花帶來刺激感。','好主意！還有嗎？','太晚了，腦袋停工了，晚安。']
msgs=''
for raw,zh in zip(p[4:17],skzh):
 m=re.match(r'(Ripple|Gehry): (.*?) (\d+:\d+ PM)$',raw,re.S)
 if not m:raise ValueError(raw[:80])
 who,body,time=m.groups();msgs+=f'<div class="peak-chat-msg {who.lower()}"><strong>{who}</strong>{bi(body,zh)}<time>{time}</time></div>'
put(9,'<section class="recreated-page peak-skype" aria-label="Ripple and Gehry Skype chat"><h2>Skype chat between Ripple Wu and Gehry Zhang, 6 April</h2><div class="peak-chat"><header>Skype　 Contacts　 Conversation　 Call　 View　 Tools　 Help</header><div class="peak-chat-tools">Show messages from: <b>yesterday</b> | 7 days | 30 days | 3 months | 6 months</div><h3>Thursday, April 6, 2017</h3>'+msgs+'</div></section>')
p=PAGES[9];awards=[('1st Prize','Forest of Dreams Estate (Dragon Peak Properties)'),('2nd Prize','21B Seashell Cove Avenue (Shek Gaan Developments)'),('3rd Prize','Enchanted Bay (Gault & Rand Land)'),('4th Prize','88 Fecund Gardens Drive (Dark Matter Solutions)')]
chart='''<figure class="peak-chart"><figcaption>Spending on Green Construction Methods by Hong Kong’s three biggest developers since 2000<br>(Billions of HK$)</figcaption><svg viewBox="0 0 660 320" role="img" aria-label="Line graph: Dragon Peak rises sharply after 2005 and leads by 2015; Shek Gaan rises to second, Gault and Rand rises gradually"><g stroke="#cad5d1" stroke-width="1" fill="none"><path d="M55 30V270H555"/><path d="M55 230H555M55 190H555M55 150H555M55 110H555M55 70H555M55 30H555"/></g><g fill="#263b3d" font-family="Arial" font-size="13"><text x="30" y="274">0</text><text x="30" y="234">1</text><text x="30" y="194">2</text><text x="30" y="154">3</text><text x="30" y="114">4</text><text x="30" y="74">5</text><text x="30" y="34">6</text><text x="55" y="294">2000</text><text x="200" y="294">2005</text><text x="350" y="294">2010</text><text x="500" y="294">2015</text></g><polyline points="78,185 225,160 380,50 535,30" fill="none" stroke="#284c4b" stroke-width="6" stroke-dasharray="14 7"/><polyline points="78,165 225,170 380,155 535,145" fill="none" stroke="#6a7777" stroke-width="5" stroke-dasharray="2 9" stroke-linecap="round"/><polyline points="78,145 225,175 380,125 535,82" fill="none" stroke="#9aabaa" stroke-width="5"/><g font-family="Arial" font-size="13" fill="#263b3d"><text x="560" y="37">Dragon Peak</text><text x="560" y="90">Shek Gaan</text><text x="560" y="150">Gault &amp; Rand</text></g></svg><p class="translation" lang="zh-Hant">折線圖顯示：Dragon Peak 在 2005 年後環保建築開支急升，2015 年居首；Shek Gaan 升至第二，Gault &amp; Rand 緩慢增長。原卷為圖像數據，線條位置按原圖重畫。</p></figure>'''
news='<article class="peak-news"><h3>'+escape(p[1])+'</h3>'+bi(p[2],'本月 Tai Shing Conservation Institute 公布香港最環保發展項目獎；Dragon Peak 多年投資環保建築技術，因此獲獎並不意外。')+bi(p[3],'公司也在香港以外支持環保，最近向澳洲大堡礁保育組織捐出可觀款項，表示會盡力保存珊瑚供後代欣賞。')+'<div class="awards"><h4>Greenest Housing Development Awards 2016</h4><ol>'+''.join(f'<li><b>{escape(place)}</b> — {escape(name)}</li>' for place,name in awards)+'</ol></div>'+chart+'</article>'
put(10,'<section class="recreated-page peak-news-page" aria-label="Hong Kong Real Estate Monthly article and chart"><h2>Article from <em>Hong Kong Real Estate Monthly</em></h2>'+news+'</section>')
p=PAGES[10];minzh=['工程進度報告確認暫定竣工日仍為 2018 年 11 月 30 日。會議討論開幕日期後，決定選 12 月 24 日，讓商場立即受惠於聖誕假期。','Kwok 先生報告財務部審批開幕典禮預算結果：嘉賓酬金港幣十萬元獲批；馬車典禮五萬元因保險問題被拒。','因馬車方案不獲批准，Lo 博士提議請會游泳的嘉賓率先在新泳池下水，以宣布開幕。眾人同意，並決定邀請 Mariana Tse，由 Gehry 聯絡。','Wu 女士指出 Mariana Tse 最近拒收同類活動酬金。Kwok 先生建議把嘉賓酬金預算捐給她選擇的慈善機構，眾人同意。']
budget='<div class="table-scroll"><table><thead><tr><th>Item</th><th>Requested budget</th><th>Approved?</th><th>Reason</th></tr></thead><tbody><tr><th>Guest of honour fees</th><td>HK$100,000</td><td>✓</td><td>n/a</td></tr><tr><th>Horse and carriage for ceremony</th><td>HK$50,000</td><td>✕</td><td>Refused due to insurance concerns.</td></tr></tbody></table></div>'
mins='<div class="meeting-sheet"><h3>Golden Flower Adventure Mall team meeting</h3><dl class="meeting-meta"><dt>Date</dt><dd>8:00 AM, Fri. 7 April 2017</dd><dt>Venue</dt><dd>The Eyrie, Dragon Peak Tower</dd><dt>Chairperson</dt><dd>Norman Kwok</dd><dt>Members</dt><dd>Alison Lo · Mari Nakamura · Ripple Wu</dd><dt>Secretary</dt><dd>Gehry Zhang</dd></dl><h3>Opening Ceremony of Mall</h3>'+bi(p[5],minzh[0])+bi(p[6],minzh[1])+budget+bi(p[8],minzh[2])+bi(p[9],minzh[3])+'<p>Meeting ended at 8:40 am.</p></div>'
put(11,'<section class="recreated-page meeting-minutes peak-minutes" aria-label="Golden Flower Adventure Mall meeting minutes"><h2>Minutes from Golden Flower Adventure Mall team meeting</h2>'+mins+'<p class="source-end">THIS IS THE LAST PAGE OF THE PART B2 DATA FILE</p></section>')
tasks=[(12,8,'Summary for meeting','Write a summary of the opinions on the initial concept plan for the Golden Flower Adventure Mall using information from the B2 Data File and your notes. Write around 220 words.','運用乙部二資料檔及筆記，概述商場初步概念方案的意見，約寫 220 字。',22,None),(14,9,'Overview for DPP’s website','Write an overview of what DPP has done in Hong Kong to protect the environment using information from the B2 Data File and your notes. Write around 150 words.','運用乙部二資料檔及筆記，概述 DPP 在香港的環境保護工作，約寫 150 字。',18,'Dragon Peak’s Commitment to the Environment in Hong Kong'),(16,10,'Letter to invite guest of honour','Write a letter to invite the guest of honour for the Opening Ceremony for the Golden Flower Adventure Mall using information from the B2 Data File. You do not need to write an address. Write around 100 words.','運用乙部二資料檔，撰寫邀請商場開幕典禮主禮嘉賓的信，不用寫地址，約寫 100 字。',13,None)]
for n,task,title,prompt,zh,marks,special in tasks:
 head='<div class="qab-heading"><span>HKDSE 2017 · ENGLISH LANGUAGE · PAPER 3 PART B2</span><strong>B2 · DIFFICULT SECTION</strong></div>' if n==12 else ''
 field=(f'<h3 class="answer-title">{escape(special)}</h3>' if special else '')+ans(n,'response',title,790)
 put(n,f'<section class="recreated-page answer-book peak-answer" aria-label="Task {task}: {escape(title)}">{head}<h2>Task {task}: {escape(title)} <small>({marks} marks)</small></h2>{bi(prompt,zh)}{field}</section>')
for n,task,end in [(13,8,'END OF TASK 8'),(15,9,'END OF TASK 9'),(17,10,'END OF TASK 10 · END OF PART B2')]:put(n,f'<section class="recreated-page answer-book peak-answer" aria-label="Task {task} answer continuation"><h2>Task {task} · Answer continuation</h2><p class="translation" lang="zh-Hant">任務 {task} 續答頁</p>{ans(n,"continuation",f"Task {task} answer continuation",820)}<p class="source-end">{end}</p></section>')
