"""Source-authored 2018 Paper 3 B1 board-game documents and answer book."""
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent / 'layouts'
def put(n, body): (ROOT / f'2018-b1-page-{n:02}.html').write_text(body.rstrip()+'\n', encoding='utf-8')
def bi(en, zh): return f'<div class="bilingual"><p lang="en">{escape(en)}</p><p class="translation" lang="zh-Hant">{escape(zh)}</p></div>'
def field(key, label): return f'<input data-note="10-{key}" aria-label="{escape(label, quote=True)}">'

put(1, (ROOT/'2015-b1-page-01.html').read_text().replace('2015','2018'))
situation = [
('You are Sammy Tsang. You work for a board game company called Griffin Workshop in Hong Kong. It is a small company set up by some friends. It is now working on its latest board game Escape to Hong Kong Island. Your boss, Angel Fu, has asked you to do some tasks.', '你是 Sammy Tsang，在香港桌上遊戲公司 Griffin Workshop 工作。公司由一群朋友創辦，規模不大，現正開發最新桌遊《Escape to Hong Kong Island》。你的上司 Angel Fu 指派了幾項工作。'),
('You will listen to a recording of the weekly podcast programme The Classical. In the podcast you will hear an interview with Angel Fu and Eric Park, a well-known board game designer. Take notes under the appropriate headings.', '你將聆聽每週播出的播客節目《The Classical》，內容是 Angel Fu 與知名桌遊設計師 Eric Park 的訪問。請按標題記筆記。'),
('Before the recording is played, you will have five minutes to study the Question-Answer Book and the Data File to familiarise yourself with the situation and the tasks.', '錄音播放前，你有五分鐘閱讀問答冊和資料檔，熟悉情境與任務。'),
('Complete the tasks by following the instructions in the Question-Answer Book and on the recording. You will find all the information you need in the Question-Answer Book, the Data File and on the recording. As you listen, you can make notes on page 3 of the Data File.', '按照問答冊和錄音指示完成任務。所有所需資料均見於問答冊、資料檔和錄音；聆聽時可在資料檔第 3 頁記筆記。'),
('You now have five minutes to familiarise yourself with the Question-Answer Book and the Data File.', '現在有五分鐘熟悉問答冊和資料檔。')]
toc=[(3,'Listening note-taking sheet for the podcast The Classical'),(4,'Email from Angel Fu to Sammy Tsang'),(5,'Thread from the BoardGameFan forum'),(6,'Questionnaire results from testing of Escape to Hong Kong Island'),(7,'Skype chat between Mabel Lau and Angel Fu'),(8,'Email from Tommy Chen to Mabel Lau and Angel Fu'),(9,'WhatsApp Escape to Hong Kong Island group messages')]
put(2,'<section class="recreated-page situation-page" aria-label="2018 Part B situation and contents"><div class="situation-box"><h2>Part B</h2><h3>Situation</h3>'+''.join(bi(*x) for x in situation)+'</div><div class="contents-box"><h3>Contents</h3><ol>'+''.join(f'<li><a href="#page-{p}">{escape(t)} <span>{p}</span></a></li>' for p,t in toc)+'</ol></div></section>')

note_heads=[('Information about Griffin Workshop','Griffin Workshop 的資料'),('How to fund your game','如何籌集遊戲開發資金'),('Details about Griffin Workshop’s first game','Griffin Workshop 首款遊戲的詳情'),('Details about Griffin Workshop’s latest game','Griffin Workshop 最新遊戲的詳情'),('Advice regarding latest game','關於最新遊戲的建議')]
put(3,'<section class="recreated-page conference-notes" aria-label="The Classical podcast note-taking sheet"><h2>Listening note-taking sheet for the podcast <em>The Classical</em></h2><div class="notes-form-body">'+''.join(f'<h3>{escape(en)}</h3><p class="translation" lang="zh-Hant">{escape(zh)}</p><textarea data-note="3-{i}" rows="5" aria-label="Notes: {escape(en,quote=True)}"></textarea>' for i,(en,zh) in enumerate(note_heads,1))+'</div></section>')

email_pars=[
('Dear Sammy','Sammy：'),('Could you please do the following three things for me?','請替我完成以下三件事：'),
('We have received an invitation to MegaGame Conference, a games conference for board game designers. Please complete the application form for our company. You can look at the Skype chat between me and Mabel about this and the email exchange between me, Tommy and Mabel. You can also listen to me on The Classical podcast.','我們收到桌遊設計師會議 MegaGame Conference 的邀請。請為公司填寫報名表。可參考我和 Mabel 的 Skype 對話、我與 Tommy 和 Mabel 的電郵，以及《The Classical》播客。'),
('We want to ask Paul Achebe, a well-known game reviewer, to do a video review for our game Escape to Hong Kong Island for YouTube. He reviewed our other game last year. Write him an email. In the email, ask him if he wants to do the video review and briefly describe the game for him. Remember to mention the target audience of the game. You can look at the BoardGameFan forum and listen to the podcast to help you.','我們想邀請知名遊戲評論員 Paul Achebe 為《Escape to Hong Kong Island》製作 YouTube 影片評論。他去年曾評論我們的另一款遊戲。請寫電郵邀請他，簡介遊戲並說明目標玩家。可參考 BoardGameFan 討論區及播客。'),
('We tested Escape to Hong Kong Island with a group of people on Monday and gave them a questionnaire afterwards. Write a report for our company meeting next week. Summarize the results of the questionnaire and what the problems with the game were. Then report on what has been done and what follow-up action hasn’t been done yet. Look at the questionnaire results and the WhatsApp Escape to Hong Kong Island group messages to help you.','我們星期一找了一組人試玩《Escape to Hong Kong Island》，之後請他們填問卷。請為下週公司會議寫報告，概述問卷結果和遊戲問題，再說明哪些跟進工作已完成、哪些尚未完成。可參考問卷和 WhatsApp 群組訊息。')]
put(4,'<section class="recreated-page email-document" aria-label="Email from Angel Fu to Sammy Tsang"><h2>Email from Angel Fu to Sammy Tsang</h2><div class="email-window"><div class="email-tabs"><span>File</span><span>Message</span></div><div class="email-toolbar">'+''.join(f'<span>{x}</span>' for x in ['Junk','Delete','Reply','Reply All','Forward','Move','Mark Unread','Follow up'])+'</div><div class="email-headers"><div><strong>To:</strong> Sammy Tsang</div><div><strong>Sent:</strong> Sat 14 April 2018 9:02AM</div><div><strong>From:</strong> Angel Fu</div><div><strong>Subject:</strong> Things to do for Escape to Hong Kong Island</div></div><div class="email-content">'+''.join(bi(*p) for p in email_pars[:2])+'<ul>'+''.join('<li>'+bi(*p)+'</li>' for p in email_pars[2:])+'</ul><p>Thanks<br>Angel</p></div></div></section>')

posts=[
('Leroy74','April 11 2018, 08:40 PM','Hey has anyone played this yet? Is it any good? These guys did another game, Death Kick, which was awesome.','有人玩過這款遊戲嗎？好玩嗎？他們之前的《Death Kick》很棒。'),
('AmyTroll','April 11 2018, 08:55 PM','I played the new one on Monday. They had a big test session. Was pretty good.','我星期一參加了大型試玩，玩了這款新遊戲，覺得相當不錯。'),
('Vexy4','April 11 2018, 09:05 PM','What’s it about?','遊戲內容是甚麼？'),
('AmyTroll','April 11 2018, 09:07 PM','It’s a zombie game.','這是一款喪屍遊戲。'),
('Leroy74','April 11 2018, 09:43 PM','What another zombie game! There’s so many of them. Not interested.','又是喪屍遊戲？這類遊戲太多了，沒興趣。'),
('AmyTroll','April 11 2018, 10:01 PM','But it’s set in Hong Kong. The board is a map of Hong Kong and you move around the map.','但遊戲以香港為背景；棋盤是香港地圖，玩家在地圖上移動。'),
('Kidpaul','April 11 2018, 10:49 PM','Ah now you’ve got me interested. What age is it for? I’d like to play it with my kids. And what’s it look like?','這樣我有興趣了。適合甚麼年齡？我想和孩子一起玩。畫風是怎樣的？'),
('AngelFu (creator)','April 12 2018, 11:43 AM','Hey there all and thanks for the interest in our game. Target audience: range is 12 to 15 year olds. Here’s a sample of the artwork from our talented artist Ryan Au:','大家好，感謝關注。目標玩家年齡是 12 至 15 歲。這裏是畫師 Ryan Au 的作品樣本：'),
('Leroy74','April 12 2018, 01:46 PM','Oh, looks a bit childish for 12-15 year olds to be honest. Somebody said that it’s a team game: that true? Not really a fan of team games as don’t really like working together with other players.','坦白說，對 12 至 15 歲的人而言，畫風有點幼稚。聽說這是團隊遊戲，是真的嗎？我不太喜歡與其他玩家合作。'),
('AmyTroll','April 12 2018, 03:26 PM','Yup it’s a team game. You definitely have to work together.','對，這是團隊遊戲，一定要合作。'),
('AngelFu (creator)','April 13 2018, 08:18 AM','Yes there are two teams, 2 players in each team.','對，有兩隊，每隊兩名玩家。')]
forum='<section class="recreated-page forum-document" aria-label="BoardGameFan source forum"><h2>Thread from the <em>BoardGameFan</em> forum</h2><div class="forum-window"><div class="forum-browser"><strong>BoardGameFan</strong>　File　Edit　View　Go　Bookmarks　Tools　Help</div><div class="browser-strip">◀　▶　↻　⌂　http://www.boardgamefan.com/forum</div><h3>Escape to Hong Kong Island</h3><p class="forum-actions">Track this topic　│　Email this topic　│　Print this topic</p>'
for i,(name,date,en,zh) in enumerate(posts):
 forum+=f'<article class="forum-post"><header><strong>{escape(name)}</strong><span>Posted: {escape(date)}</span></header><div>{bi(en,zh)}'
 if i==7: forum+='<figure class="boardgame-art"><img src="assets/2018-b1-ryan-au-art.webp" alt="Ryan Au’s original zombie character artwork from the paper"></figure>'+bi('Any other questions you have, please ask.','如有其他問題，歡迎發問。')
 forum+='</div></article>'
forum+='<div class="forum-footer">Pages: (1) [1] <span>Add reply　│　New topic</span></div></div></section>'
put(5,forum)

# Page 6 is already an individually reconstructed four-chart questionnaire.

skype=[
('Mabel','Hey what’s up?','嘿，最近怎樣？'),('Angel','How’s Toronto?','多倫多如何？'),('Mabel','Cold!!! Have you decided if you’re going to go to the MegaGame Conference?','冷極了！你決定去不去 MegaGame Conference 了嗎？'),('Angel','Yeah I definitely don’t want to miss it. You going?','我一定不想錯過。你去嗎？'),('Mabel','Yeah. Definitely. Who else is going?','當然。還有誰去？'),('Angel','Tommy told me he’s going.','Tommy 說他會去。'),('Mabel','What about Alex?','Alex 呢？'),('Angel','Yeah, Alex said he can make it as well.','Alex 說他也可以去。'),('Mabel','So that’s 4 of us.','那就是四個人。'),('Angel','Yep.','對。'),('Mabel','How many days is it?','會議有多少天？'),('Angel','Two I think. And we are going to both days.','我想是兩天，我們兩天都去。'),('Mabel','Isn’t it 3?','不是三天嗎？'),('Angel','Let me check. Sorry, you’re right – 3 days. We’ll go to all 3 then.','讓我查一查。抱歉，你說得對，是三天。我們三天都去。'),('Mabel','Are we going to do a demonstration of the game so that people can see the game in action?','我們會示範遊戲，讓大家看實際玩法嗎？'),('Angel','Yeah. Gonna do one demo on each day.','會，每天示範一次。'),('Mabel','Sounds fun. How many players do we need for the demo?','聽起來很好玩。每次示範需要幾名玩家？'),('Angel','Four.','四名。'),('Mabel','Well that’s good, cause there are 4 of us! So we can do the demo.','那很好，剛好我們有四個人，可以示範。'),('Angel','Yeah, lucky! Should be fun.','對，真巧！應該會很好玩。'),('Mabel','Yeah, I’m looking forward to it. Gotta go now. Going to this great little place called Snakes and Lattes Café in downtown Toronto to play Risk!','我也很期待。先走了，我要去多倫多市中心的 Snakes and Lattes Café 玩《Risk》！'),('Angel','It’s been years since I played Risk!! See you next week.','我已多年沒玩《Risk》了！下週見。')]
put(7,'<section class="recreated-page skype-conversation" aria-label="Skype chat between Mabel Lau and Angel Fu"><h2>Skype chat between Mabel Lau and Angel Fu</h2><div class="skype-window"><div class="skype-header">Skype　　Contacts　Conversation　Call　View　Tools　Help</div><div class="skype-filters">Show messages from: yesterday　7 days　30 days　3 months　6 months</div><p class="skype-date">Thursday, April 12, 2018 10:07PM</p>'+''.join(f'<div class="skype-row {"skype-mabel" if speaker=="Mabel" else "skype-angel"}"><strong>{speaker}:</strong>{bi(en,zh)}</div>' for speaker,en,zh in skype)+'</div></section>')

messages=[
('To: Mabel Lau; Angel Fu','Sent: Fri 13 April 2018 3:32PM','From: Tommy Chen','Cc: Sammy Tsang','Subject: RE: MegaGame Conference',[('Hi','你好：'),('Yes, I am vegetarian. BTW tell them I need wheelchair access. These places always forget about special needs.','是的，我吃素。另外，請告訴主辦方我需要無障礙輪椅通道。這些地方總是忘記特殊需要。'),('Cheers','謝謝'),('Tommy','Tommy')]),
('To: Angel Fu; Tommy Chen','Sent: Fri 13 April 2018 2:03PM','From: Mabel Lau','Cc: Sammy Tsang','Subject: RE: MegaGame Conference',[('Hi Angel','Angel：'),('No, I eat anything!','不用，我甚麼都吃！'),('Best','祝好'),('Mabel','Mabel')]),
('To: Mabel Lau; Tommy Chen','Sent: Fri 13 April 2018 1:56PM','From: Angel Fu','Cc: Sammy Tsang','Subject: MegaGame Conference',[('Dear Mabel and Tommy','Mabel、Tommy：'),('I was just looking at the MegaGame Conference application form and noticed it asks whether any of us has any special food needs. I don’t have any and I’ve just spoken to Alex and he doesn’t have any either but I don’t know about you two. Are either of you vegetarian? Let me know by tomorrow latest.','我正在看 MegaGame Conference 報名表，發現上面問有沒有人有特殊飲食需要。我沒有，剛問過 Alex，他也沒有；但不知道你們兩位是否吃素。最遲明天告訴我。'),('Regards','祝好'),('Angel','Angel')])]
def mail(msg):
 hdr=msg[:5]; pars=msg[5]
 return '<div class="email-window"><div class="email-headers">'+''.join(f'<div><strong>{escape(h.split(":",1)[0])}:</strong>{escape(h.split(":",1)[1])}</div>' for h in hdr)+'</div><div class="email-content">'+''.join(bi(*p) for p in pars)+'</div></div>'
put(8,'<section class="recreated-page museum-thread" aria-label="MegaGame Conference email thread"><h2>Email from Tommy Chen to Mabel Lau and Angel Fu</h2>'+''.join(mail(x) for x in messages)+'</section>')

whats=[('11 April 2018',[('Angel','10:08 AM','Hi, I’ve set up this WhatsApp group to focus on what we need to do based on the questionnaire results. Things to change: the rulebook (Mabel); the artwork (Alex); the text on the map (Tommy). Send a message to this group when you’ve done your changes.','我開設這個 WhatsApp 群組，以跟進問卷結果。要修改的項目：規則書（Mabel）、插畫（Alex）、地圖文字（Tommy）。完成後請在群組通知大家。'),('Tommy','10:35 AM','I’ve now changed the text. Now black and bigger font! Think it’s better now.','我已改好文字，現在改用黑色和較大的字體！我覺得好多了。')]),('12 April 2018',[('Mabel','4:45 AM','I haven’t added extra examples. Still on holiday! Sorry!','我還沒加上更多例子，仍在放假！抱歉！'),('Angel','10:51 AM','OK. Alex, any news on the new artwork?','好。Alex，新插畫有消息嗎？'),('Alex','11:53 PM','Ryan the artist says he hasn’t had time. He will send me new artwork next Wednesday.','畫師 Ryan 說還沒時間做，下週三會把新插畫發給我。')])]
chat='<section class="recreated-page group-chat" aria-label="Escape to Hong Kong Island WhatsApp group"><h2>WhatsApp Escape to Hong Kong Island group messages</h2><div class="chat-shell"><div class="chat-heading"><strong>Escape to Hong Kong Island</strong><span>Angel, Tommy, Mabel, Alex</span></div>'
for date,lines in whats:
 chat+=f'<p class="chat-date">{date}</p>'
 for name,t,en,zh in lines:
  chat+=f'<div class="chat-bubble {"outgoing" if name=="Angel" else ""}"><strong class="chat-speaker">{name}</strong>{bi(en,zh)}<time>{t}</time></div>'
chat+='</div><p class="end-note">THIS IS THE LAST PAGE OF THE PART B1 DATA FILE</p></section>'
put(9,chat)

rows=['Number of days you will be attending the conference:','Number of people from your organization attending:','Special dietary needs:','Other special needs:']
form='<div class="megagame-form"><h4>MEGAGAME CONFERENCE</h4><h5>Part 1 – Your conference needs:</h5><div class="conference-rows">'+''.join(f'<label><span>{i}.　{escape(label)}</span>{field(str(i),label)}</label>' for i,label in enumerate(rows,1))+'<div class="conference-choice"><span>5.　Will you demonstrate your game? (Tick the option.)<br><small>If No, then go to Part 2. If Yes, then please answer the questions below.</small></span><label>Yes <input type="radio" name="2018-demo" data-note="10-demo-yes" value="yes"></label><label>No <input type="radio" name="2018-demo" data-note="10-demo-no" value="no"></label></div>'+''.join(f'<label><span>{i}.　{escape(label)}</span>{field(str(i),label)}</label>' for i,label in [(6,'Number of demos you want:'),(7,'Number of players in each demo:')])+'</div><h5>Part 2 – Details of your company:</h5><div class="company-name">Name of your company: <em>Griffin Workshop</em></div><label class="long-answer">8.　Write a few sentences about your company (include the following):<ul><li>Why you formed the company</li><li>When you formed the company</li><li>The size of your company</li></ul><textarea data-note="10-company" rows="6" aria-label="Company background"></textarea></label><label class="long-answer">9.　Have you published any games before? (If so please state the name of your game and the type of game.)<textarea data-note="10-games" rows="5" aria-label="Previous published games"></textarea></label></div>'
put(10,'<section class="recreated-page answer-book conference-answer" aria-label="2018 B1 QAB application form"><div class="answer-book-header"><span>HKDSE 2018 · ENGLISH LANGUAGE · PAPER 3 PART B1 · Question-Answer Book</span><strong>B1</strong></div><h3>Task 5: Application form <small>(14 marks)</small></h3>'+bi('Complete the application form below using information from the B1 Data File and your notes.','利用乙部一資料檔和筆記完成以下報名表。')+form+'<p class="answer-end">END OF TASK 5</p></section>')

def writing(n,title,zh,lead,height,key):
 ident=f'2018-b1-{n}-{key}'
 return f'<section class="recreated-page answer-book" aria-label="2018 B1 QAB page {n-9}"><h3>{escape(title)}</h3>'+bi(lead,zh)+f'<label class="answer-field" for="{ident}">{escape(title)}</label><textarea class="answer-box" id="{ident}" data-note="{n}-{key}" data-count-id="{ident}" style="min-height:{height}px" aria-label="{escape(title,quote=True)}"></textarea><p class="answer-count" data-count-for="{ident}">0 words</p>'
put(11,writing(11,'Task 6: Email (18 marks)','利用乙部一資料檔和筆記，寫一封約 120 字的電郵給知名遊戲評論員 Paul Achebe。','Write an email to the well-known board game reviewer Paul Achebe using information from the B1 Data File and your notes. Write around 120 words.',640,'email').replace('<label class="answer-field"','<div class="answer-email-head"><label>Subject: <input data-note="11-subject" aria-label="Email subject"></label></div><label class="answer-field"')+'</section>')
put(12,writing(12,'Task 6: Email, continued','任務 6：電郵續頁。','Continue your email here.',270,'email-cont')+'<p class="answer-end">END OF TASK 6</p><h3>Task 7: Report for company meeting <small>(20 marks)</small></h3>'+bi('Write a report on the questionnaire results and follow-up action for the company meeting using information from the B1 Data File. Write around 150 words.','利用乙部一資料檔，為公司會議撰寫約 150 字的問卷結果和跟進工作報告。')+'<label class="answer-field" for="2018-b1-12-report">Task 7 report</label><textarea class="answer-box" id="2018-b1-12-report" data-note="12-report" data-count-id="2018-b1-12-report" style="min-height:400px" aria-label="Task 7 report"></textarea><p class="answer-count" data-count-for="2018-b1-12-report">0 words</p></section>')
put(13,writing(13,'Task 7: Report, continued','任務 7：報告續頁。','Continue your report here.',700,'report-cont')+'<p class="answer-end">END OF TASK 7<br>END OF PART B1</p></section>')
